Occam - Application Specialization: C:/Users/Hashim/Dropbox/Occam 2.0/src/StrategySpecializer.cpp File Reference
StrategySpecializer.cpp File Reference
#include "llvm/Module.h"
#include "llvm/Function.h"
#include "llvm/Instruction.h"
#include "llvm/Constants.h"
#include "llvm/PassManager.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Support/CallSite.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "SpecializationTable.h"
#include "SpecializationPolicy.h"
#include "StrategySpecializer.h"
#include "Specializer.h"
#include <list>
#include <set>
#include <vector>
Classes
class anonymous_namespace{StrategySpecializer.cpp}::ParEvalOptPass
Namespaces
previrt
anonymous_namespace{StrategySpecializer.cpp}
Macros
#define DUMP 1
Functions
static bool trySpecializeFunction (Function *f, SpecializationTable &table, SpecializationPolicy *policy, std::list< Function * > &to_add)
static cl::opt< bool > anonymous_namespace{StrategySpecializer.cpp}::OptSpecialized ("Ppeval-opt", cl::Hidden, cl::init(false), cl::desc("optimize specialized function instances?"))
If the flag is specified , optimize specialized function instances.
static RegisterPass
< ParEvalOptPass > anonymous_namespace{StrategySpecializer.cpp}::X ("Ppeval","partial evaluation (inlining)", false, false)
Register the Ppeval Pass with the Pass Manager. The Pass provides partial evaluation (intra module specialization)
Macro Definition Documentation
#define DUMP 1
Definition at line 61 of file StrategySpecializer.cpp.
Function Documentation
static bool trySpecializeFunction (Function * f, SpecializationTable & table, SpecializationPolicy * policy, std::list< Function * > & to_add) static
The trySpecializeFunction iterates over all of the instructions in the function, looking for call instructions. If the call contains constant arguments, a specialized copy of the function corresponding to the arguments is looked up in the previrt::SpecializationTable (storing a list of applied specializations). If the table does not contain a version corresponding to the particular usage, a new cloned copy of the function is created, with arguments directly evaluated in the body of the function, hence fewer parameters to the function. The specialized version is added to the previrt::SpecializationTable for future reference.
Definition at line 72 of file StrategySpecializer.cpp.
References previrt::SpecializationTable::addSpecialization(), previrt::canSpecialize(), previrt::SpecializationTable::getSpecializations(), previrt::proto::I, previrt::specializeCallSite(), previrt::specializeFunction(), and previrt::SpecializationPolicy::specializeOn().
Referenced by previrt::SpecializerPass::runOnModule().