Occam - Application Specialization: previrt::WatchPass2 Class Reference
previrt::WatchPass2 Class Reference
Public Member Functions
WatchPass2 ()
virtual ~WatchPass2 ()
Default Destructor.
virtual bool runOnModule (Module &M)
Static Public Attributes
static char ID
Private Attributes
watch::proto::WatchInterface interface
The interface is an object that reads in a Google protocol buffer from a file interface defines the actions that need to be applied in order to create watch functions.
bool fancy
If fancy is set; a fancy failure function is created; one that takes the function name and the arguments.
bool allowLocal
If allowLocal is set, the local calls to the function (that is watched) are allowed.
std::string failureName
name of failure function; The function called in case the interface is violated
Detailed Description
The WatchPass2 Class is registered as a Pass with the PassManager internal database by the name 'Pwatch2'. The Pass creates watch functions for functions that are a part of the watch::proto::WatchInterface. It enforces a certain interface as specified in the watch::proto::WatchInterface Google protocol buffer.
The Pass takes four command line arguments. watch::proto::WatchInterface serialized files are passed following the 'Pwatch2-input' flag. The 'Pwatch2-local' flag if passed, specifies that local calls to the function should be allowed. The 'Pwatch2-fail' flag is followed by the name of the failure function, that is called in case the interface is violated. If the 'Pwatch2-fail' flag is specified, the failure function is created is a fancy failure function; it takes as argument, the name of the function that violated the interface and the set of arguments.
Definition at line 910 of file Watch2.cpp.
Constructor & Destructor Documentation
previrt::WatchPass2::WatchPass2 () inline
The constructor initializes the class data members fancy, allowLocal, failureName with the command line arguments specified to the Pass.
Definition at line 928 of file Watch2.cpp.
References previrt::WatchInput().
virtual previrt::WatchPass2::~WatchPass2 () inline virtual
Default Destructor.
Definition at line 958 of file Watch2.cpp.
Member Function Documentation
virtual bool previrt::WatchPass2::runOnModule (Module & M) inline virtual
The runOnModule routine iterates over all of the functions, creating watch functions for the ones specified in the interface, enforcing the interface as specified in the interface object (Google protocol buffer).
The procedure performed by the WatchPass2::runOnModule routine is as follows:
1) previrt::getExit is called to create a failure function; the function called when the interface is violated.
2) Iterating over all of the functions in the Module, calling previrt::patternMatches on each. If the function name is a pattern matching one of the interface hooks, a new function is created and previrt::watchFunction is called with the newly created watch function, to enforce an interface as specified by the watch::proto::ActionTree protecting calls to the original function.
3) The process in step2 is repeated for aliased functions.
4) The newly created watch functions are added to the module.
The watch::proto::WatchInterface buffer contains a list of Hooks; whereas each hook is a pair of watch::proto::PatternExpr and watch::proto:ActionTree. The watch::proto::PatternExpr identifies the function that needs to be watched out, and the watch::proto::ActionTree defines the set of tests that need to be applied to implement the watch functions.
Definition at line 985 of file Watch2.cpp.
References previrt::WatchContext::addAllFunctions(), previrt::WatchContext::added_functions, previrt::getAliasedFunction(), previrt::getExit(), previrt::patternMatches(), and previrt::watchFunction().
Member Data Documentation
bool previrt::WatchPass2::allowLocal private
If allowLocal is set, the local calls to the function (that is watched) are allowed.
Definition at line 919 of file Watch2.cpp.
std::string previrt::WatchPass2::failureName private
name of failure function; The function called in case the interface is violated
Definition at line 921 of file Watch2.cpp.
bool previrt::WatchPass2::fancy private
If fancy is set; a fancy failure function is created; one that takes the function name and the arguments.
Definition at line 917 of file Watch2.cpp.
char previrt::WatchPass2::ID static
Definition at line 923 of file Watch2.cpp.
watch::proto::WatchInterface previrt::WatchPass2::interface private
The interface is an object that reads in a Google protocol buffer from a file interface defines the actions that need to be applied in order to create watch functions.
Definition at line 915 of file Watch2.cpp.
The documentation for this class was generated from the following file:
C:/Users/Hashim/Dropbox/Occam 2.0/src/Watch2.cpp