Occam - Application Specialization: previrt::proto::PrevirtType_Int Class Reference
previrt::proto::PrevirtType_Int Class Reference
#include <Previrt.pb.h>
Public Member Functions
PrevirtType_Int ()
virtual ~PrevirtType_Int ()
PrevirtType_Int (const PrevirtType_Int &from)
PrevirtType_Int & operator= (const PrevirtType_Int &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (PrevirtType_Int *other)
PrevirtType_Int * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const PrevirtType_Int &from)
void MergeFrom (const PrevirtType_Int &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_bits () const
void clear_bits ()
inline::google::protobuf::uint32 bits () const
void set_bits (::google::protobuf::uint32 value)
bool has_value () const
void clear_value ()
const ::std::string & value () const
void set_value (const ::std::string &value)
void set_value (const char *value)
void set_value (const char *value, size_t size)
inline::std::string * mutable_value ()
inline::std::string * release_value ()
void set_allocated_value (::std::string *value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const PrevirtType_Int & default_instance ()
Static Public Attributes
static const int kBitsFieldNumber = 2
static const int kValueFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_bits ()
void clear_has_bits ()
void set_has_value ()
void clear_has_value ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::std::string * value_
::google::protobuf::uint32 bits_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(2+31)/32]
Static Private Attributes
static PrevirtType_Int * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 126 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::PrevirtType_Int::PrevirtType_Int ()
Definition at line 595 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::PrevirtType_Int::~PrevirtType_Int () virtual
Definition at line 616 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::PrevirtType_Int::PrevirtType_Int (const PrevirtType_Int & from)
Definition at line 603 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
google::protobuf::uint32 previrt::proto::PrevirtType_Int::bits () const inline
Definition at line 1822 of file Previrt.pb.h.
References bits_.
Referenced by ByteSize(), MergeFrom(), previrt::PrevirtType::operator==(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::PrevirtType_Int::ByteSize () const
Definition at line 762 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, bits(), has_bits(), has_value(), unknown_fields(), and value().
void previrt::proto::PrevirtType_Int::Clear ()
Definition at line 649 of file Previrt.pb.cc.
References _has_bits_, bits_, has_value(), mutable_unknown_fields(), and value_.
Referenced by CopyFrom().
void previrt::proto::PrevirtType_Int::clear_bits () inline
Definition at line 1818 of file Previrt.pb.h.
References bits_, and clear_has_bits().
void previrt::proto::PrevirtType_Int::clear_has_bits () inline private
Definition at line 1815 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_bits().
void previrt::proto::PrevirtType_Int::clear_has_value () inline private
Definition at line 1837 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_value(), release_value(), and set_allocated_value().
void previrt::proto::PrevirtType_Int::clear_value () inline
Definition at line 1840 of file Previrt.pb.h.
References clear_has_value(), and value_.
void previrt::proto::PrevirtType_Int::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 817 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::PrevirtType_Int::CopyFrom (const PrevirtType_Int & from)
Definition at line 823 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const PrevirtType_Int & previrt::proto::PrevirtType_Int::default_instance () static
Definition at line 638 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::PrevirtType::InitAsDefaultInstance(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::PrevirtType_Int::descriptor () static
Definition at line 633 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Int_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
int previrt::proto::PrevirtType_Int::GetCachedSize () const inline
Definition at line 167 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::PrevirtType_Int::GetMetadata () const
Definition at line 845 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Int_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Int_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
bool previrt::proto::PrevirtType_Int::has_bits () const inline
Definition at line 1809 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::PrevirtType_Int::has_value () const inline
Definition at line 1831 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::PrevirtType_Int::InitAsDefaultInstance () private
Definition at line 600 of file Previrt.pb.cc.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::PrevirtType_Int::IsInitialized () const
Definition at line 829 of file Previrt.pb.cc.
References _has_bits_.
void previrt::proto::PrevirtType_Int::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 792 of file Previrt.pb.cc.
Referenced by CopyFrom(), and PrevirtType_Int().
void previrt::proto::PrevirtType_Int::MergeFrom (const PrevirtType_Int & from)
Definition at line 804 of file Previrt.pb.cc.
References _has_bits_, bits(), has_bits(), has_value(), mutable_unknown_fields(), set_bits(), set_value(), unknown_fields(), and value().
bool previrt::proto::PrevirtType_Int::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 662 of file Previrt.pb.cc.
References bits_, DO_, mutable_unknown_fields(), mutable_value(), set_has_bits(), and value().
inline ::google::protobuf::UnknownFieldSet* previrt::proto::PrevirtType_Int::mutable_unknown_fields () inline
Definition at line 142 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
std::string * previrt::proto::PrevirtType_Int::mutable_value () inline
Definition at line 1870 of file Previrt.pb.h.
References set_has_value(), and value_.
Referenced by MergePartialFromCodedStream().
PrevirtType_Int * previrt::proto::PrevirtType_Int::New () const
Definition at line 645 of file Previrt.pb.cc.
References PrevirtType_Int().
PrevirtType_Int& previrt::proto::PrevirtType_Int::operator= (const PrevirtType_Int & from) inline
Definition at line 133 of file Previrt.pb.h.
References CopyFrom().
std::string * previrt::proto::PrevirtType_Int::release_value () inline
Definition at line 1877 of file Previrt.pb.h.
References clear_has_value(), and value_.
void previrt::proto::PrevirtType_Int::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 716 of file Previrt.pb.cc.
References bits(), has_bits(), has_value(), unknown_fields(), and value().
google::protobuf::uint8 * previrt::proto::PrevirtType_Int::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 738 of file Previrt.pb.cc.
References bits(), has_bits(), has_value(), unknown_fields(), and value().
void previrt::proto::PrevirtType_Int::set_allocated_value (::std::string * value) inline
Definition at line 1887 of file Previrt.pb.h.
References clear_has_value(), set_has_value(), value(), and value_.
void previrt::proto::PrevirtType_Int::set_bits (::google::protobuf::uint32 value) inline
Definition at line 1825 of file Previrt.pb.h.
References bits_, set_has_bits(), and value().
Referenced by MergeFrom().
void previrt::proto::PrevirtType_Int::set_has_bits () inline private
Definition at line 1812 of file Previrt.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_bits().
void previrt::proto::PrevirtType_Int::set_has_value () inline private
Definition at line 1834 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_value(), set_allocated_value(), and set_value().
void previrt::proto::PrevirtType_Int::set_value (const ::std::string & value) inline
Definition at line 1849 of file Previrt.pb.h.
References set_has_value(), and value_.
Referenced by MergeFrom().
void previrt::proto::PrevirtType_Int::set_value (const char * value) inline
Definition at line 1856 of file Previrt.pb.h.
References set_has_value(), and value_.
void previrt::proto::PrevirtType_Int::set_value (const char * value, size_t size) inline
Definition at line 1863 of file Previrt.pb.h.
References set_has_value(), and value_.
void previrt::proto::PrevirtType_Int::SetCachedSize (int size) const private
Definition at line 628 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::PrevirtType_Int::SharedCtor () private
Definition at line 609 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, bits_, and value_.
Referenced by PrevirtType_Int().
void previrt::proto::PrevirtType_Int::SharedDtor () private
Definition at line 620 of file Previrt.pb.cc.
References default_instance_, and value_.
Referenced by ~PrevirtType_Int().
void previrt::proto::PrevirtType_Int::Swap (PrevirtType_Int * other)
Definition at line 835 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, bits_, and value_.
const ::google::protobuf::UnknownFieldSet& previrt::proto::PrevirtType_Int::unknown_fields () const inline
Definition at line 138 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
const ::std::string & previrt::proto::PrevirtType_Int::value () const inline
Definition at line 1846 of file Previrt.pb.h.
References value_.
Referenced by ByteSize(), MergeFrom(), MergePartialFromCodedStream(), previrt::PrevirtType::operator==(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), set_allocated_value(), and set_bits().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::PrevirtType_Int::_cached_size_ mutable private
Definition at line 211 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::PrevirtType_Int::_has_bits_[(2+31)/32] private
Definition at line 212 of file Previrt.pb.h.
Referenced by ByteSize(), Clear(), clear_has_bits(), clear_has_value(), has_bits(), has_value(), IsInitialized(), MergeFrom(), set_has_bits(), set_has_value(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::PrevirtType_Int::_unknown_fields_ private
Definition at line 206 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
::google::protobuf::uint32 previrt::proto::PrevirtType_Int::bits_ private
Definition at line 209 of file Previrt.pb.h.
Referenced by bits(), Clear(), clear_bits(), MergePartialFromCodedStream(), set_bits(), SharedCtor(), and Swap().
PrevirtType_Int * previrt::proto::PrevirtType_Int::default_instance_ = NULL static private
Definition at line 219 of file Previrt.pb.h.
Referenced by default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
const int previrt::proto::PrevirtType_Int::kBitsFieldNumber = 2 static
Definition at line 183 of file Previrt.pb.h.
const int previrt::proto::PrevirtType_Int::kValueFieldNumber = 3 static
Definition at line 190 of file Previrt.pb.h.
::std::string* previrt::proto::PrevirtType_Int::value_ private
Definition at line 208 of file Previrt.pb.h.
Referenced by Clear(), clear_value(), mutable_value(), release_value(), set_allocated_value(), set_value(), SharedCtor(), SharedDtor(), Swap(), and value().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc