Occam - Application Specialization: previrt::proto::PrevirtType Class Reference
previrt::proto::PrevirtType Class Reference
#include <Previrt.pb.h>
Public Types
typedef PrevirtType_Int Int
typedef PrevirtType_Vec Vec
typedef PrevirtType_Str Str
typedef PrevirtType_Float Float
typedef PrevirtType_Global Global
Public Member Functions
PrevirtType ()
virtual ~PrevirtType ()
PrevirtType (const PrevirtType &from)
PrevirtType & operator= (const PrevirtType &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (PrevirtType *other)
PrevirtType * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const PrevirtType &from)
void MergeFrom (const PrevirtType &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_type () const
void clear_type ()
inline::previrt::proto::Type type () const
void set_type (::previrt::proto::Type value)
bool has_int_ () const
void clear_int_ ()
const
::previrt::proto::PrevirtType_Int & int_ () const
inline::previrt::proto::PrevirtType_Int * mutable_int_ ()
inline::previrt::proto::PrevirtType_Int * release_int_ ()
void set_allocated_int_ (::previrt::proto::PrevirtType_Int *int_)
bool has_vec () const
void clear_vec ()
const
::previrt::proto::PrevirtType_Vec & vec () const
inline::previrt::proto::PrevirtType_Vec * mutable_vec ()
inline::previrt::proto::PrevirtType_Vec * release_vec ()
void set_allocated_vec (::previrt::proto::PrevirtType_Vec *vec)
bool has_str () const
void clear_str ()
const
::previrt::proto::PrevirtType_Str & str () const
inline::previrt::proto::PrevirtType_Str * mutable_str ()
inline::previrt::proto::PrevirtType_Str * release_str ()
void set_allocated_str (::previrt::proto::PrevirtType_Str *str)
bool has_float_ () const
void clear_float_ ()
const
::previrt::proto::PrevirtType_Float & float_ () const
inline::previrt::proto::PrevirtType_Float * mutable_float_ ()
inline::previrt::proto::PrevirtType_Float * release_float_ ()
void set_allocated_float_ (::previrt::proto::PrevirtType_Float *float_)
bool has_global () const
void clear_global ()
const
::previrt::proto::PrevirtType_Global & global () const
inline::previrt::proto::PrevirtType_Global * mutable_global ()
inline::previrt::proto::PrevirtType_Global * release_global ()
void set_allocated_global (::previrt::proto::PrevirtType_Global *global)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const PrevirtType & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kIntFieldNumber = 10
static const int kVecFieldNumber = 20
static const int kStrFieldNumber = 30
static const int kFloatFieldNumber = 40
static const int kGlobalFieldNumber = 50
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_type ()
void clear_has_type ()
void set_has_int_ ()
void clear_has_int_ ()
void set_has_vec ()
void clear_has_vec ()
void set_has_str ()
void clear_has_str ()
void set_has_float_ ()
void clear_has_float_ ()
void set_has_global ()
void clear_has_global ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::previrt::proto::PrevirtType_Int * int__
::previrt::proto::PrevirtType_Vec * vec_
::previrt::proto::PrevirtType_Str * str_
::previrt::proto::PrevirtType_Float * float__
::previrt::proto::PrevirtType_Global * global_
int type_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(6+31)/32]
Static Private Attributes
static PrevirtType * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 599 of file Previrt.pb.h.
Member Typedef Documentation
typedef PrevirtType_Float previrt::proto::PrevirtType::Float
Definition at line 654 of file Previrt.pb.h.
typedef PrevirtType_Global previrt::proto::PrevirtType::Global
Definition at line 655 of file Previrt.pb.h.
typedef PrevirtType_Int previrt::proto::PrevirtType::Int
Definition at line 651 of file Previrt.pb.h.
typedef PrevirtType_Str previrt::proto::PrevirtType::Str
Definition at line 653 of file Previrt.pb.h.
typedef PrevirtType_Vec previrt::proto::PrevirtType::Vec
Definition at line 652 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::PrevirtType::PrevirtType ()
Definition at line 1852 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::PrevirtType::~PrevirtType () virtual
Definition at line 1882 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::PrevirtType::PrevirtType (const PrevirtType & from)
Definition at line 1865 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
int previrt::proto::PrevirtType::ByteSize () const
Definition at line 2146 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, float_(), global(), has_float_(), has_global(), has_int_(), has_str(), has_type(), has_vec(), int_(), str(), type(), unknown_fields(), and vec().
void previrt::proto::PrevirtType::Clear ()
Definition at line 1917 of file Previrt.pb.cc.
References _has_bits_, float__, global_, has_float_(), has_global(), has_int_(), has_str(), has_vec(), int__, mutable_unknown_fields(), str_, type_, and vec_.
Referenced by CopyFrom().
void previrt::proto::PrevirtType::clear_float_ () inline
Definition at line 2369 of file Previrt.pb.h.
References clear_has_float_(), and float__.
void previrt::proto::PrevirtType::clear_global () inline
Definition at line 2407 of file Previrt.pb.h.
References clear_has_global(), and global_.
void previrt::proto::PrevirtType::clear_has_float_ () inline private
Definition at line 2366 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_float_(), release_float_(), and set_allocated_float_().
void previrt::proto::PrevirtType::clear_has_global () inline private
Definition at line 2404 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_global(), release_global(), and set_allocated_global().
void previrt::proto::PrevirtType::clear_has_int_ () inline private
Definition at line 2252 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_int_(), release_int_(), and set_allocated_int_().
void previrt::proto::PrevirtType::clear_has_str () inline private
Definition at line 2328 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_str(), release_str(), and set_allocated_str().
void previrt::proto::PrevirtType::clear_has_type () inline private
Definition at line 2229 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_type().
void previrt::proto::PrevirtType::clear_has_vec () inline private
Definition at line 2290 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_vec(), release_vec(), and set_allocated_vec().
void previrt::proto::PrevirtType::clear_int_ () inline
Definition at line 2255 of file Previrt.pb.h.
References clear_has_int_(), and int__.
void previrt::proto::PrevirtType::clear_str () inline
Definition at line 2331 of file Previrt.pb.h.
References clear_has_str(), and str_.
void previrt::proto::PrevirtType::clear_type () inline
Definition at line 2232 of file Previrt.pb.h.
References clear_has_type(), and type_.
void previrt::proto::PrevirtType::clear_vec () inline
Definition at line 2293 of file Previrt.pb.h.
References clear_has_vec(), and vec_.
void previrt::proto::PrevirtType::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 2240 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::PrevirtType::CopyFrom (const PrevirtType & from)
Definition at line 2246 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const PrevirtType & previrt::proto::PrevirtType::default_instance () static
Definition at line 1906 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::ActionTree_Case::InitAsDefaultInstance(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::PrevirtType::descriptor () static
Definition at line 1901 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
const ::previrt::proto::PrevirtType_Float & previrt::proto::PrevirtType::float_ () const inline
Definition at line 2373 of file Previrt.pb.h.
References default_instance_, and float__.
Referenced by ByteSize(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_float_().
int previrt::proto::PrevirtType::GetCachedSize () const inline
Definition at line 640 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::PrevirtType::GetMetadata () const
Definition at line 2284 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
const ::previrt::proto::PrevirtType_Global & previrt::proto::PrevirtType::global () const inline
Definition at line 2411 of file Previrt.pb.h.
References default_instance_, and global_.
Referenced by ByteSize(), IsInitialized(), MergeFrom(), previrt::PrevirtType::operator==(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_global().
bool previrt::proto::PrevirtType::has_float_ () const inline
Definition at line 2360 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::PrevirtType::has_global () const inline
Definition at line 2398 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::PrevirtType::has_int_ () const inline
Definition at line 2246 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::PrevirtType::has_str () const inline
Definition at line 2322 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::PrevirtType::has_type () const inline
Definition at line 2223 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::PrevirtType::has_vec () const inline
Definition at line 2284 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::PrevirtType::InitAsDefaultInstance () private
Definition at line 1857 of file Previrt.pb.cc.
References previrt::proto::PrevirtType_Int::default_instance(), previrt::proto::PrevirtType_Vec::default_instance(), previrt::proto::PrevirtType_Str::default_instance(), previrt::proto::PrevirtType_Float::default_instance(), previrt::proto::PrevirtType_Global::default_instance(), float__, global_, int__, str_, and vec_.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
const ::previrt::proto::PrevirtType_Int & previrt::proto::PrevirtType::int_ () const inline
Definition at line 2259 of file Previrt.pb.h.
References default_instance_, and int__.
Referenced by ByteSize(), IsInitialized(), MergeFrom(), previrt::PrevirtType::operator==(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_int_().
bool previrt::proto::PrevirtType::IsInitialized () const
Definition at line 2252 of file Previrt.pb.cc.
References _has_bits_, float_(), global(), has_float_(), has_global(), has_int_(), has_vec(), int_(), and vec().
void previrt::proto::PrevirtType::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 2203 of file Previrt.pb.cc.
Referenced by CopyFrom(), and PrevirtType().
void previrt::proto::PrevirtType::MergeFrom (const PrevirtType & from)
Definition at line 2215 of file Previrt.pb.cc.
References _has_bits_, float_(), global(), has_float_(), has_global(), has_int_(), has_str(), has_type(), has_vec(), int_(), mutable_float_(), mutable_global(), mutable_int_(), mutable_str(), mutable_unknown_fields(), mutable_vec(), set_type(), str(), type(), unknown_fields(), and vec().
bool previrt::proto::PrevirtType::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 1940 of file Previrt.pb.cc.
References DO_, mutable_float_(), mutable_global(), mutable_int_(), mutable_str(), mutable_unknown_fields(), mutable_vec(), set_type(), and previrt::proto::Type_IsValid().
previrt::proto::PrevirtType_Float * previrt::proto::PrevirtType::mutable_float_ () inline
Definition at line 2376 of file Previrt.pb.h.
References float__, and set_has_float_().
Referenced by previrt::PrevirtType::abstract(), MergeFrom(), and MergePartialFromCodedStream().
previrt::proto::PrevirtType_Global * previrt::proto::PrevirtType::mutable_global () inline
Definition at line 2414 of file Previrt.pb.h.
References global_, and set_has_global().
Referenced by previrt::PrevirtType::abstract(), MergeFrom(), and MergePartialFromCodedStream().
previrt::proto::PrevirtType_Int * previrt::proto::PrevirtType::mutable_int_ () inline
Definition at line 2262 of file Previrt.pb.h.
References int__, and set_has_int_().
Referenced by previrt::PrevirtType::abstract(), MergeFrom(), and MergePartialFromCodedStream().
previrt::proto::PrevirtType_Str * previrt::proto::PrevirtType::mutable_str () inline
Definition at line 2338 of file Previrt.pb.h.
References set_has_str(), and str_.
Referenced by previrt::PrevirtType::abstract(), MergeFrom(), and MergePartialFromCodedStream().
inline ::google::protobuf::UnknownFieldSet* previrt::proto::PrevirtType::mutable_unknown_fields () inline
Definition at line 615 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
previrt::proto::PrevirtType_Vec * previrt::proto::PrevirtType::mutable_vec () inline
Definition at line 2300 of file Previrt.pb.h.
References set_has_vec(), and vec_.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
PrevirtType * previrt::proto::PrevirtType::New () const
Definition at line 1913 of file Previrt.pb.cc.
References PrevirtType().
PrevirtType& previrt::proto::PrevirtType::operator= (const PrevirtType & from) inline
Definition at line 606 of file Previrt.pb.h.
References CopyFrom().
previrt::proto::PrevirtType_Float * previrt::proto::PrevirtType::release_float_ () inline
Definition at line 2381 of file Previrt.pb.h.
References clear_has_float_(), and float__.
previrt::proto::PrevirtType_Global * previrt::proto::PrevirtType::release_global () inline
Definition at line 2419 of file Previrt.pb.h.
References clear_has_global(), and global_.
previrt::proto::PrevirtType_Int * previrt::proto::PrevirtType::release_int_ () inline
Definition at line 2267 of file Previrt.pb.h.
References clear_has_int_(), and int__.
previrt::proto::PrevirtType_Str * previrt::proto::PrevirtType::release_str () inline
Definition at line 2343 of file Previrt.pb.h.
References clear_has_str(), and str_.
previrt::proto::PrevirtType_Vec * previrt::proto::PrevirtType::release_vec () inline
Definition at line 2305 of file Previrt.pb.h.
References clear_has_vec(), and vec_.
void previrt::proto::PrevirtType::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 2052 of file Previrt.pb.cc.
References float_(), global(), has_float_(), has_global(), has_int_(), has_str(), has_type(), has_vec(), int_(), str(), type(), unknown_fields(), and vec().
google::protobuf::uint8 * previrt::proto::PrevirtType::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 2096 of file Previrt.pb.cc.
References float_(), global(), has_float_(), has_global(), has_int_(), has_str(), has_type(), has_vec(), int_(), str(), type(), unknown_fields(), and vec().
void previrt::proto::PrevirtType::set_allocated_float_ (::previrt::proto::PrevirtType_Float * float_) inline
Definition at line 2387 of file Previrt.pb.h.
References clear_has_float_(), float_(), float__, and set_has_float_().
void previrt::proto::PrevirtType::set_allocated_global (::previrt::proto::PrevirtType_Global * global) inline
Definition at line 2425 of file Previrt.pb.h.
References clear_has_global(), global(), global_, and set_has_global().
void previrt::proto::PrevirtType::set_allocated_int_ (::previrt::proto::PrevirtType_Int * int_) inline
Definition at line 2273 of file Previrt.pb.h.
References clear_has_int_(), int_(), int__, and set_has_int_().
void previrt::proto::PrevirtType::set_allocated_str (::previrt::proto::PrevirtType_Str * str) inline
Definition at line 2349 of file Previrt.pb.h.
References clear_has_str(), set_has_str(), str(), and str_.
void previrt::proto::PrevirtType::set_allocated_vec (::previrt::proto::PrevirtType_Vec * vec) inline
Definition at line 2311 of file Previrt.pb.h.
References clear_has_vec(), set_has_vec(), vec(), and vec_.
void previrt::proto::PrevirtType::set_has_float_ () inline private
Definition at line 2363 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_float_(), and set_allocated_float_().
void previrt::proto::PrevirtType::set_has_global () inline private
Definition at line 2401 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_global(), and set_allocated_global().
void previrt::proto::PrevirtType::set_has_int_ () inline private
Definition at line 2249 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_int_(), and set_allocated_int_().
void previrt::proto::PrevirtType::set_has_str () inline private
Definition at line 2325 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_str(), and set_allocated_str().
void previrt::proto::PrevirtType::set_has_type () inline private
Definition at line 2226 of file Previrt.pb.h.
References _has_bits_.
Referenced by set_type().
void previrt::proto::PrevirtType::set_has_vec () inline private
Definition at line 2287 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_vec(), and set_allocated_vec().
void previrt::proto::PrevirtType::set_type (::previrt::proto::Type value) inline
Definition at line 2239 of file Previrt.pb.h.
References set_has_type(), type_, and previrt::proto::Type_IsValid().
Referenced by previrt::PrevirtType::abstract(), MergeFrom(), MergePartialFromCodedStream(), and previrt::PrevirtType::unknown().
void previrt::proto::PrevirtType::SetCachedSize (int size) const private
Definition at line 1896 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::PrevirtType::SharedCtor () private
Definition at line 1871 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, float__, global_, int__, str_, type_, and vec_.
Referenced by PrevirtType().
void previrt::proto::PrevirtType::SharedDtor () private
Definition at line 1886 of file Previrt.pb.cc.
References default_instance_, float__, global_, int__, str_, and vec_.
Referenced by ~PrevirtType().
const ::previrt::proto::PrevirtType_Str & previrt::proto::PrevirtType::str () const inline
Definition at line 2335 of file Previrt.pb.h.
References default_instance_, and str_.
Referenced by ByteSize(), MergeFrom(), previrt::PrevirtType::operator==(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_str().
void previrt::proto::PrevirtType::Swap (PrevirtType * other)
Definition at line 2270 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, float__, global_, int__, str_, type_, and vec_.
previrt::proto::Type previrt::proto::PrevirtType::type () const inline
Definition at line 2236 of file Previrt.pb.h.
References type_.
Referenced by ByteSize(), MergeFrom(), previrt::PrevirtType::operator==(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
const ::google::protobuf::UnknownFieldSet& previrt::proto::PrevirtType::unknown_fields () const inline
Definition at line 611 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
const ::previrt::proto::PrevirtType_Vec & previrt::proto::PrevirtType::vec () const inline
Definition at line 2297 of file Previrt.pb.h.
References default_instance_, and vec_.
Referenced by ByteSize(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_vec().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::PrevirtType::_cached_size_ mutable private
Definition at line 735 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::PrevirtType::_has_bits_[(6+31)/32] private
Definition at line 736 of file Previrt.pb.h.
Referenced by ByteSize(), Clear(), clear_has_float_(), clear_has_global(), clear_has_int_(), clear_has_str(), clear_has_type(), clear_has_vec(), has_float_(), has_global(), has_int_(), has_str(), has_type(), has_vec(), IsInitialized(), MergeFrom(), set_has_float_(), set_has_global(), set_has_int_(), set_has_str(), set_has_type(), set_has_vec(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::PrevirtType::_unknown_fields_ private
Definition at line 726 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
PrevirtType * previrt::proto::PrevirtType::default_instance_ = NULL static private
Definition at line 743 of file Previrt.pb.h.
Referenced by default_instance(), float_(), global(), int_(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), SharedDtor(), str(), and vec().
::previrt::proto::PrevirtType_Float* previrt::proto::PrevirtType::float__ private
Definition at line 731 of file Previrt.pb.h.
Referenced by Clear(), clear_float_(), float_(), InitAsDefaultInstance(), mutable_float_(), release_float_(), set_allocated_float_(), SharedCtor(), SharedDtor(), and Swap().
::previrt::proto::PrevirtType_Global* previrt::proto::PrevirtType::global_ private
Definition at line 732 of file Previrt.pb.h.
Referenced by Clear(), clear_global(), global(), InitAsDefaultInstance(), mutable_global(), release_global(), set_allocated_global(), SharedCtor(), SharedDtor(), and Swap().
::previrt::proto::PrevirtType_Int* previrt::proto::PrevirtType::int__ private
Definition at line 728 of file Previrt.pb.h.
Referenced by Clear(), clear_int_(), InitAsDefaultInstance(), int_(), mutable_int_(), release_int_(), set_allocated_int_(), SharedCtor(), SharedDtor(), and Swap().
const int previrt::proto::PrevirtType::kFloatFieldNumber = 40 static
Definition at line 696 of file Previrt.pb.h.
const int previrt::proto::PrevirtType::kGlobalFieldNumber = 50 static
Definition at line 705 of file Previrt.pb.h.
const int previrt::proto::PrevirtType::kIntFieldNumber = 10 static
Definition at line 669 of file Previrt.pb.h.
const int previrt::proto::PrevirtType::kStrFieldNumber = 30 static
Definition at line 687 of file Previrt.pb.h.
const int previrt::proto::PrevirtType::kTypeFieldNumber = 1 static
Definition at line 662 of file Previrt.pb.h.
const int previrt::proto::PrevirtType::kVecFieldNumber = 20 static
Definition at line 678 of file Previrt.pb.h.
::previrt::proto::PrevirtType_Str* previrt::proto::PrevirtType::str_ private
Definition at line 730 of file Previrt.pb.h.
Referenced by Clear(), clear_str(), InitAsDefaultInstance(), mutable_str(), release_str(), set_allocated_str(), SharedCtor(), SharedDtor(), str(), and Swap().
int previrt::proto::PrevirtType::type_ private
Definition at line 733 of file Previrt.pb.h.
Referenced by Clear(), clear_type(), set_type(), SharedCtor(), Swap(), and type().
::previrt::proto::PrevirtType_Vec* previrt::proto::PrevirtType::vec_ private
Definition at line 729 of file Previrt.pb.h.
Referenced by Clear(), clear_vec(), InitAsDefaultInstance(), mutable_vec(), release_vec(), set_allocated_vec(), SharedCtor(), SharedDtor(), Swap(), and vec().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc