Occam - Application Specialization: previrt::proto::PrevirtType_Str Class Reference
previrt::proto::PrevirtType_Str Class Reference
#include <Previrt.pb.h>
Public Member Functions
PrevirtType_Str ()
virtual ~PrevirtType_Str ()
PrevirtType_Str (const PrevirtType_Str &from)
PrevirtType_Str & operator= (const PrevirtType_Str &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (PrevirtType_Str *other)
PrevirtType_Str * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const PrevirtType_Str &from)
void MergeFrom (const PrevirtType_Str &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_data () const
void clear_data ()
const ::std::string & data () const
void set_data (const ::std::string &value)
void set_data (const char *value)
void set_data (const void *value, size_t size)
inline::std::string * mutable_data ()
inline::std::string * release_data ()
void set_allocated_data (::std::string *data)
bool has_cstr () const
void clear_cstr ()
bool cstr () const
void set_cstr (bool value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const PrevirtType_Str & default_instance ()
Static Public Attributes
static const int kDataFieldNumber = 31
static const int kCstrFieldNumber = 32
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_data ()
void clear_has_data ()
void set_has_cstr ()
void clear_has_cstr ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::std::string * data_
bool cstr_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(2+31)/32]
Static Private Attributes
static PrevirtType_Str * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 308 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::PrevirtType_Str::PrevirtType_Str ()
Definition at line 1067 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::PrevirtType_Str::~PrevirtType_Str () virtual
Definition at line 1088 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::PrevirtType_Str::PrevirtType_Str (const PrevirtType_Str & from)
Definition at line 1075 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
int previrt::proto::PrevirtType_Str::ByteSize () const
Definition at line 1225 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, data(), has_cstr(), has_data(), and unknown_fields().
void previrt::proto::PrevirtType_Str::Clear ()
Definition at line 1121 of file Previrt.pb.cc.
References _has_bits_, cstr_, data_, has_data(), and mutable_unknown_fields().
Referenced by CopyFrom().
void previrt::proto::PrevirtType_Str::clear_cstr () inline
Definition at line 2013 of file Previrt.pb.h.
References clear_has_cstr(), and cstr_.
void previrt::proto::PrevirtType_Str::clear_data () inline
Definition at line 1943 of file Previrt.pb.h.
References clear_has_data(), and data_.
void previrt::proto::PrevirtType_Str::clear_has_cstr () inline private
Definition at line 2010 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_cstr().
void previrt::proto::PrevirtType_Str::clear_has_data () inline private
Definition at line 1940 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_data(), release_data(), and set_allocated_data().
void previrt::proto::PrevirtType_Str::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1278 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::PrevirtType_Str::CopyFrom (const PrevirtType_Str & from)
Definition at line 1284 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
bool previrt::proto::PrevirtType_Str::cstr () const inline
Definition at line 2017 of file Previrt.pb.h.
References cstr_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
const ::std::string & previrt::proto::PrevirtType_Str::data () const inline
Definition at line 1949 of file Previrt.pb.h.
References data_.
Referenced by ByteSize(), MergeFrom(), previrt::PrevirtType::operator==(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_data().
const PrevirtType_Str & previrt::proto::PrevirtType_Str::default_instance () static
Definition at line 1110 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::PrevirtType::InitAsDefaultInstance(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::PrevirtType_Str::descriptor () static
Definition at line 1105 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Str_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
int previrt::proto::PrevirtType_Str::GetCachedSize () const inline
Definition at line 349 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::PrevirtType_Str::GetMetadata () const
Definition at line 1305 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Str_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Str_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
bool previrt::proto::PrevirtType_Str::has_cstr () const inline
Definition at line 2004 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::PrevirtType_Str::has_data () const inline
Definition at line 1934 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::PrevirtType_Str::InitAsDefaultInstance () private
Definition at line 1072 of file Previrt.pb.cc.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::PrevirtType_Str::IsInitialized () const
Definition at line 1290 of file Previrt.pb.cc.
void previrt::proto::PrevirtType_Str::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 1253 of file Previrt.pb.cc.
Referenced by CopyFrom(), and PrevirtType_Str().
void previrt::proto::PrevirtType_Str::MergeFrom (const PrevirtType_Str & from)
Definition at line 1265 of file Previrt.pb.cc.
References _has_bits_, cstr(), data(), has_cstr(), has_data(), mutable_unknown_fields(), set_cstr(), set_data(), and unknown_fields().
bool previrt::proto::PrevirtType_Str::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 1134 of file Previrt.pb.cc.
References cstr_, DO_, mutable_data(), mutable_unknown_fields(), and set_has_cstr().
std::string * previrt::proto::PrevirtType_Str::mutable_data () inline
Definition at line 1973 of file Previrt.pb.h.
References data_, and set_has_data().
Referenced by MergePartialFromCodedStream().
inline ::google::protobuf::UnknownFieldSet* previrt::proto::PrevirtType_Str::mutable_unknown_fields () inline
Definition at line 324 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
PrevirtType_Str * previrt::proto::PrevirtType_Str::New () const
Definition at line 1117 of file Previrt.pb.cc.
References PrevirtType_Str().
PrevirtType_Str& previrt::proto::PrevirtType_Str::operator= (const PrevirtType_Str & from) inline
Definition at line 315 of file Previrt.pb.h.
References CopyFrom().
std::string * previrt::proto::PrevirtType_Str::release_data () inline
Definition at line 1980 of file Previrt.pb.h.
References clear_has_data(), and data_.
void previrt::proto::PrevirtType_Str::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 1185 of file Previrt.pb.cc.
References cstr(), data(), has_cstr(), has_data(), and unknown_fields().
google::protobuf::uint8 * previrt::proto::PrevirtType_Str::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 1204 of file Previrt.pb.cc.
References cstr(), data(), has_cstr(), has_data(), and unknown_fields().
void previrt::proto::PrevirtType_Str::set_allocated_data (::std::string * data) inline
Definition at line 1990 of file Previrt.pb.h.
References clear_has_data(), data(), data_, and set_has_data().
void previrt::proto::PrevirtType_Str::set_cstr (bool value) inline
Definition at line 2020 of file Previrt.pb.h.
References cstr_, and set_has_cstr().
Referenced by MergeFrom().
void previrt::proto::PrevirtType_Str::set_data (const ::std::string & value) inline
Definition at line 1952 of file Previrt.pb.h.
References data_, and set_has_data().
Referenced by MergeFrom().
void previrt::proto::PrevirtType_Str::set_data (const char * value) inline
Definition at line 1959 of file Previrt.pb.h.
References data_, and set_has_data().
void previrt::proto::PrevirtType_Str::set_data (const void * value, size_t size) inline
Definition at line 1966 of file Previrt.pb.h.
References data_, and set_has_data().
void previrt::proto::PrevirtType_Str::set_has_cstr () inline private
Definition at line 2007 of file Previrt.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_cstr().
void previrt::proto::PrevirtType_Str::set_has_data () inline private
Definition at line 1937 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_data(), set_allocated_data(), and set_data().
void previrt::proto::PrevirtType_Str::SetCachedSize (int size) const private
Definition at line 1100 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::PrevirtType_Str::SharedCtor () private
Definition at line 1081 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, cstr_, and data_.
Referenced by PrevirtType_Str().
void previrt::proto::PrevirtType_Str::SharedDtor () private
Definition at line 1092 of file Previrt.pb.cc.
References data_, and default_instance_.
Referenced by ~PrevirtType_Str().
void previrt::proto::PrevirtType_Str::Swap (PrevirtType_Str * other)
Definition at line 1295 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, cstr_, and data_.
const ::google::protobuf::UnknownFieldSet& previrt::proto::PrevirtType_Str::unknown_fields () const inline
Definition at line 320 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::PrevirtType_Str::_cached_size_ mutable private
Definition at line 393 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::PrevirtType_Str::_has_bits_[(2+31)/32] private
Definition at line 394 of file Previrt.pb.h.
Referenced by ByteSize(), Clear(), clear_has_cstr(), clear_has_data(), has_cstr(), has_data(), MergeFrom(), set_has_cstr(), set_has_data(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::PrevirtType_Str::_unknown_fields_ private
Definition at line 388 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
bool previrt::proto::PrevirtType_Str::cstr_ private
Definition at line 391 of file Previrt.pb.h.
Referenced by Clear(), clear_cstr(), cstr(), MergePartialFromCodedStream(), set_cstr(), SharedCtor(), and Swap().
::std::string* previrt::proto::PrevirtType_Str::data_ private
Definition at line 390 of file Previrt.pb.h.
Referenced by Clear(), clear_data(), data(), mutable_data(), release_data(), set_allocated_data(), set_data(), SharedCtor(), SharedDtor(), and Swap().
PrevirtType_Str * previrt::proto::PrevirtType_Str::default_instance_ = NULL static private
Definition at line 401 of file Previrt.pb.h.
Referenced by default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
const int previrt::proto::PrevirtType_Str::kCstrFieldNumber = 32 static
Definition at line 377 of file Previrt.pb.h.
const int previrt::proto::PrevirtType_Str::kDataFieldNumber = 31 static
Definition at line 365 of file Previrt.pb.h.
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc