Occam - Application Specialization: previrt::SpecializationTable Class Reference
previrt::SpecializationTable Class Reference
#include <SpecializationTable.h>
Classes
struct Specialization
Public Types
typedef llvm::Value ** SpecScheme
typedef llvm::Value *const * ConstSpecScheme
Public Member Functions
SpecializationTable ()
Default constructor.
SpecializationTable (llvm::Module *m)
virtual ~SpecializationTable ()
void initialize (llvm::Module *)
void getSpecializations (llvm::Function *, ConstSpecScheme, std::vector< const Specialization * > &) const
bool addSpecialization (llvm::Function *, ConstSpecScheme, llvm::Function *, bool record=true)
Specialization * getSpecialization (llvm::Function *) const
Private Types
typedef std::map
< llvm::Function
*, Specialization * > SpecTable
Private Attributes
SpecTable specialized
A map containing the specialization structures against function pointers.
llvm::Module * module
The Module that is specialized.
Detailed Description
The SpecializationTable is a repository of specializations. If a specialized version of a function has been created, specific to a set of arguments, there is no need to create another version, if the function is called with exactly the same arguments. Therefore before a specialized copy of a function is required, it is looked up in the SpecializationTable. If a function corresponding to the specialization exists, it is retrieved from the table, otherwise previrt::specializeFunction is called to create a new specialized version with respect to the usage.
Definition at line 71 of file SpecializationTable.h.
Member Typedef Documentation
typedef llvm::Value* const* previrt::SpecializationTable::ConstSpecScheme
Definition at line 75 of file SpecializationTable.h.
typedef llvm::Value** previrt::SpecializationTable::SpecScheme
Definition at line 74 of file SpecializationTable.h.
typedef std::map<llvm::Function*,Specialization*> previrt::SpecializationTable::SpecTable private
Definition at line 97 of file SpecializationTable.h.
Constructor & Destructor Documentation
previrt::SpecializationTable::SpecializationTable ()
Default constructor.
Default constructor
Definition at line 102 of file SpecializationTable.cpp.
previrt::SpecializationTable::SpecializationTable (llvm::Module * m)
Overloaded Constructor, takes as argument a Module m, and calls SpecializationTable::initialize, to initialize the specialization table
previrt::SpecializationTable::~SpecializationTable () virtual
Destructor releases memory allocated for each specialization in the SpecializationTable
Destructor, free memory for each of the Specialization Node.
Definition at line 186 of file SpecializationTable.cpp.
References specialized.
Member Function Documentation
bool previrt::SpecializationTable::addSpecialization (llvm::Function * , ConstSpecScheme , llvm::Function * , bool record = true)
The addSpecialization function creates a Specialization node against a function pointer. Adds an entry for a specialization of a function with respect to a certain usage, so that if the function is called again with the same usage, the once created specialized copy is used rather creating a new one.
Parameters
parent a pointer to the original function.
scheme argument specifying the specialization scheme, values for arguments to be specialized and NULL otherwise.
specialization specialized version of the function
record a boolean parameter indicating if meta data is to be added to the Module.
Definition at line 288 of file SpecializationTable.cpp.
References previrt::SpecializationTable::Specialization::args, previrt::SpecializationTable::Specialization::children, getSpecialization(), previrt::SpecializationTable::Specialization::handle, module, previrt::SpecializationTable::Specialization::parent, and specialized.
Referenced by initialize(), and trySpecializeFunction().
Specialization * previrt::SpecializationTable::getSpecialization (llvm::Function *) const
In case the specialization Map has a specialization pointer for the Function 'f', it simply returns the pointer otherwise creates a new specialization object for the Function f. The function is called to retrieve all the specialized versions of the Function 'f'
Definition at line 347 of file SpecializationTable.cpp.
References previrt::SpecializationTable::Specialization::args, previrt::SpecializationTable::Specialization::handle, previrt::SpecializationTable::Specialization::parent, and specialized.
Referenced by addSpecialization(), and getSpecializations().
void previrt::SpecializationTable::getSpecializations (llvm::Function * , ConstSpecScheme , std::vector< const Specialization * > &) const
Returns all the specializations against a function that are at least as strict as specified by the scheme (calling SpecializationTable::getSpecializations). A specialization is as strict as the other if it specializes no more arguments as compared to the other. For example, consider a function with three arguments, and the scheme specifies only the first argument as specialize-able (NON-NULL value), then all specializations that specialize the first argument, or the ones specializing none are returned. Essentially we want only the matching specializations, therefore in the files StrategySpecializer.cpp line 167, SpecializationTable::refines is called once again this time with inverting the specScheme (to specialize with respect to), and the specialization scheme of the arguments, thereby only functions that take exactly the same arguments can be extracted from the Specialization Table
Definition at line 258 of file SpecializationTable.cpp.
References previrt::SpecializationTable::Specialization::children, getSpecialization(), and previrt::SpecializationTable::Specialization::refines().
Referenced by trySpecializeFunction().
void previrt::SpecializationTable::initialize (llvm::Module *)
The meta data can contain a list of specializations (names of original functions and specialized versions). If any specialization meta data is available the initialize routine fills in the Specialization Table with the data.
Definition at line 119 of file SpecializationTable.cpp.
References addSpecialization(), and module.
Member Data Documentation
llvm::Module* previrt::SpecializationTable::module private
The Module that is specialized.
Definition at line 101 of file SpecializationTable.h.
Referenced by addSpecialization(), and initialize().
SpecTable previrt::SpecializationTable::specialized mutable private
A map containing the specialization structures against function pointers.
Definition at line 99 of file SpecializationTable.h.
Referenced by addSpecialization(), getSpecialization(), and ~SpecializationTable().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/SpecializationTable.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/SpecializationTable.cpp