Occam - Application Specialization: previrt::ComponentInterface Class Reference
previrt::ComponentInterface Class Reference
#include <PrevirtualizeInterfaces.h>
Public Types
typedef llvm::StringMap
< std::vector< CallInfo * >
>::const_iterator FunctionIterator
typedef std::vector< CallInfo * >
::const_iterator CallIterator
Public Member Functions
ComponentInterface ()
Default constructor.
virtual ~ComponentInterface ()
Default destructor.
void call (FunctionHandle f, llvm::User::op_iterator args_begin, llvm::User::op_iterator args_end)
void callAny (const llvm::Function *f)
void reference (llvm::StringRef)
CallInfo * getOrCreateCall (FunctionHandle f, const std::vector< PrevirtType > &args)
void dump () const
FunctionIterator begin () const
FunctionIterator end () const
FunctionIterator find (llvm::StringRef) const
CallIterator call_begin (llvm::StringRef) const
CallIterator call_end (llvm::StringRef) const
CallIterator call_begin (FunctionIterator) const
CallIterator call_end (FunctionIterator) const
bool readFromFile (const std::string &filename)
Public Attributes
llvm::StringMap< std::vector
< CallInfo * > > calls
llvm StringMap – This is an unconventional map that is specialized for handling keys that are "strings", which are basically ranges of bytes. This does some funky memory allocation and hashing things to make it extremely efficient, storing the string data after the value in the map
std::set< std::string > references
The set of external references.
Detailed Description
The ComponentInterface class logs the external calls and references made from a module, ComponentInterface is used within the class previrt::GatherInterface2Pass (gathering references and external calls) and SpecializeComponentPass (creating specialized functions wrt to the calls in the interface)
Definition at line 89 of file PrevirtualizeInterfaces.h.
Member Typedef Documentation
typedef std::vector<CallInfo*>::const_iterator previrt::ComponentInterface::CallIterator
Definition at line 94 of file PrevirtualizeInterfaces.h.
typedef llvm::StringMap<std::vector<CallInfo*> >::const_iterator previrt::ComponentInterface::FunctionIterator
Definition at line 93 of file PrevirtualizeInterfaces.h.
Constructor & Destructor Documentation
previrt::ComponentInterface::ComponentInterface ()
Default constructor.
Definition at line 167 of file PrevirtualizeInterfaces.cpp.
previrt::ComponentInterface::~ComponentInterface () virtual
Default destructor.
Definition at line 172 of file PrevirtualizeInterfaces.cpp.
Member Function Documentation
ComponentInterface::FunctionIterator previrt::ComponentInterface::begin () const
Returns the starting iterator of the calls list in the previrt::ComponentInterface
Definition at line 305 of file PrevirtualizeInterfaces.cpp.
Referenced by previrt::enforceInterface(), previrt::GatherInterface2Pass::runOnModule(), and previrt::SpecializeComponent().
void previrt::ComponentInterface::call (FunctionHandle f, llvm::User::op_iterator args_begin, llvm::User::op_iterator args_end)
The function adds a call to the ComponentInterface, the call information includes the name of the call, and the set of arguments The calls are logged in the 'Pinterface2' Pass implemented in the class previrt::GatherInterface2Pass
Definition at line 187 of file PrevirtualizeInterfaces.cpp.
References previrt::CallInfo::count, and NO_MATCH.
CallIterator previrt::ComponentInterface::call_begin (llvm::StringRef) const
Referenced by previrt::getContractFromInterface(), previrt::ComponentInterfaceTransform::lookupRewrite(), and previrt::SpecializeComponent().
ComponentInterface::CallIterator previrt::ComponentInterface::call_begin (FunctionIterator i) const
Definition at line 344 of file PrevirtualizeInterfaces.cpp.
CallIterator previrt::ComponentInterface::call_end (llvm::StringRef) const
Referenced by previrt::getContractFromInterface(), previrt::ComponentInterfaceTransform::lookupRewrite(), and previrt::SpecializeComponent().
ComponentInterface::CallIterator previrt::ComponentInterface::call_end (FunctionIterator i) const
Definition at line 349 of file PrevirtualizeInterfaces.cpp.
void previrt::ComponentInterface::callAny (const llvm::Function * f)
void previrt::ComponentInterface::dump () const
Used for debugging
Definition at line 290 of file PrevirtualizeInterfaces.cpp.
Referenced by previrt::MinimizeComponent().
ComponentInterface::FunctionIterator previrt::ComponentInterface::end () const
Returns the ending iterator of the calls list in the previrt::ComponentInterface
Definition at line 312 of file PrevirtualizeInterfaces.cpp.
Referenced by previrt::enforceInterface(), previrt::getContractFromInterface(), previrt::GatherInterface2Pass::runOnModule(), and previrt::SpecializeComponent().
ComponentInterface::FunctionIterator previrt::ComponentInterface::find (llvm::StringRef) const
Definition at line 319 of file PrevirtualizeInterfaces.cpp.
Referenced by previrt::getContractFromInterface().
CallInfo * previrt::ComponentInterface::getOrCreateCall (FunctionHandle f, const std::vector< PrevirtType > & args)
Definition at line 255 of file PrevirtualizeInterfaces.cpp.
bool previrt::ComponentInterface::readFromFile (const std::string & filename)
Given the file name, the function parses it into the previrt::proto::ComponentInterface (Google protocol buffer), and then copies it into an object of type previrt::ComponentInterface and returns the object
Definition at line 411 of file PrevirtualizeInterfaces.cpp.
Referenced by previrt::GatherInterface2Pass::runOnModule().
void previrt::ComponentInterface::reference (llvm::StringRef)
Add a reference to the references set (class data member), The set of externals is collected and added to the previrt::ComponentInterface in the 'Pinterface2' Pass implemented in the class previrt::GatherInterface2Pass.
Definition at line 249 of file PrevirtualizeInterfaces.cpp.
Member Data Documentation
llvm::StringMap<std::vector<CallInfo*> > previrt::ComponentInterface::calls
llvm StringMap – This is an unconventional map that is specialized for handling keys that are "strings", which are basically ranges of bytes. This does some funky memory allocation and hashing things to make it extremely efficient, storing the string data after the value in the map
Definition at line 100 of file PrevirtualizeInterfaces.h.
Referenced by previrt::ComponentInterfaceTransform::lookupRewrite(), and previrt::MinimizeComponent().
std::set<std::string> previrt::ComponentInterface::references
The set of external references.
Definition at line 102 of file PrevirtualizeInterfaces.h.
Referenced by previrt::MinimizeComponent().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/PrevirtualizeInterfaces.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/PrevirtualizeInterfaces.cpp