Occam - Application Specialization: previrt::proto::ComponentInterface Class Reference
previrt::proto::ComponentInterface Class Reference
#include <Previrt.pb.h>
Public Member Functions
ComponentInterface ()
virtual ~ComponentInterface ()
ComponentInterface (const ComponentInterface &from)
ComponentInterface & operator= (const ComponentInterface &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ComponentInterface *other)
ComponentInterface * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ComponentInterface &from)
void MergeFrom (const ComponentInterface &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
int calls_size () const
void clear_calls ()
const ::previrt::proto::CallInfo & calls (int index) const
inline::previrt::proto::CallInfo * mutable_calls (int index)
inline::previrt::proto::CallInfo * add_calls ()
const
::google::protobuf::RepeatedPtrField
< ::previrt::proto::CallInfo > & calls () const
inline::google::protobuf::RepeatedPtrField
< ::previrt::proto::CallInfo > * mutable_calls ()
int definitions_size () const
void clear_definitions ()
const ::previrt::proto::CallInfo & definitions (int index) const
inline::previrt::proto::CallInfo * mutable_definitions (int index)
inline::previrt::proto::CallInfo * add_definitions ()
const
::google::protobuf::RepeatedPtrField
< ::previrt::proto::CallInfo > & definitions () const
inline::google::protobuf::RepeatedPtrField
< ::previrt::proto::CallInfo > * mutable_definitions ()
int globals_size () const
void clear_globals ()
const
::previrt::proto::PrevirtType & globals (int index) const
inline::previrt::proto::PrevirtType * mutable_globals (int index)
inline::previrt::proto::PrevirtType * add_globals ()
const
::google::protobuf::RepeatedPtrField
< ::previrt::proto::PrevirtType > & globals () const
inline::google::protobuf::RepeatedPtrField
< ::previrt::proto::PrevirtType > * mutable_globals ()
int references_size () const
void clear_references ()
const ::std::string & references (int index) const
inline::std::string * mutable_references (int index)
void set_references (int index, const ::std::string &value)
void set_references (int index, const char *value)
void set_references (int index, const void *value, size_t size)
inline::std::string * add_references ()
void add_references (const ::std::string &value)
void add_references (const char *value)
void add_references (const void *value, size_t size)
const
::google::protobuf::RepeatedPtrField
< ::std::string > & references () const
inline::google::protobuf::RepeatedPtrField
< ::std::string > * mutable_references ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const ComponentInterface & default_instance ()
Static Public Attributes
static const int kCallsFieldNumber = 1
static const int kDefinitionsFieldNumber = 2
static const int kGlobalsFieldNumber = 3
static const int kReferencesFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::RepeatedPtrField
< ::previrt::proto::CallInfo > calls_
::google::protobuf::RepeatedPtrField
< ::previrt::proto::CallInfo > definitions_
::google::protobuf::RepeatedPtrField
< ::previrt::proto::PrevirtType > globals_
::google::protobuf::RepeatedPtrField
< ::std::string > references_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(4+31)/32]
Static Private Attributes
static ComponentInterface * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 970 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::ComponentInterface::ComponentInterface ()
Definition at line 2933 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::ComponentInterface::~ComponentInterface () virtual
Definition at line 2952 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::ComponentInterface::ComponentInterface (const ComponentInterface & from)
Definition at line 2941 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
previrt::proto::CallInfo * previrt::proto::ComponentInterface::add_calls () inline
Definition at line 2710 of file Previrt.pb.h.
References calls_.
Referenced by MergePartialFromCodedStream().
previrt::proto::CallInfo * previrt::proto::ComponentInterface::add_definitions () inline
Definition at line 2735 of file Previrt.pb.h.
References definitions_.
Referenced by MergePartialFromCodedStream().
previrt::proto::PrevirtType * previrt::proto::ComponentInterface::add_globals () inline
Definition at line 2760 of file Previrt.pb.h.
References globals_.
Referenced by MergePartialFromCodedStream().
std::string * previrt::proto::ComponentInterface::add_references () inline
Definition at line 2795 of file Previrt.pb.h.
References references_.
Referenced by MergePartialFromCodedStream().
void previrt::proto::ComponentInterface::add_references (const ::std::string & value) inline
Definition at line 2798 of file Previrt.pb.h.
References references_.
void previrt::proto::ComponentInterface::add_references (const char * value) inline
Definition at line 2801 of file Previrt.pb.h.
References references_.
void previrt::proto::ComponentInterface::add_references (const void * value, size_t size) inline
Definition at line 2804 of file Previrt.pb.h.
References references_.
int previrt::proto::ComponentInterface::ByteSize () const
Definition at line 3141 of file Previrt.pb.cc.
References _cached_size_, calls(), calls_size(), definitions(), definitions_size(), globals(), globals_size(), references(), references_size(), and unknown_fields().
const ::previrt::proto::CallInfo & previrt::proto::ComponentInterface::calls (int index) const inline
Definition at line 2704 of file Previrt.pb.h.
References calls_.
const ::google::protobuf::RepeatedPtrField<::previrt::proto::CallInfo > & previrt::proto::ComponentInterface::calls () const inline
Definition at line 2714 of file Previrt.pb.h.
References calls_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::ComponentInterface::calls_size () const inline
Definition at line 2698 of file Previrt.pb.h.
References calls_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::ComponentInterface::Clear ()
Definition at line 2982 of file Previrt.pb.cc.
References _has_bits_, calls_, definitions_, globals_, mutable_unknown_fields(), and references_.
Referenced by CopyFrom().
void previrt::proto::ComponentInterface::clear_calls () inline
Definition at line 2701 of file Previrt.pb.h.
References calls_.
void previrt::proto::ComponentInterface::clear_definitions () inline
Definition at line 2726 of file Previrt.pb.h.
References definitions_.
void previrt::proto::ComponentInterface::clear_globals () inline
Definition at line 2751 of file Previrt.pb.h.
References globals_.
void previrt::proto::ComponentInterface::clear_references () inline
Definition at line 2776 of file Previrt.pb.h.
References references_.
void previrt::proto::ComponentInterface::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 3207 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::ComponentInterface::CopyFrom (const ComponentInterface & from)
Definition at line 3213 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const ComponentInterface & previrt::proto::ComponentInterface::default_instance () static
Definition at line 2971 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::previrt::proto::CallInfo & previrt::proto::ComponentInterface::definitions (int index) const inline
Definition at line 2729 of file Previrt.pb.h.
References definitions_.
const ::google::protobuf::RepeatedPtrField<::previrt::proto::CallInfo > & previrt::proto::ComponentInterface::definitions () const inline
Definition at line 2739 of file Previrt.pb.h.
References definitions_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::ComponentInterface::definitions_size () const inline
Definition at line 2723 of file Previrt.pb.h.
References definitions_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
const ::google::protobuf::Descriptor * previrt::proto::ComponentInterface::descriptor () static
Definition at line 2966 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ComponentInterface_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
int previrt::proto::ComponentInterface::GetCachedSize () const inline
Definition at line 1011 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::ComponentInterface::GetMetadata () const
Definition at line 3245 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ComponentInterface_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ComponentInterface_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
const ::previrt::proto::PrevirtType & previrt::proto::ComponentInterface::globals (int index) const inline
Definition at line 2754 of file Previrt.pb.h.
References globals_.
const ::google::protobuf::RepeatedPtrField<::previrt::proto::PrevirtType > & previrt::proto::ComponentInterface::globals () const inline
Definition at line 2764 of file Previrt.pb.h.
References globals_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::ComponentInterface::globals_size () const inline
Definition at line 2748 of file Previrt.pb.h.
References globals_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::ComponentInterface::InitAsDefaultInstance () private
Definition at line 2938 of file Previrt.pb.cc.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::ComponentInterface::IsInitialized () const
Definition at line 3219 of file Previrt.pb.cc.
References calls(), calls_size(), definitions(), definitions_size(), globals(), and globals_size().
void previrt::proto::ComponentInterface::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 3186 of file Previrt.pb.cc.
Referenced by ComponentInterface(), and CopyFrom().
void previrt::proto::ComponentInterface::MergeFrom (const ComponentInterface & from)
Definition at line 3198 of file Previrt.pb.cc.
References calls_, definitions_, globals_, mutable_unknown_fields(), references_, and unknown_fields().
bool previrt::proto::ComponentInterface::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 2991 of file Previrt.pb.cc.
References add_calls(), add_definitions(), add_globals(), add_references(), DO_, and mutable_unknown_fields().
previrt::proto::CallInfo * previrt::proto::ComponentInterface::mutable_calls (int index) inline
Definition at line 2707 of file Previrt.pb.h.
References calls_.
google::protobuf::RepeatedPtrField<::previrt::proto::CallInfo > * previrt::proto::ComponentInterface::mutable_calls () inline
Definition at line 2718 of file Previrt.pb.h.
References calls_.
previrt::proto::CallInfo * previrt::proto::ComponentInterface::mutable_definitions (int index) inline
Definition at line 2732 of file Previrt.pb.h.
References definitions_.
google::protobuf::RepeatedPtrField<::previrt::proto::CallInfo > * previrt::proto::ComponentInterface::mutable_definitions () inline
Definition at line 2743 of file Previrt.pb.h.
References definitions_.
previrt::proto::PrevirtType * previrt::proto::ComponentInterface::mutable_globals (int index) inline
Definition at line 2757 of file Previrt.pb.h.
References globals_.
google::protobuf::RepeatedPtrField<::previrt::proto::PrevirtType > * previrt::proto::ComponentInterface::mutable_globals () inline
Definition at line 2768 of file Previrt.pb.h.
References globals_.
std::string * previrt::proto::ComponentInterface::mutable_references (int index) inline
Definition at line 2782 of file Previrt.pb.h.
References references_.
google::protobuf::RepeatedPtrField<::std::string > * previrt::proto::ComponentInterface::mutable_references () inline
Definition at line 2812 of file Previrt.pb.h.
References references_.
inline ::google::protobuf::UnknownFieldSet* previrt::proto::ComponentInterface::mutable_unknown_fields () inline
Definition at line 986 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
ComponentInterface * previrt::proto::ComponentInterface::New () const
Definition at line 2978 of file Previrt.pb.cc.
References ComponentInterface().
ComponentInterface& previrt::proto::ComponentInterface::operator= (const ComponentInterface & from) inline
Definition at line 977 of file Previrt.pb.h.
References CopyFrom().
const ::std::string & previrt::proto::ComponentInterface::references (int index) const inline
Definition at line 2779 of file Previrt.pb.h.
References references_.
const ::google::protobuf::RepeatedPtrField<::std::string > & previrt::proto::ComponentInterface::references () const inline
Definition at line 2808 of file Previrt.pb.h.
References references_.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::ComponentInterface::references_size () const inline
Definition at line 2773 of file Previrt.pb.h.
References references_.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::ComponentInterface::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 3073 of file Previrt.pb.cc.
References calls(), calls_size(), definitions(), definitions_size(), globals(), globals_size(), references(), references_size(), and unknown_fields().
google::protobuf::uint8 * previrt::proto::ComponentInterface::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 3105 of file Previrt.pb.cc.
References calls(), calls_size(), definitions(), definitions_size(), globals(), globals_size(), references(), references_size(), and unknown_fields().
void previrt::proto::ComponentInterface::set_references (int index, const ::std::string & value) inline
Definition at line 2785 of file Previrt.pb.h.
References references_.
void previrt::proto::ComponentInterface::set_references (int index, const char * value) inline
Definition at line 2788 of file Previrt.pb.h.
References references_.
void previrt::proto::ComponentInterface::set_references (int index, const void * value, size_t size) inline
Definition at line 2791 of file Previrt.pb.h.
References references_.
void previrt::proto::ComponentInterface::SetCachedSize (int size) const private
Definition at line 2961 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::ComponentInterface::SharedCtor () private
Definition at line 2947 of file Previrt.pb.cc.
References _cached_size_, and _has_bits_.
Referenced by ComponentInterface().
void previrt::proto::ComponentInterface::SharedDtor () private
Definition at line 2956 of file Previrt.pb.cc.
References default_instance_.
Referenced by ~ComponentInterface().
void previrt::proto::ComponentInterface::Swap (ComponentInterface * other)
Definition at line 3233 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, calls_, definitions_, globals_, and references_.
const ::google::protobuf::UnknownFieldSet& previrt::proto::ComponentInterface::unknown_fields () const inline
Definition at line 982 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::ComponentInterface::_cached_size_ mutable private
Definition at line 1086 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::ComponentInterface::_has_bits_[(4+31)/32] private
Definition at line 1087 of file Previrt.pb.h.
Referenced by Clear(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::ComponentInterface::_unknown_fields_ private
Definition at line 1079 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
::google::protobuf::RepeatedPtrField< ::previrt::proto::CallInfo > previrt::proto::ComponentInterface::calls_ private
Definition at line 1081 of file Previrt.pb.h.
Referenced by add_calls(), calls(), calls_size(), Clear(), clear_calls(), MergeFrom(), mutable_calls(), and Swap().
ComponentInterface * previrt::proto::ComponentInterface::default_instance_ = NULL static private
Definition at line 1094 of file Previrt.pb.h.
Referenced by default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
::google::protobuf::RepeatedPtrField< ::previrt::proto::CallInfo > previrt::proto::ComponentInterface::definitions_ private
Definition at line 1082 of file Previrt.pb.h.
Referenced by add_definitions(), Clear(), clear_definitions(), definitions(), definitions_size(), MergeFrom(), mutable_definitions(), and Swap().
::google::protobuf::RepeatedPtrField< ::previrt::proto::PrevirtType > previrt::proto::ComponentInterface::globals_ private
Definition at line 1083 of file Previrt.pb.h.
Referenced by add_globals(), Clear(), clear_globals(), globals(), globals_size(), MergeFrom(), mutable_globals(), and Swap().
const int previrt::proto::ComponentInterface::kCallsFieldNumber = 1 static
Definition at line 1027 of file Previrt.pb.h.
const int previrt::proto::ComponentInterface::kDefinitionsFieldNumber = 2 static
Definition at line 1039 of file Previrt.pb.h.
const int previrt::proto::ComponentInterface::kGlobalsFieldNumber = 3 static
Definition at line 1051 of file Previrt.pb.h.
const int previrt::proto::ComponentInterface::kReferencesFieldNumber = 4 static
Definition at line 1063 of file Previrt.pb.h.
::google::protobuf::RepeatedPtrField< ::std::string> previrt::proto::ComponentInterface::references_ private
Definition at line 1084 of file Previrt.pb.h.
Referenced by add_references(), Clear(), clear_references(), MergeFrom(), mutable_references(), references(), references_size(), set_references(), and Swap().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc