Occam - Application Specialization: previrt::proto::ActionTree_Forward Class Reference
previrt::proto::ActionTree_Forward Class Reference
#include <Previrt.pb.h>
Public Member Functions
ActionTree_Forward ()
virtual ~ActionTree_Forward ()
ActionTree_Forward (const ActionTree_Forward &from)
ActionTree_Forward & operator= (const ActionTree_Forward &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ActionTree_Forward *other)
ActionTree_Forward * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ActionTree_Forward &from)
void MergeFrom (const ActionTree_Forward &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const ActionTree_Forward & default_instance ()
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [1]
Static Private Attributes
static ActionTree_Forward * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 1301 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::ActionTree_Forward::ActionTree_Forward ()
Definition at line 3818 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::ActionTree_Forward::~ActionTree_Forward () virtual
Definition at line 3837 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::ActionTree_Forward::ActionTree_Forward (const ActionTree_Forward & from)
Definition at line 3826 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
int previrt::proto::ActionTree_Forward::ByteSize () const
Definition at line 3905 of file Previrt.pb.cc.
References _cached_size_, and unknown_fields().
void previrt::proto::ActionTree_Forward::Clear ()
Definition at line 3867 of file Previrt.pb.cc.
References _has_bits_, and mutable_unknown_fields().
Referenced by CopyFrom().
void previrt::proto::ActionTree_Forward::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 3936 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::ActionTree_Forward::CopyFrom (const ActionTree_Forward & from)
Definition at line 3942 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const ActionTree_Forward & previrt::proto::ActionTree_Forward::default_instance () static
Definition at line 3856 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::ActionTree::InitAsDefaultInstance(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::ActionTree_Forward::descriptor () static
Definition at line 3851 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Forward_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
int previrt::proto::ActionTree_Forward::GetCachedSize () const inline
Definition at line 1342 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::ActionTree_Forward::GetMetadata () const
Definition at line 3960 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Forward_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Forward_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
void previrt::proto::ActionTree_Forward::InitAsDefaultInstance () private
Definition at line 3823 of file Previrt.pb.cc.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::ActionTree_Forward::IsInitialized () const
Definition at line 3948 of file Previrt.pb.cc.
void previrt::proto::ActionTree_Forward::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 3919 of file Previrt.pb.cc.
Referenced by ActionTree_Forward(), and CopyFrom().
void previrt::proto::ActionTree_Forward::MergeFrom (const ActionTree_Forward & from)
Definition at line 3931 of file Previrt.pb.cc.
References mutable_unknown_fields(), and unknown_fields().
bool previrt::proto::ActionTree_Forward::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 3872 of file Previrt.pb.cc.
References DO_, and mutable_unknown_fields().
inline ::google::protobuf::UnknownFieldSet* previrt::proto::ActionTree_Forward::mutable_unknown_fields () inline
Definition at line 1317 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
ActionTree_Forward * previrt::proto::ActionTree_Forward::New () const
Definition at line 3863 of file Previrt.pb.cc.
References ActionTree_Forward().
ActionTree_Forward& previrt::proto::ActionTree_Forward::operator= (const ActionTree_Forward & from) inline
Definition at line 1308 of file Previrt.pb.h.
References CopyFrom().
void previrt::proto::ActionTree_Forward::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 3888 of file Previrt.pb.cc.
References unknown_fields().
google::protobuf::uint8 * previrt::proto::ActionTree_Forward::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 3896 of file Previrt.pb.cc.
References unknown_fields().
void previrt::proto::ActionTree_Forward::SetCachedSize (int size) const private
Definition at line 3846 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::ActionTree_Forward::SharedCtor () private
Definition at line 3832 of file Previrt.pb.cc.
References _cached_size_, and _has_bits_.
Referenced by ActionTree_Forward().
void previrt::proto::ActionTree_Forward::SharedDtor () private
Definition at line 3841 of file Previrt.pb.cc.
References default_instance_.
Referenced by ~ActionTree_Forward().
void previrt::proto::ActionTree_Forward::Swap (ActionTree_Forward * other)
Definition at line 3953 of file Previrt.pb.cc.
References _cached_size_, and _unknown_fields_.
const ::google::protobuf::UnknownFieldSet& previrt::proto::ActionTree_Forward::unknown_fields () const inline
Definition at line 1313 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::ActionTree_Forward::_cached_size_ mutable private
Definition at line 1361 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::ActionTree_Forward::_has_bits_[1] private
Definition at line 1362 of file Previrt.pb.h.
Referenced by Clear(), and SharedCtor().
::google::protobuf::UnknownFieldSet previrt::proto::ActionTree_Forward::_unknown_fields_ private
Definition at line 1358 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
ActionTree_Forward * previrt::proto::ActionTree_Forward::default_instance_ = NULL static private
Definition at line 1369 of file Previrt.pb.h.
Referenced by default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc