Occam - Application Specialization: previrt::PrevirtType Class Reference
previrt::PrevirtType Class Reference
#include <PrevirtTypes.h>
Public Member Functions
PrevirtType ()
Constructor. Sets the default type of the previrt::proto::PrevirtType buffer as U (unknown)
PrevirtType (const proto::PrevirtType &)
Overloaded constructor.
PrevirtType & operator= (const PrevirtType &)
Assignment Operator overloaded.
bool operator!= (const PrevirtType &) const
Not equal comparison operator overloaded.
bool operator== (const PrevirtType &) const
Equality Operator overloaded.
int refines (const llvm::Value *const) const
llvm::Value * concretize (llvm::Module &, llvm::Type *) const
bool isConcrete () const
bool isUnknown () const
std::string to_string () const
llvm::Function * getEqualityFunction (llvm::Module *) const
Static Public Member Functions
static PrevirtType abstract (const llvm::Value *const)
static PrevirtType unknown ()
Private Types
typedef std::map< llvm::Type
*, llvm::Function * > EqCache
Private Attributes
proto::PrevirtType buffer
A Google protocol buffer class.
Static Private Attributes
static EqCache cacheEq
A map of Type * against Function *.
Detailed Description
The PrevirtType class is a wrapper above the previrt::proto::PrevirtType buffer. The format of the previrt::proto::PrevirtType is defined in the file Previrt.proto line 78. The class can contain values of the type int, string, float, vector or a global value. The PrevirtType class extends the functionality of the previrt::proto::PrevirtType class, by adding a number of utility functions.
Definition at line 70 of file PrevirtTypes.h.
Member Typedef Documentation
typedef std::map<llvm::Type*, llvm::Function*> previrt::PrevirtType::EqCache private
Definition at line 75 of file PrevirtTypes.h.
Constructor & Destructor Documentation
previrt::PrevirtType::PrevirtType ()
Constructor. Sets the default type of the previrt::proto::PrevirtType buffer as U (unknown)
Definition at line 69 of file PrevirtTypes.cpp.
References previrt::proto::U.
previrt::PrevirtType::PrevirtType (const proto::PrevirtType & pt)
Overloaded constructor.
Definition at line 75 of file PrevirtTypes.cpp.
Member Function Documentation
PrevirtType previrt::PrevirtType::abstract (const llvm::Value * const val) static
Given the Value*, the function creates and returns a PrevirtType object. The appropriate type of the Value is determined (int, float, vector,global) and assigns the type to the PrevirtType object. The value is copied to the buffer of the PrevirtType object.
Definition at line 148 of file PrevirtTypes.cpp.
References previrt::proto::Bogus, buffer, previrt::proto::F, previrt::proto::G, previrt::proto::I, previrt::proto::IEEEdouble, previrt::proto::IEEEhalf, previrt::proto::IEEEquad, previrt::proto::IEEEsingle, previrt::proto::PrevirtType::mutable_float_(), previrt::proto::PrevirtType::mutable_global(), previrt::proto::PrevirtType::mutable_int_(), previrt::proto::PrevirtType::mutable_str(), previrt::proto::N, previrt::proto::PPCDoubleDouble, previrt::proto::S, previrt::proto::PrevirtType::set_type(), previrt::StringFromValue(), previrt::proto::U, and previrt::proto::x87DoubleExtended.
Referenced by previrt::SpecializationPolicy::isConstantSpecializable().
llvm::Value * previrt::PrevirtType::concretize (llvm::Module & , llvm::Type *) const
Return a global variable containing the value of the PrevirtType
Definition at line 434 of file PrevirtTypes.cpp.
References previrt::charStarFromStringConstant(), previrt::proto::G, previrt::proto::I, previrt::materializeStringLiteral(), previrt::proto::N, and previrt::proto::S.
Function * previrt::PrevirtType::getEqualityFunction (llvm::Module *) const
Build an equality function to compare two values. The Type of the buffer, determines whether a string or int equality function is required. The cacheEq type keeps a map of Function * against Type *. If an equality function already exists in the cacheEq map, it is simply returned, otherwise a new function to test the equality of two values taken as input, is created and added to the cacheEq map for future reference.
Definition at line 643 of file PrevirtTypes.cpp.
References previrt::buildIntEquality(), previrt::buildStringEquality(), previrt::proto::I, previrt::proto::N, and previrt::proto::S.
Referenced by previrt::compileAction().
bool previrt::PrevirtType::isConcrete () const
Return true if the type of the buffer is of type proto::G , proto::S, proto::I or proto::N . If the buffer type is proto::F, proto::V or proto::U the function returns false.
Definition at line 500 of file PrevirtTypes.cpp.
References previrt::proto::G, previrt::proto::I, previrt::proto::N, and previrt::proto::S.
Referenced by previrt::SpecializationPolicy::isConstantSpecializable().
bool previrt::PrevirtType::isUnknown () const
If the PrevirtType class data member buffer did not having any concrete type (int,string,vector,float,global,NULL) the function returns true
Definition at line 509 of file PrevirtTypes.cpp.
References previrt::proto::U.
bool previrt::PrevirtType::operator!= (const PrevirtType & other) const
Not equal comparison operator overloaded.
Definition at line 91 of file PrevirtTypes.cpp.
PrevirtType & previrt::PrevirtType::operator= (const PrevirtType & from)
Assignment Operator overloaded.
Definition at line 82 of file PrevirtTypes.cpp.
References buffer.
bool previrt::PrevirtType::operator== (const PrevirtType & other) const
Equality Operator overloaded.
Definition at line 98 of file PrevirtTypes.cpp.
References previrt::proto::PrevirtType_Int::bits(), buffer, previrt::proto::PrevirtType_Str::data(), previrt::proto::F, previrt::proto::G, previrt::proto::PrevirtType::global(), previrt::proto::I, previrt::proto::PrevirtType::int_(), previrt::proto::N, previrt::proto::PrevirtType_Global::name(), previrt::proto::S, previrt::proto::PrevirtType::str(), previrt::proto::PrevirtType::type(), previrt::proto::U, and previrt::proto::PrevirtType_Int::value().
int previrt::PrevirtType::refines (const llvm::Value * const val) const
Definition at line 350 of file PrevirtTypes.cpp.
References previrt::proto::Bogus, CASE, EXACT_MATCH, previrt::proto::F, previrt::proto::G, previrt::proto::I, previrt::proto::IEEEdouble, previrt::proto::IEEEhalf, previrt::proto::IEEEquad, previrt::proto::IEEEsingle, LOOSE_MATCH, previrt::proto::N, NO_MATCH, previrt::proto::PPCDoubleDouble, previrt::proto::S, previrt::StringFromValue(), previrt::proto::U, and previrt::proto::x87DoubleExtended.
std::string previrt::PrevirtType::to_string () const
The PrevirtType::to_string function returns a string; the name of a global variable. If the buffer type was proto::G (global) and the value of integers and strings enclosed in a string, if the type of buffer is proto::I or proto::S
Definition at line 518 of file PrevirtTypes.cpp.
References previrt::proto::G, previrt::proto::I, previrt::proto::N, and previrt::proto::S.
Referenced by previrt::specializeFunction().
PrevirtType previrt::PrevirtType::unknown () static
Return an object of PrevirtType with the default type of the /e buffer(class data member) set as U (unknown)
Definition at line 136 of file PrevirtTypes.cpp.
References buffer, previrt::proto::PrevirtType::set_type(), and previrt::proto::U.
Member Data Documentation
proto::PrevirtType previrt::PrevirtType::buffer private
A Google protocol buffer class.
Definition at line 74 of file PrevirtTypes.h.
Referenced by abstract(), operator=(), operator==(), and unknown().
PrevirtType::EqCache previrt::PrevirtType::cacheEq static private
A map of Type * against Function *.
Definition at line 77 of file PrevirtTypes.h.
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/PrevirtTypes.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/PrevirtTypes.cpp