Occam - Application Specialization: previrt::GatherInterface2Pass Class Reference
previrt::GatherInterface2Pass Class Reference
Public Member Functions
GatherInterface2Pass ()
Constructor calls the ModulePass constructor to initialize data members in the base class.
virtual ~GatherInterface2Pass ()
Default constructor.
virtual void getAnalysisUsage (AnalysisUsage &Info) const
virtual bool runOnModule (Module &M)
Public Attributes
ComponentInterface interface
interface is an object of type previrt::proto::ComponentInterface, The object contains an array of previrt::proto::CallInfo and a set of references, that gathers the information related to a specific call-sites and external references in the module.
Static Public Attributes
static char ID
Detailed Description
GatherInterface2Pass implements one phase of a three phase Inter-Module specialization process. The steps of the process are:
1) Gathering external references across all modules, so that the specific usages of functions outside the modules where they are defined can be captured. This collection is accomplished by the 'Pinterface2' pass implemented, in the previrt::GatherInterface2Pass class.
2) Given the specific usages, serialized into a file as a previrt::proto::ComponentInterfaceTransform object, the SpecializeComponentPass creates specialized versions of function in the modules where they have been defined.
3) Once the specialized functions have been created, the corresponding calls to the specialized versions, need to be rewritten, taking a fewer number of arguments. The call rewriting process is accomplished by the 'Prewrite' Pass implemented by the previrt::RewriteComponentPass class.
GatherInterface2Pass is registered as a Pass ,with the PassManager internal database by the name 'Pinterface2'. The Pass takes three arguments. The flag 'Pinterface2-output' followed by a file name specifies the output file for the interface description. The flag 'Pinterface2-function' is followed by a function name, specifying the externally called function in the module. The 'Pinterface2-entry' flag is followed by a file containing the functions called (function names). All the arguments are optional.
Definition at line 438 of file GatherInterface2.cpp.
Constructor & Destructor Documentation
previrt::GatherInterface2Pass::GatherInterface2Pass () inline
Constructor calls the ModulePass constructor to initialize data members in the base class.
Definition at line 448 of file GatherInterface2.cpp.
virtual previrt::GatherInterface2Pass::~GatherInterface2Pass () inline virtual
Default constructor.
Definition at line 455 of file GatherInterface2.cpp.
Member Function Documentation
virtual void previrt::GatherInterface2Pass::getAnalysisUsage (AnalysisUsage & Info) const inline virtual
Returns the call graph of the Module
Definition at line 462 of file GatherInterface2.cpp.
virtual bool previrt::GatherInterface2Pass::runOnModule (Module & M) inline virtual
The GatherInterface2Pass:runOnModule gathers the external references and external function calls. The operation is completed in the following steps:
1) Extract the call graph of the Module.
2) Traverse through the set of global variables defined in the module and add all with external linkage to the list of references and calls in the interface object
3) If the entry functions are input to the Pass in a file. The functions are parsed from the file.
4) The set of entry functions, helps us to only traverse the relevant sections of the call graph.
5) All the call-sites found by traversing the call graph that are external function calls are logged into the interface object along with the specific set of arguments (required in the next phases, SpecializeComponentPass and RewriteComponentPass)
6) If an output file name is specified to the Pass, the interface object, is serialized to the file.
Note: The serialized file will be input to the SpecializeComponentPass (defined in the file SpecializeComponent.cpp)
Definition at line 490 of file GatherInterface2.cpp.
References previrt::ComponentInterface::begin(), previrt::ComponentInterface::end(), previrt::GatherInterfaceEntry(), previrt::GatherInterfaceMain(), previrt::GatherInterfaceOutput(), previrt::getGlobal(), previrt::isInternal(), and previrt::ComponentInterface::readFromFile().
Member Data Documentation
char previrt::GatherInterface2Pass::ID static
Definition at line 444 of file GatherInterface2.cpp.
ComponentInterface previrt::GatherInterface2Pass::interface
interface is an object of type previrt::proto::ComponentInterface, The object contains an array of previrt::proto::CallInfo and a set of references, that gathers the information related to a specific call-sites and external references in the module.
Definition at line 443 of file GatherInterface2.cpp.
The documentation for this class was generated from the following file:
C:/Users/Hashim/Dropbox/Occam 2.0/src/GatherInterface2.cpp