Occam - Application Specialization: previrt::ComponentInterfaceTransform Class Reference
previrt::ComponentInterfaceTransform Class Reference
#include <PrevirtualizeInterfaces.h>
Public Types
typedef std::map< const
CallInfo *const , const
CallRewrite > CMap
typedef std::map
< FunctionHandle, CMap > FMap
Public Member Functions
ComponentInterfaceTransform ()
Default constructor. Initializes the interface to NULL and the ownsIface class data member to true.
ComponentInterfaceTransform (ComponentInterface *)
virtual ~ComponentInterfaceTransform ()
void rewrite (FunctionHandle, const CallInfo *const , FunctionHandle, const std::vector< unsigned > &)
void rewrite (FunctionHandle, const CallInfo *const , const CallRewrite &)
void dump () const
Debugging information, for previrt::ComponentInterfaceTransform.
const ComponentInterface & getInterface () const
unsigned rewriteCount () const
const CallRewrite * lookupRewrite (FunctionHandle, llvm::User::op_iterator, llvm::User::op_iterator) const
const CallRewrite * lookupRewrite (FunctionHandle, const CallInfo *const) const
bool readInterfaceFromFile (const std::string &)
bool readTransformFromFile (const std::string &)
friend void::previrt::codeInto (const proto::ComponentInterface &, ComponentInterfaceTransform &)
Public Attributes
ComponentInterface * interface
FMap rewrites
bool ownsIface
Detailed Description
The ComponentInterfaceTransform class essentially contains two objects. The interface object (data class member) of type previrt::ComponentInterface, contains the set of external calls and references. The external calls and references are gathered by the 'Pinterface2' Pass, implemented in the class previrt::GatherInterface2Pass. The class member rewrites, is a map of function names against CallInfo and CallRewrite, that is required by the 'Prewrite' Pass implemented in the class previrt::RewriteComponentPass.
Definition at line 185 of file PrevirtualizeInterfaces.h.
Member Typedef Documentation
typedef std::map<const CallInfo* const , const CallRewrite> previrt::ComponentInterfaceTransform::CMap
Definition at line 188 of file PrevirtualizeInterfaces.h.
typedef std::map<FunctionHandle, CMap> previrt::ComponentInterfaceTransform::FMap
Definition at line 189 of file PrevirtualizeInterfaces.h.
Constructor & Destructor Documentation
previrt::ComponentInterfaceTransform::ComponentInterfaceTransform ()
Default constructor. Initializes the interface to NULL and the ownsIface class data member to true.
Definition at line 537 of file PrevirtualizeInterfaces.cpp.
previrt::ComponentInterfaceTransform::ComponentInterfaceTransform (ComponentInterface * ci)
ComponentInterfaceTransform overloaded constructor, Takes as an argument as previrt::ComponentInterface object ci and initializes its class data member interface
Definition at line 544 of file PrevirtualizeInterfaces.cpp.
previrt::ComponentInterfaceTransform::~ComponentInterfaceTransform () virtual
ComponentInterfaceTransform destructor, If the class data member interface is initialized, the memory allocated for it, is deallocated
Definition at line 551 of file PrevirtualizeInterfaces.cpp.
References interface, and ownsIface.
Member Function Documentation
void previrt::ComponentInterfaceTransform::dump () const
Debugging information, for previrt::ComponentInterfaceTransform.
Definition at line 598 of file PrevirtualizeInterfaces.cpp.
References rewrites.
const ComponentInterface & previrt::ComponentInterfaceTransform::getInterface () const
Return the previrt::ComponentInterface from the previrt::ComponentInterfaceTransform
Definition at line 611 of file PrevirtualizeInterfaces.cpp.
References interface, and ownsIface.
Referenced by previrt::SpecializeComponent().
CallRewrite const * previrt::ComponentInterfaceTransform::lookupRewrite (FunctionHandle name, llvm::User::op_iterator op_begin, llvm::User::op_iterator op_end) const
Given the functionHandle to the original function and a set of specific arguments, a corresponding CallRewrite is returned if one exists in the previrt::ComponentInterfaceTransform object. If a CallRewrite does not exist for the function with the specific set of arguments, the function returns NULL
Parameters
name The name of the function for which a specialized version might have been created and thus looking for an existing rewrite
op_begin start of the argument iterator
ob_end end of the argument iterator
Definition at line 643 of file PrevirtualizeInterfaces.cpp.
References previrt::ComponentInterface::call_begin(), previrt::ComponentInterface::call_end(), previrt::ComponentInterface::calls, and interface.
Referenced by previrt::TransformComponentWithUse().
const CallRewrite * previrt::ComponentInterfaceTransform::lookupRewrite (FunctionHandle name, const CallInfo * const key) const
Given the function name, and the CallInfo (set of arguments), return a CallRewrite object if a corresponding CallRewrite object exists.
Definition at line 674 of file PrevirtualizeInterfaces.cpp.
References interface, and rewrites.
bool previrt::ComponentInterfaceTransform::readInterfaceFromFile (const std::string & filename)
Given a file name containing a serialized previrt::proto::ComponentInterface object, read the interface into a previrt::ComponentInterfaceTransform object.
Definition at line 694 of file PrevirtualizeInterfaces.cpp.
bool previrt::ComponentInterfaceTransform::readTransformFromFile (const std::string & filename)
Given a file name containing a serialized previrt::proto::ComponentInterfaceTransform object, read the interface into a previrt::ComponentInterfaceTransform object.
Definition at line 718 of file PrevirtualizeInterfaces.cpp.
void previrt::ComponentInterfaceTransform::rewrite (FunctionHandle hndl, const CallInfo * const from, FunctionHandle to, const std::vector< unsigned > & to_args)
Adds a rewrite to the previrt::ComponentInterfaceTransform object, the rewrites are used to rewrite calls made to specialized functions. The rewriting process takes place in the 'Prewrite' Pass implemented in the class previrt::RewriteComponentPass.
Parameters
hndl A Function handle to the original function
from The CallInfo of the original function (the set of arguments)
to Function handle to the specialized function
to_args The new set of arguments (reduced) to the specialized function
Definition at line 568 of file PrevirtualizeInterfaces.cpp.
Referenced by previrt::SpecializeComponent().
void previrt::ComponentInterfaceTransform::rewrite (FunctionHandle hndl, const CallInfo * const from, const CallRewrite & to)
Adds a rewrite to the previrt::ComponentInterfaceTransform object, the rewrites are used to rewrite calls made to specialized functions. The rewriting process takes place in the 'Prewrite' Pass implemented in the class RewriteComponentPass.
Parameters
hndl A Function handle to the original function
from The CallInfo of the original function (the set of arguments)
to The CallRewrite object to replace all calls to the specific usage of the function as defined in the CallRewrite, to the newly assigned function name and the reduced set of arguments.
Definition at line 584 of file PrevirtualizeInterfaces.cpp.
References rewrites.
unsigned previrt::ComponentInterfaceTransform::rewriteCount () const
Return the number of arguments that have to be rewritten, as specified by the previrt::ComponentInterfaceTransform
Definition at line 624 of file PrevirtualizeInterfaces.cpp.
References rewrites.
previrt::ComponentInterfaceTransform::void::previrt::codeInto (const proto::ComponentInterface & , ComponentInterfaceTransform &)
Member Data Documentation
ComponentInterface* previrt::ComponentInterfaceTransform::interface
Definition at line 192 of file PrevirtualizeInterfaces.h.
Referenced by getInterface(), lookupRewrite(), and ~ComponentInterfaceTransform().
bool previrt::ComponentInterfaceTransform::ownsIface
Definition at line 194 of file PrevirtualizeInterfaces.h.
Referenced by getInterface(), and ~ComponentInterfaceTransform().
FMap previrt::ComponentInterfaceTransform::rewrites
Definition at line 193 of file PrevirtualizeInterfaces.h.
Referenced by dump(), lookupRewrite(), rewrite(), rewriteCount(), and previrt::TransformComponentWithUse().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/PrevirtualizeInterfaces.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/PrevirtualizeInterfaces.cpp