Occam - Application Specialization: previrt::proto::CallRewrite Class Reference
previrt::proto::CallRewrite Class Reference
#include <Previrt.pb.h>
Public Member Functions
CallRewrite ()
virtual ~CallRewrite ()
CallRewrite (const CallRewrite &from)
CallRewrite & operator= (const CallRewrite &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (CallRewrite *other)
CallRewrite * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const CallRewrite &from)
void MergeFrom (const CallRewrite &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_call () const
void clear_call ()
const ::previrt::proto::CallInfo & call () const
inline::previrt::proto::CallInfo * mutable_call ()
inline::previrt::proto::CallInfo * release_call ()
void set_allocated_call (::previrt::proto::CallInfo *call)
bool has_new_function () const
void clear_new_function ()
const ::std::string & new_function () const
void set_new_function (const ::std::string &value)
void set_new_function (const char *value)
void set_new_function (const void *value, size_t size)
inline::std::string * mutable_new_function ()
inline::std::string * release_new_function ()
void set_allocated_new_function (::std::string *new_function)
int args_size () const
void clear_args ()
inline::google::protobuf::int32 args (int index) const
void set_args (int index,::google::protobuf::int32 value)
void add_args (::google::protobuf::int32 value)
const
::google::protobuf::RepeatedField
< ::google::protobuf::int32 > & args () const
inline::google::protobuf::RepeatedField
< ::google::protobuf::int32 > * mutable_args ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const CallRewrite & default_instance ()
Static Public Attributes
static const int kCallFieldNumber = 1
static const int kNewFunctionFieldNumber = 2
static const int kArgsFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_call ()
void clear_has_call ()
void set_has_new_function ()
void clear_has_new_function ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::previrt::proto::CallInfo * call_
::std::string * new_function_
::google::protobuf::RepeatedField
< ::google::protobuf::int32 > args_
int _args_cached_byte_size_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(3+31)/32]
Static Private Attributes
static CallRewrite * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 857 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::CallRewrite::CallRewrite ()
Definition at line 2601 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::CallRewrite::~CallRewrite () virtual
Definition at line 2623 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::CallRewrite::CallRewrite (const CallRewrite & from)
Definition at line 2610 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
void previrt::proto::CallRewrite::add_args (::google::protobuf::int32 value) inline
Definition at line 2681 of file Previrt.pb.h.
References args_.
google::protobuf::int32 previrt::proto::CallRewrite::args (int index) const inline
Definition at line 2675 of file Previrt.pb.h.
References args_.
const ::google::protobuf::RepeatedField<::google::protobuf::int32 > & previrt::proto::CallRewrite::args () const inline
Definition at line 2685 of file Previrt.pb.h.
References args_.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::CallRewrite::args_size () const inline
Definition at line 2669 of file Previrt.pb.h.
References args_.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::CallRewrite::ByteSize () const
Definition at line 2810 of file Previrt.pb.cc.
References _args_cached_byte_size_, _cached_size_, _has_bits_, args(), args_size(), call(), has_call(), has_new_function(), new_function(), and unknown_fields().
const ::previrt::proto::CallInfo & previrt::proto::CallRewrite::call () const inline
Definition at line 2574 of file Previrt.pb.h.
References call_, and default_instance_.
Referenced by ByteSize(), previrt::codeInto< proto::ComponentInterfaceTransform, ComponentInterfaceTransform >(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_call().
void previrt::proto::CallRewrite::Clear ()
Definition at line 2657 of file Previrt.pb.cc.
References _has_bits_, args_, call_, has_call(), has_new_function(), mutable_unknown_fields(), and new_function_.
Referenced by CopyFrom().
void previrt::proto::CallRewrite::clear_args () inline
Definition at line 2672 of file Previrt.pb.h.
References args_.
void previrt::proto::CallRewrite::clear_call () inline
Definition at line 2570 of file Previrt.pb.h.
References call_, and clear_has_call().
void previrt::proto::CallRewrite::clear_has_call () inline private
Definition at line 2567 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_call(), release_call(), and set_allocated_call().
void previrt::proto::CallRewrite::clear_has_new_function () inline private
Definition at line 2605 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_new_function(), release_new_function(), and set_allocated_new_function().
void previrt::proto::CallRewrite::clear_new_function () inline
Definition at line 2608 of file Previrt.pb.h.
References clear_has_new_function(), and new_function_.
void previrt::proto::CallRewrite::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 2883 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::CallRewrite::CopyFrom (const CallRewrite & from)
Definition at line 2889 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const CallRewrite & previrt::proto::CallRewrite::default_instance () static
Definition at line 2646 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::CallRewrite::descriptor () static
Definition at line 2641 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::CallRewrite_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
int previrt::proto::CallRewrite::GetCachedSize () const inline
Definition at line 898 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::CallRewrite::GetMetadata () const
Definition at line 2915 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::CallRewrite_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::CallRewrite_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
bool previrt::proto::CallRewrite::has_call () const inline
Definition at line 2561 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::CallRewrite::has_new_function () const inline
Definition at line 2599 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::CallRewrite::InitAsDefaultInstance () private
Definition at line 2606 of file Previrt.pb.cc.
References call_, and previrt::proto::CallInfo::default_instance().
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::CallRewrite::IsInitialized () const
Definition at line 2895 of file Previrt.pb.cc.
References _has_bits_, call(), and has_call().
void previrt::proto::CallRewrite::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 2857 of file Previrt.pb.cc.
Referenced by CallRewrite(), and CopyFrom().
void previrt::proto::CallRewrite::MergeFrom (const CallRewrite & from)
Definition at line 2869 of file Previrt.pb.cc.
References _has_bits_, args_, call(), has_call(), has_new_function(), mutable_call(), mutable_unknown_fields(), new_function(), set_new_function(), and unknown_fields().
bool previrt::proto::CallRewrite::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 2673 of file Previrt.pb.cc.
References DO_, mutable_args(), mutable_call(), mutable_new_function(), and mutable_unknown_fields().
google::protobuf::RepeatedField<::google::protobuf::int32 > * previrt::proto::CallRewrite::mutable_args () inline
Definition at line 2689 of file Previrt.pb.h.
References args_.
Referenced by MergePartialFromCodedStream().
previrt::proto::CallInfo * previrt::proto::CallRewrite::mutable_call () inline
Definition at line 2577 of file Previrt.pb.h.
References call_, and set_has_call().
Referenced by previrt::codeInto< ComponentInterfaceTransform, proto::ComponentInterfaceTransform >(), MergeFrom(), and MergePartialFromCodedStream().
std::string * previrt::proto::CallRewrite::mutable_new_function () inline
Definition at line 2638 of file Previrt.pb.h.
References new_function_, and set_has_new_function().
Referenced by MergePartialFromCodedStream().
inline ::google::protobuf::UnknownFieldSet* previrt::proto::CallRewrite::mutable_unknown_fields () inline
Definition at line 873 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
CallRewrite * previrt::proto::CallRewrite::New () const
Definition at line 2653 of file Previrt.pb.cc.
References CallRewrite().
const ::std::string & previrt::proto::CallRewrite::new_function () const inline
Definition at line 2614 of file Previrt.pb.h.
References new_function_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_new_function().
CallRewrite& previrt::proto::CallRewrite::operator= (const CallRewrite & from) inline
Definition at line 864 of file Previrt.pb.h.
References CopyFrom().
previrt::proto::CallInfo * previrt::proto::CallRewrite::release_call () inline
Definition at line 2582 of file Previrt.pb.h.
References call_, and clear_has_call().
std::string * previrt::proto::CallRewrite::release_new_function () inline
Definition at line 2645 of file Previrt.pb.h.
References clear_has_new_function(), and new_function_.
void previrt::proto::CallRewrite::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 2743 of file Previrt.pb.cc.
References _args_cached_byte_size_, args(), args_size(), call(), has_call(), has_new_function(), new_function(), and unknown_fields().
google::protobuf::uint8 * previrt::proto::CallRewrite::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 2773 of file Previrt.pb.cc.
References _args_cached_byte_size_, args(), args_size(), call(), has_call(), has_new_function(), new_function(), and unknown_fields().
void previrt::proto::CallRewrite::set_allocated_call (::previrt::proto::CallInfo * call) inline
Definition at line 2588 of file Previrt.pb.h.
References call(), call_, clear_has_call(), and set_has_call().
void previrt::proto::CallRewrite::set_allocated_new_function (::std::string * new_function) inline
Definition at line 2655 of file Previrt.pb.h.
References clear_has_new_function(), new_function(), new_function_, and set_has_new_function().
void previrt::proto::CallRewrite::set_args (int index, ::google::protobuf::int32 value) inline
Definition at line 2678 of file Previrt.pb.h.
References args_.
void previrt::proto::CallRewrite::set_has_call () inline private
Definition at line 2564 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_call(), and set_allocated_call().
void previrt::proto::CallRewrite::set_has_new_function () inline private
Definition at line 2602 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_new_function(), set_allocated_new_function(), and set_new_function().
void previrt::proto::CallRewrite::set_new_function (const ::std::string & value) inline
Definition at line 2617 of file Previrt.pb.h.
References new_function_, and set_has_new_function().
Referenced by MergeFrom().
void previrt::proto::CallRewrite::set_new_function (const char * value) inline
Definition at line 2624 of file Previrt.pb.h.
References new_function_, and set_has_new_function().
void previrt::proto::CallRewrite::set_new_function (const void * value, size_t size) inline
Definition at line 2631 of file Previrt.pb.h.
References new_function_, and set_has_new_function().
void previrt::proto::CallRewrite::SetCachedSize (int size) const private
Definition at line 2636 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::CallRewrite::SharedCtor () private
Definition at line 2616 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, call_, and new_function_.
Referenced by CallRewrite().
void previrt::proto::CallRewrite::SharedDtor () private
Definition at line 2627 of file Previrt.pb.cc.
References call_, default_instance_, and new_function_.
Referenced by ~CallRewrite().
void previrt::proto::CallRewrite::Swap (CallRewrite * other)
Definition at line 2904 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, args_, call_, and new_function_.
const ::google::protobuf::UnknownFieldSet& previrt::proto::CallRewrite::unknown_fields () const inline
Definition at line 869 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::CallRewrite::_args_cached_byte_size_ mutable private
Definition at line 956 of file Previrt.pb.h.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::CallRewrite::_cached_size_ mutable private
Definition at line 958 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::CallRewrite::_has_bits_[(3+31)/32] private
Definition at line 959 of file Previrt.pb.h.
Referenced by ByteSize(), Clear(), clear_has_call(), clear_has_new_function(), has_call(), has_new_function(), IsInitialized(), MergeFrom(), set_has_call(), set_has_new_function(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::CallRewrite::_unknown_fields_ private
Definition at line 951 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
::google::protobuf::RepeatedField< ::google::protobuf::int32 > previrt::proto::CallRewrite::args_ private
Definition at line 955 of file Previrt.pb.h.
Referenced by add_args(), args(), args_size(), Clear(), clear_args(), MergeFrom(), mutable_args(), set_args(), and Swap().
::previrt::proto::CallInfo* previrt::proto::CallRewrite::call_ private
Definition at line 953 of file Previrt.pb.h.
Referenced by call(), Clear(), clear_call(), InitAsDefaultInstance(), mutable_call(), release_call(), set_allocated_call(), SharedCtor(), SharedDtor(), and Swap().
CallRewrite * previrt::proto::CallRewrite::default_instance_ = NULL static private
Definition at line 966 of file Previrt.pb.h.
Referenced by call(), default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
const int previrt::proto::CallRewrite::kArgsFieldNumber = 3 static
Definition at line 935 of file Previrt.pb.h.
const int previrt::proto::CallRewrite::kCallFieldNumber = 1 static
Definition at line 914 of file Previrt.pb.h.
const int previrt::proto::CallRewrite::kNewFunctionFieldNumber = 2 static
Definition at line 923 of file Previrt.pb.h.
::std::string* previrt::proto::CallRewrite::new_function_ private
Definition at line 954 of file Previrt.pb.h.
Referenced by Clear(), clear_new_function(), mutable_new_function(), new_function(), release_new_function(), set_allocated_new_function(), set_new_function(), SharedCtor(), SharedDtor(), and Swap().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc