Occam - Application Specialization: previrt::proto::PrevirtType_Global Class Reference
previrt::proto::PrevirtType_Global Class Reference
#include <Previrt.pb.h>
Public Member Functions
PrevirtType_Global ()
virtual ~PrevirtType_Global ()
PrevirtType_Global (const PrevirtType_Global &from)
PrevirtType_Global & operator= (const PrevirtType_Global &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (PrevirtType_Global *other)
PrevirtType_Global * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const PrevirtType_Global &from)
void MergeFrom (const PrevirtType_Global &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_name () const
void clear_name ()
const ::std::string & name () const
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const void *value, size_t size)
inline::std::string * mutable_name ()
inline::std::string * release_name ()
void set_allocated_name (::std::string *name)
bool has_is_const () const
void clear_is_const ()
bool is_const () const
void set_is_const (bool value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const PrevirtType_Global & default_instance ()
Static Public Attributes
static const int kNameFieldNumber = 51
static const int kIsConstFieldNumber = 52
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_name ()
void clear_has_name ()
void set_has_is_const ()
void clear_has_is_const ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::std::string * name_
bool is_const_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(2+31)/32]
Static Private Attributes
static PrevirtType_Global * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 502 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::PrevirtType_Global::PrevirtType_Global ()
Definition at line 1593 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::PrevirtType_Global::~PrevirtType_Global () virtual
Definition at line 1614 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::PrevirtType_Global::PrevirtType_Global (const PrevirtType_Global & from)
Definition at line 1601 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
int previrt::proto::PrevirtType_Global::ByteSize () const
Definition at line 1751 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, has_is_const(), has_name(), name(), and unknown_fields().
void previrt::proto::PrevirtType_Global::Clear ()
Definition at line 1647 of file Previrt.pb.cc.
References _has_bits_, has_name(), is_const_, mutable_unknown_fields(), and name_.
Referenced by CopyFrom().
void previrt::proto::PrevirtType_Global::clear_has_is_const () inline private
Definition at line 2203 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_is_const().
void previrt::proto::PrevirtType_Global::clear_has_name () inline private
Definition at line 2133 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_name(), release_name(), and set_allocated_name().
void previrt::proto::PrevirtType_Global::clear_is_const () inline
Definition at line 2206 of file Previrt.pb.h.
References clear_has_is_const(), and is_const_.
void previrt::proto::PrevirtType_Global::clear_name () inline
Definition at line 2136 of file Previrt.pb.h.
References clear_has_name(), and name_.
void previrt::proto::PrevirtType_Global::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1804 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::PrevirtType_Global::CopyFrom (const PrevirtType_Global & from)
Definition at line 1810 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const PrevirtType_Global & previrt::proto::PrevirtType_Global::default_instance () static
Definition at line 1636 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::PrevirtType::InitAsDefaultInstance(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::PrevirtType_Global::descriptor () static
Definition at line 1631 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Global_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
int previrt::proto::PrevirtType_Global::GetCachedSize () const inline
Definition at line 543 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::PrevirtType_Global::GetMetadata () const
Definition at line 1832 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Global_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Global_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
bool previrt::proto::PrevirtType_Global::has_is_const () const inline
Definition at line 2197 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::PrevirtType_Global::has_name () const inline
Definition at line 2127 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::PrevirtType_Global::InitAsDefaultInstance () private
Definition at line 1598 of file Previrt.pb.cc.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::PrevirtType_Global::is_const () const inline
Definition at line 2210 of file Previrt.pb.h.
References is_const_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::PrevirtType_Global::IsInitialized () const
Definition at line 1816 of file Previrt.pb.cc.
References _has_bits_.
void previrt::proto::PrevirtType_Global::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 1779 of file Previrt.pb.cc.
Referenced by CopyFrom(), and PrevirtType_Global().
void previrt::proto::PrevirtType_Global::MergeFrom (const PrevirtType_Global & from)
Definition at line 1791 of file Previrt.pb.cc.
References _has_bits_, has_is_const(), has_name(), is_const(), mutable_unknown_fields(), name(), set_is_const(), set_name(), and unknown_fields().
bool previrt::proto::PrevirtType_Global::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 1660 of file Previrt.pb.cc.
References DO_, is_const_, mutable_name(), mutable_unknown_fields(), and set_has_is_const().
std::string * previrt::proto::PrevirtType_Global::mutable_name () inline
Definition at line 2166 of file Previrt.pb.h.
References name_, and set_has_name().
Referenced by MergePartialFromCodedStream().
inline ::google::protobuf::UnknownFieldSet* previrt::proto::PrevirtType_Global::mutable_unknown_fields () inline
Definition at line 518 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
const ::std::string & previrt::proto::PrevirtType_Global::name () const inline
Definition at line 2142 of file Previrt.pb.h.
References name_.
Referenced by ByteSize(), MergeFrom(), previrt::PrevirtType::operator==(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_name().
PrevirtType_Global * previrt::proto::PrevirtType_Global::New () const
Definition at line 1643 of file Previrt.pb.cc.
References PrevirtType_Global().
PrevirtType_Global& previrt::proto::PrevirtType_Global::operator= (const PrevirtType_Global & from) inline
Definition at line 509 of file Previrt.pb.h.
References CopyFrom().
std::string * previrt::proto::PrevirtType_Global::release_name () inline
Definition at line 2173 of file Previrt.pb.h.
References clear_has_name(), and name_.
void previrt::proto::PrevirtType_Global::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 1711 of file Previrt.pb.cc.
References has_is_const(), has_name(), is_const(), name(), and unknown_fields().
google::protobuf::uint8 * previrt::proto::PrevirtType_Global::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 1730 of file Previrt.pb.cc.
References has_is_const(), has_name(), is_const(), name(), and unknown_fields().
void previrt::proto::PrevirtType_Global::set_allocated_name (::std::string * name) inline
Definition at line 2183 of file Previrt.pb.h.
References clear_has_name(), name(), name_, and set_has_name().
void previrt::proto::PrevirtType_Global::set_has_is_const () inline private
Definition at line 2200 of file Previrt.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_is_const().
void previrt::proto::PrevirtType_Global::set_has_name () inline private
Definition at line 2130 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_name(), set_allocated_name(), and set_name().
void previrt::proto::PrevirtType_Global::set_is_const (bool value) inline
Definition at line 2213 of file Previrt.pb.h.
References is_const_, and set_has_is_const().
Referenced by MergeFrom().
void previrt::proto::PrevirtType_Global::set_name (const ::std::string & value) inline
Definition at line 2145 of file Previrt.pb.h.
References name_, and set_has_name().
Referenced by MergeFrom().
void previrt::proto::PrevirtType_Global::set_name (const char * value) inline
Definition at line 2152 of file Previrt.pb.h.
References name_, and set_has_name().
void previrt::proto::PrevirtType_Global::set_name (const void * value, size_t size) inline
Definition at line 2159 of file Previrt.pb.h.
References name_, and set_has_name().
void previrt::proto::PrevirtType_Global::SetCachedSize (int size) const private
Definition at line 1626 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::PrevirtType_Global::SharedCtor () private
Definition at line 1607 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, is_const_, and name_.
Referenced by PrevirtType_Global().
void previrt::proto::PrevirtType_Global::SharedDtor () private
Definition at line 1618 of file Previrt.pb.cc.
References default_instance_, and name_.
Referenced by ~PrevirtType_Global().
void previrt::proto::PrevirtType_Global::Swap (PrevirtType_Global * other)
Definition at line 1822 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, is_const_, and name_.
const ::google::protobuf::UnknownFieldSet& previrt::proto::PrevirtType_Global::unknown_fields () const inline
Definition at line 514 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::PrevirtType_Global::_cached_size_ mutable private
Definition at line 587 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::PrevirtType_Global::_has_bits_[(2+31)/32] private
Definition at line 588 of file Previrt.pb.h.
Referenced by ByteSize(), Clear(), clear_has_is_const(), clear_has_name(), has_is_const(), has_name(), IsInitialized(), MergeFrom(), set_has_is_const(), set_has_name(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::PrevirtType_Global::_unknown_fields_ private
Definition at line 582 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
PrevirtType_Global * previrt::proto::PrevirtType_Global::default_instance_ = NULL static private
Definition at line 595 of file Previrt.pb.h.
Referenced by default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
bool previrt::proto::PrevirtType_Global::is_const_ private
Definition at line 585 of file Previrt.pb.h.
Referenced by Clear(), clear_is_const(), is_const(), MergePartialFromCodedStream(), set_is_const(), SharedCtor(), and Swap().
const int previrt::proto::PrevirtType_Global::kIsConstFieldNumber = 52 static
Definition at line 571 of file Previrt.pb.h.
const int previrt::proto::PrevirtType_Global::kNameFieldNumber = 51 static
Definition at line 559 of file Previrt.pb.h.
::std::string* previrt::proto::PrevirtType_Global::name_ private
Definition at line 584 of file Previrt.pb.h.
Referenced by Clear(), clear_name(), mutable_name(), name(), release_name(), set_allocated_name(), set_name(), SharedCtor(), SharedDtor(), and Swap().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc