Occam - Application Specialization: previrt::proto::EnforceInterface Class Reference
previrt::proto::EnforceInterface Class Reference
#include <Previrt.pb.h>
Public Types
typedef EnforceInterface_Functions Functions
Public Member Functions
EnforceInterface ()
virtual ~EnforceInterface ()
EnforceInterface (const EnforceInterface &from)
EnforceInterface & operator= (const EnforceInterface &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (EnforceInterface *other)
EnforceInterface * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const EnforceInterface &from)
void MergeFrom (const EnforceInterface &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
int functions_size () const
void clear_functions ()
const
::previrt::proto::EnforceInterface_Functions & functions (int index) const
inline::previrt::proto::EnforceInterface_Functions * mutable_functions (int index)
inline::previrt::proto::EnforceInterface_Functions * add_functions ()
const
::google::protobuf::RepeatedPtrField
< ::previrt::proto::EnforceInterface_Functions > & functions () const
inline::google::protobuf::RepeatedPtrField
< ::previrt::proto::EnforceInterface_Functions > * mutable_functions ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const EnforceInterface & default_instance ()
Static Public Attributes
static const int kFunctionsFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::RepeatedPtrField
< ::previrt::proto::EnforceInterface_Functions > functions_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(1+31)/32]
Static Private Attributes
static EnforceInterface * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 1716 of file Previrt.pb.h.
Member Typedef Documentation
typedef EnforceInterface_Functions previrt::proto::EnforceInterface::Functions
Definition at line 1768 of file Previrt.pb.h.
Constructor & Destructor Documentation
EnforceInterface::EnforceInterface ()
Definition at line 4946 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
EnforceInterface::~EnforceInterface () virtual
Definition at line 4965 of file Previrt.pb.cc.
References SharedDtor().
EnforceInterface::EnforceInterface (const EnforceInterface & from)
Definition at line 4954 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
previrt::proto::EnforceInterface_Functions * EnforceInterface::add_functions () inline
Definition at line 3431 of file Previrt.pb.h.
References functions_.
Referenced by MergePartialFromCodedStream().
int EnforceInterface::ByteSize () const
Definition at line 5068 of file Previrt.pb.cc.
References _cached_size_, functions(), functions_size(), and unknown_fields().
void EnforceInterface::Clear ()
Definition at line 4995 of file Previrt.pb.cc.
References _has_bits_, functions_, and mutable_unknown_fields().
Referenced by CopyFrom().
void EnforceInterface::clear_functions () inline
Definition at line 3419 of file Previrt.pb.h.
References functions_.
void EnforceInterface::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 5108 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void EnforceInterface::CopyFrom (const EnforceInterface & from)
Definition at line 5114 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const EnforceInterface & EnforceInterface::default_instance () static
Definition at line 4984 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * EnforceInterface::descriptor () static
Definition at line 4979 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::EnforceInterface_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
const ::previrt::proto::EnforceInterface_Functions & EnforceInterface::functions (int index) const inline
Definition at line 3423 of file Previrt.pb.h.
References functions_.
const ::google::protobuf::RepeatedPtrField<::previrt::proto::EnforceInterface_Functions > & EnforceInterface::functions () const inline
Definition at line 3436 of file Previrt.pb.h.
References functions_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int EnforceInterface::functions_size () const inline
Definition at line 3415 of file Previrt.pb.h.
References functions_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::EnforceInterface::GetCachedSize () const inline
Definition at line 1757 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata EnforceInterface::GetMetadata () const
Definition at line 5137 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::EnforceInterface_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::EnforceInterface_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
void EnforceInterface::InitAsDefaultInstance () private
Definition at line 4951 of file Previrt.pb.cc.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool EnforceInterface::IsInitialized () const
Definition at line 5120 of file Previrt.pb.cc.
References functions(), and functions_size().
void EnforceInterface::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 5090 of file Previrt.pb.cc.
Referenced by CopyFrom(), and EnforceInterface().
void EnforceInterface::MergeFrom (const EnforceInterface & from)
Definition at line 5102 of file Previrt.pb.cc.
References functions_, mutable_unknown_fields(), and unknown_fields().
bool EnforceInterface::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 5001 of file Previrt.pb.cc.
References add_functions(), DO_, and mutable_unknown_fields().
previrt::proto::EnforceInterface_Functions * EnforceInterface::mutable_functions (int index) inline
Definition at line 3427 of file Previrt.pb.h.
References functions_.
google::protobuf::RepeatedPtrField<::previrt::proto::EnforceInterface_Functions > * EnforceInterface::mutable_functions () inline
Definition at line 3441 of file Previrt.pb.h.
References functions_.
inline ::google::protobuf::UnknownFieldSet* previrt::proto::EnforceInterface::mutable_unknown_fields () inline
Definition at line 1732 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
EnforceInterface * EnforceInterface::New () const
Definition at line 4991 of file Previrt.pb.cc.
References EnforceInterface().
EnforceInterface& previrt::proto::EnforceInterface::operator= (const EnforceInterface & from) inline
Definition at line 1723 of file Previrt.pb.h.
References CopyFrom().
void EnforceInterface::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 5038 of file Previrt.pb.cc.
References functions(), functions_size(), and unknown_fields().
google::protobuf::uint8 * EnforceInterface::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 5052 of file Previrt.pb.cc.
References functions(), functions_size(), and unknown_fields().
void EnforceInterface::SetCachedSize (int size) const private
Definition at line 4974 of file Previrt.pb.cc.
References _cached_size_.
void EnforceInterface::SharedCtor () private
Definition at line 4960 of file Previrt.pb.cc.
References _cached_size_, and _has_bits_.
Referenced by EnforceInterface().
void EnforceInterface::SharedDtor () private
Definition at line 4969 of file Previrt.pb.cc.
References default_instance_.
Referenced by ~EnforceInterface().
void EnforceInterface::Swap (EnforceInterface * other)
Definition at line 5128 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, and functions_.
const ::google::protobuf::UnknownFieldSet& previrt::proto::EnforceInterface::unknown_fields () const inline
Definition at line 1728 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::EnforceInterface::_cached_size_ mutable private
Definition at line 1791 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::EnforceInterface::_has_bits_[(1+31)/32] private
Definition at line 1792 of file Previrt.pb.h.
Referenced by Clear(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::EnforceInterface::_unknown_fields_ private
Definition at line 1787 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
EnforceInterface * EnforceInterface::default_instance_ = NULL static private
Definition at line 1799 of file Previrt.pb.h.
Referenced by default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
::google::protobuf::RepeatedPtrField< ::previrt::proto::EnforceInterface_Functions > previrt::proto::EnforceInterface::functions_ private
Definition at line 1789 of file Previrt.pb.h.
Referenced by add_functions(), Clear(), clear_functions(), functions(), functions_size(), MergeFrom(), mutable_functions(), and Swap().
const int EnforceInterface::kFunctionsFieldNumber = 1 static
Definition at line 1775 of file Previrt.pb.h.
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc