Occam - Application Specialization: previrt::proto::ActionTree Class Reference
previrt::proto::ActionTree Class Reference
#include <Previrt.pb.h>
Public Types
typedef ActionTree_Case Case
typedef ActionTree_Forward Forward
typedef ActionTree_Event Event
Public Member Functions
ActionTree ()
virtual ~ActionTree ()
ActionTree (const ActionTree &from)
ActionTree & operator= (const ActionTree &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ActionTree *other)
ActionTree * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ActionTree &from)
void MergeFrom (const ActionTree &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_type () const
void clear_type ()
inline::previrt::proto::ActionType type () const
void set_type (::previrt::proto::ActionType value)
bool has_case_ () const
void clear_case_ ()
const
::previrt::proto::ActionTree_Case & case_ () const
inline::previrt::proto::ActionTree_Case * mutable_case_ ()
inline::previrt::proto::ActionTree_Case * release_case_ ()
void set_allocated_case_ (::previrt::proto::ActionTree_Case *case_)
bool has_forward () const
void clear_forward ()
const
::previrt::proto::ActionTree_Forward & forward () const
inline::previrt::proto::ActionTree_Forward * mutable_forward ()
inline::previrt::proto::ActionTree_Forward * release_forward ()
void set_allocated_forward (::previrt::proto::ActionTree_Forward *forward)
bool has_event () const
void clear_event ()
const
::previrt::proto::ActionTree_Event & event () const
inline::previrt::proto::ActionTree_Event * mutable_event ()
inline::previrt::proto::ActionTree_Event * release_event ()
void set_allocated_event (::previrt::proto::ActionTree_Event *event)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const ActionTree & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kCaseFieldNumber = 10
static const int kForwardFieldNumber = 20
static const int kEventFieldNumber = 30
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_type ()
void clear_has_type ()
void set_has_case_ ()
void clear_has_case_ ()
void set_has_forward ()
void clear_has_forward ()
void set_has_event ()
void clear_has_event ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::previrt::proto::ActionTree_Case * case__
::previrt::proto::ActionTree_Forward * forward_
::previrt::proto::ActionTree_Event * event_
int type_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(4+31)/32]
Static Private Attributes
static ActionTree * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 1495 of file Previrt.pb.h.
Member Typedef Documentation
typedef ActionTree_Case previrt::proto::ActionTree::Case
Definition at line 1547 of file Previrt.pb.h.
typedef ActionTree_Event previrt::proto::ActionTree::Event
Definition at line 1549 of file Previrt.pb.h.
typedef ActionTree_Forward previrt::proto::ActionTree::Forward
Definition at line 1548 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::ActionTree::ActionTree ()
Definition at line 4328 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::ActionTree::~ActionTree () virtual
Definition at line 4354 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::ActionTree::ActionTree (const ActionTree & from)
Definition at line 4339 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
int previrt::proto::ActionTree::ByteSize () const
Definition at line 4556 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, case_(), event(), forward(), has_case_(), has_event(), has_forward(), has_type(), type(), and unknown_fields().
const ::previrt::proto::ActionTree_Case & previrt::proto::ActionTree::case_ () const inline
Definition at line 3189 of file Previrt.pb.h.
References case__, and default_instance_.
Referenced by ByteSize(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_case_().
void previrt::proto::ActionTree::Clear ()
Definition at line 4387 of file Previrt.pb.cc.
References _has_bits_, case__, event_, forward_, has_case_(), has_event(), has_forward(), mutable_unknown_fields(), and type_.
Referenced by CopyFrom().
void previrt::proto::ActionTree::clear_case_ () inline
Definition at line 3185 of file Previrt.pb.h.
References case__, and clear_has_case_().
void previrt::proto::ActionTree::clear_event () inline
Definition at line 3261 of file Previrt.pb.h.
References clear_has_event(), and event_.
void previrt::proto::ActionTree::clear_forward () inline
Definition at line 3223 of file Previrt.pb.h.
References clear_has_forward(), and forward_.
void previrt::proto::ActionTree::clear_has_case_ () inline private
Definition at line 3182 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_case_(), release_case_(), and set_allocated_case_().
void previrt::proto::ActionTree::clear_has_event () inline private
Definition at line 3258 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_event(), release_event(), and set_allocated_event().
void previrt::proto::ActionTree::clear_has_forward () inline private
Definition at line 3220 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_forward(), release_forward(), and set_allocated_forward().
void previrt::proto::ActionTree::clear_has_type () inline private
Definition at line 3159 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_type().
void previrt::proto::ActionTree::clear_type () inline
Definition at line 3162 of file Previrt.pb.h.
References clear_has_type(), and type_.
void previrt::proto::ActionTree::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 4630 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::ActionTree::CopyFrom (const ActionTree & from)
Definition at line 4636 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const ActionTree & previrt::proto::ActionTree::default_instance () static
Definition at line 4376 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::ActionTree_Case::InitAsDefaultInstance(), previrt::proto::ActionTree_Event::InitAsDefaultInstance(), previrt::proto::EnforceInterface_Functions::InitAsDefaultInstance(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::ActionTree::descriptor () static
Definition at line 4371 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
const ::previrt::proto::ActionTree_Event & previrt::proto::ActionTree::event () const inline
Definition at line 3265 of file Previrt.pb.h.
References default_instance_, and event_.
Referenced by ByteSize(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_event().
const ::previrt::proto::ActionTree_Forward & previrt::proto::ActionTree::forward () const inline
Definition at line 3227 of file Previrt.pb.h.
References default_instance_, and forward_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_forward().
int previrt::proto::ActionTree::GetCachedSize () const inline
Definition at line 1536 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::ActionTree::GetMetadata () const
Definition at line 4666 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
bool previrt::proto::ActionTree::has_case_ () const inline
Definition at line 3176 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::ActionTree::has_event () const inline
Definition at line 3252 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::ActionTree::has_forward () const inline
Definition at line 3214 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::ActionTree::has_type () const inline
Definition at line 3153 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::ActionTree::InitAsDefaultInstance () private
Definition at line 4333 of file Previrt.pb.cc.
References case__, previrt::proto::ActionTree_Case::default_instance(), previrt::proto::ActionTree_Forward::default_instance(), previrt::proto::ActionTree_Event::default_instance(), event_, and forward_.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::ActionTree::IsInitialized () const
Definition at line 4642 of file Previrt.pb.cc.
References _has_bits_, case_(), event(), has_case_(), and has_event().
void previrt::proto::ActionTree::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 4599 of file Previrt.pb.cc.
Referenced by ActionTree(), and CopyFrom().
void previrt::proto::ActionTree::MergeFrom (const ActionTree & from)
Definition at line 4611 of file Previrt.pb.cc.
References _has_bits_, case_(), event(), forward(), has_case_(), has_event(), has_forward(), has_type(), mutable_case_(), mutable_event(), mutable_forward(), mutable_unknown_fields(), set_type(), type(), and unknown_fields().
bool previrt::proto::ActionTree::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 4404 of file Previrt.pb.cc.
References previrt::proto::ActionType_IsValid(), DO_, mutable_case_(), mutable_event(), mutable_forward(), mutable_unknown_fields(), and set_type().
previrt::proto::ActionTree_Case * previrt::proto::ActionTree::mutable_case_ () inline
Definition at line 3192 of file Previrt.pb.h.
References case__, and set_has_case_().
Referenced by MergeFrom(), and MergePartialFromCodedStream().
previrt::proto::ActionTree_Event * previrt::proto::ActionTree::mutable_event () inline
Definition at line 3268 of file Previrt.pb.h.
References event_, and set_has_event().
Referenced by MergeFrom(), and MergePartialFromCodedStream().
previrt::proto::ActionTree_Forward * previrt::proto::ActionTree::mutable_forward () inline
Definition at line 3230 of file Previrt.pb.h.
References forward_, and set_has_forward().
Referenced by MergeFrom(), and MergePartialFromCodedStream().
inline ::google::protobuf::UnknownFieldSet* previrt::proto::ActionTree::mutable_unknown_fields () inline
Definition at line 1511 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
ActionTree * previrt::proto::ActionTree::New () const
Definition at line 4383 of file Previrt.pb.cc.
References ActionTree().
ActionTree& previrt::proto::ActionTree::operator= (const ActionTree & from) inline
Definition at line 1502 of file Previrt.pb.h.
References CopyFrom().
previrt::proto::ActionTree_Case * previrt::proto::ActionTree::release_case_ () inline
Definition at line 3197 of file Previrt.pb.h.
References case__, and clear_has_case_().
previrt::proto::ActionTree_Event * previrt::proto::ActionTree::release_event () inline
Definition at line 3273 of file Previrt.pb.h.
References clear_has_event(), and event_.
previrt::proto::ActionTree_Forward * previrt::proto::ActionTree::release_forward () inline
Definition at line 3235 of file Previrt.pb.h.
References clear_has_forward(), and forward_.
void previrt::proto::ActionTree::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 4488 of file Previrt.pb.cc.
References case_(), event(), forward(), has_case_(), has_event(), has_forward(), has_type(), type(), and unknown_fields().
google::protobuf::uint8 * previrt::proto::ActionTree::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 4520 of file Previrt.pb.cc.
References case_(), event(), forward(), has_case_(), has_event(), has_forward(), has_type(), type(), and unknown_fields().
void previrt::proto::ActionTree::set_allocated_case_ (::previrt::proto::ActionTree_Case * case_) inline
Definition at line 3203 of file Previrt.pb.h.
References case_(), case__, clear_has_case_(), and set_has_case_().
void previrt::proto::ActionTree::set_allocated_event (::previrt::proto::ActionTree_Event * event) inline
Definition at line 3279 of file Previrt.pb.h.
References clear_has_event(), event(), event_, and set_has_event().
void previrt::proto::ActionTree::set_allocated_forward (::previrt::proto::ActionTree_Forward * forward) inline
Definition at line 3241 of file Previrt.pb.h.
References clear_has_forward(), forward(), forward_, and set_has_forward().
void previrt::proto::ActionTree::set_has_case_ () inline private
Definition at line 3179 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_case_(), and set_allocated_case_().
void previrt::proto::ActionTree::set_has_event () inline private
Definition at line 3255 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_event(), and set_allocated_event().
void previrt::proto::ActionTree::set_has_forward () inline private
Definition at line 3217 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_forward(), and set_allocated_forward().
void previrt::proto::ActionTree::set_has_type () inline private
Definition at line 3156 of file Previrt.pb.h.
References _has_bits_.
Referenced by set_type().
void previrt::proto::ActionTree::set_type (::previrt::proto::ActionType value) inline
Definition at line 3169 of file Previrt.pb.h.
References previrt::proto::ActionType_IsValid(), set_has_type(), and type_.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
void previrt::proto::ActionTree::SetCachedSize (int size) const private
Definition at line 4366 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::ActionTree::SharedCtor () private
Definition at line 4345 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, case__, event_, forward_, and type_.
Referenced by ActionTree().
void previrt::proto::ActionTree::SharedDtor () private
Definition at line 4358 of file Previrt.pb.cc.
References case__, default_instance_, event_, and forward_.
Referenced by ~ActionTree().
void previrt::proto::ActionTree::Swap (ActionTree * other)
Definition at line 4654 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, case__, event_, forward_, and type_.
previrt::proto::ActionType previrt::proto::ActionTree::type () const inline
Definition at line 3166 of file Previrt.pb.h.
References type_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
const ::google::protobuf::UnknownFieldSet& previrt::proto::ActionTree::unknown_fields () const inline
Definition at line 1507 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::ActionTree::_cached_size_ mutable private
Definition at line 1605 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::ActionTree::_has_bits_[(4+31)/32] private
Definition at line 1606 of file Previrt.pb.h.
Referenced by ByteSize(), Clear(), clear_has_case_(), clear_has_event(), clear_has_forward(), clear_has_type(), has_case_(), has_event(), has_forward(), has_type(), IsInitialized(), MergeFrom(), set_has_case_(), set_has_event(), set_has_forward(), set_has_type(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::ActionTree::_unknown_fields_ private
Definition at line 1598 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
::previrt::proto::ActionTree_Case* previrt::proto::ActionTree::case__ private
Definition at line 1600 of file Previrt.pb.h.
Referenced by case_(), Clear(), clear_case_(), InitAsDefaultInstance(), mutable_case_(), release_case_(), set_allocated_case_(), SharedCtor(), SharedDtor(), and Swap().
ActionTree * previrt::proto::ActionTree::default_instance_ = NULL static private
Definition at line 1613 of file Previrt.pb.h.
Referenced by case_(), default_instance(), event(), forward(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
::previrt::proto::ActionTree_Event* previrt::proto::ActionTree::event_ private
Definition at line 1602 of file Previrt.pb.h.
Referenced by Clear(), clear_event(), event(), InitAsDefaultInstance(), mutable_event(), release_event(), set_allocated_event(), SharedCtor(), SharedDtor(), and Swap().
::previrt::proto::ActionTree_Forward* previrt::proto::ActionTree::forward_ private
Definition at line 1601 of file Previrt.pb.h.
Referenced by Clear(), clear_forward(), forward(), InitAsDefaultInstance(), mutable_forward(), release_forward(), set_allocated_forward(), SharedCtor(), SharedDtor(), and Swap().
const int previrt::proto::ActionTree::kCaseFieldNumber = 10 static
Definition at line 1563 of file Previrt.pb.h.
const int previrt::proto::ActionTree::kEventFieldNumber = 30 static
Definition at line 1581 of file Previrt.pb.h.
const int previrt::proto::ActionTree::kForwardFieldNumber = 20 static
Definition at line 1572 of file Previrt.pb.h.
const int previrt::proto::ActionTree::kTypeFieldNumber = 1 static
Definition at line 1556 of file Previrt.pb.h.
int previrt::proto::ActionTree::type_ private
Definition at line 1603 of file Previrt.pb.h.
Referenced by Clear(), clear_type(), set_type(), SharedCtor(), Swap(), and type().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc