Occam - Application Specialization: previrt::proto::ActionTree_Case Class Reference
previrt::proto::ActionTree_Case Class Reference
#include <Previrt.pb.h>
Public Member Functions
ActionTree_Case ()
virtual ~ActionTree_Case ()
ActionTree_Case (const ActionTree_Case &from)
ActionTree_Case & operator= (const ActionTree_Case &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ActionTree_Case *other)
ActionTree_Case * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ActionTree_Case &from)
void MergeFrom (const ActionTree_Case &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_var () const
void clear_var ()
inline::google::protobuf::int32 var () const
void set_var (::google::protobuf::int32 value)
bool has_test () const
void clear_test ()
const
::previrt::proto::PrevirtType & test () const
inline::previrt::proto::PrevirtType * mutable_test ()
inline::previrt::proto::PrevirtType * release_test ()
void set_allocated_test (::previrt::proto::PrevirtType *test)
bool has__then () const
void clear__then ()
const
::previrt::proto::ActionTree & _then () const
inline::previrt::proto::ActionTree * mutable__then ()
inline::previrt::proto::ActionTree * release__then ()
void set_allocated__then (::previrt::proto::ActionTree *_then)
bool has__else () const
void clear__else ()
const
::previrt::proto::ActionTree & _else () const
inline::previrt::proto::ActionTree * mutable__else ()
inline::previrt::proto::ActionTree * release__else ()
void set_allocated__else (::previrt::proto::ActionTree *_else)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const ActionTree_Case & default_instance ()
Static Public Attributes
static const int kVarFieldNumber = 11
static const int kTestFieldNumber = 12
static const int kThenFieldNumber = 18
static const int kElseFieldNumber = 19
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_var ()
void clear_has_var ()
void set_has_test ()
void clear_has_test ()
void set_has__then ()
void clear_has__then ()
void set_has__else ()
void clear_has__else ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::previrt::proto::PrevirtType * test_
::previrt::proto::ActionTree * _then_
::previrt::proto::ActionTree * _else_
::google::protobuf::int32 var_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(4+31)/32]
Static Private Attributes
static ActionTree_Case * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 1183 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::ActionTree_Case::ActionTree_Case ()
Definition at line 3469 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::ActionTree_Case::~ActionTree_Case () virtual
Definition at line 3495 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::ActionTree_Case::ActionTree_Case (const ActionTree_Case & from)
Definition at line 3480 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
const ::previrt::proto::ActionTree & previrt::proto::ActionTree_Case::_else () const inline
Definition at line 2961 of file Previrt.pb.h.
References _else_, and default_instance_.
Referenced by ByteSize(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated__else().
const ::previrt::proto::ActionTree & previrt::proto::ActionTree_Case::_then () const inline
Definition at line 2923 of file Previrt.pb.h.
References _then_, and default_instance_.
Referenced by ByteSize(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated__then().
int previrt::proto::ActionTree_Case::ByteSize () const
Definition at line 3690 of file Previrt.pb.cc.
References _cached_size_, _else(), _has_bits_, _then(), has__else(), has__then(), has_test(), has_var(), test(), unknown_fields(), and var().
void previrt::proto::ActionTree_Case::Clear ()
Definition at line 3528 of file Previrt.pb.cc.
References _else_, _has_bits_, _then_, has__else(), has__then(), has_test(), mutable_unknown_fields(), test_, and var_.
Referenced by CopyFrom().
void previrt::proto::ActionTree_Case::clear__else () inline
Definition at line 2957 of file Previrt.pb.h.
References _else_, and clear_has__else().
void previrt::proto::ActionTree_Case::clear__then () inline
Definition at line 2919 of file Previrt.pb.h.
References _then_, and clear_has__then().
void previrt::proto::ActionTree_Case::clear_has__else () inline private
Definition at line 2954 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear__else(), release__else(), and set_allocated__else().
void previrt::proto::ActionTree_Case::clear_has__then () inline private
Definition at line 2916 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear__then(), release__then(), and set_allocated__then().
void previrt::proto::ActionTree_Case::clear_has_test () inline private
Definition at line 2878 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_test(), release_test(), and set_allocated_test().
void previrt::proto::ActionTree_Case::clear_has_var () inline private
Definition at line 2856 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_var().
void previrt::proto::ActionTree_Case::clear_test () inline
Definition at line 2881 of file Previrt.pb.h.
References clear_has_test(), and test_.
void previrt::proto::ActionTree_Case::clear_var () inline
Definition at line 2859 of file Previrt.pb.h.
References clear_has_var(), and var_.
void previrt::proto::ActionTree_Case::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 3765 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::ActionTree_Case::CopyFrom (const ActionTree_Case & from)
Definition at line 3771 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const ActionTree_Case & previrt::proto::ActionTree_Case::default_instance () static
Definition at line 3517 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::ActionTree::InitAsDefaultInstance(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::ActionTree_Case::descriptor () static
Definition at line 3512 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Case_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
int previrt::proto::ActionTree_Case::GetCachedSize () const inline
Definition at line 1224 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::ActionTree_Case::GetMetadata () const
Definition at line 3804 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Case_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Case_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
bool previrt::proto::ActionTree_Case::has__else () const inline
Definition at line 2948 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::ActionTree_Case::has__then () const inline
Definition at line 2910 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::ActionTree_Case::has_test () const inline
Definition at line 2872 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::ActionTree_Case::has_var () const inline
Definition at line 2850 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::ActionTree_Case::InitAsDefaultInstance () private
Definition at line 3474 of file Previrt.pb.cc.
References _else_, _then_, previrt::proto::PrevirtType::default_instance(), previrt::proto::ActionTree::default_instance(), and test_.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::ActionTree_Case::IsInitialized () const
Definition at line 3777 of file Previrt.pb.cc.
References _else(), _has_bits_, _then(), has__else(), has__then(), has_test(), and test().
void previrt::proto::ActionTree_Case::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 3734 of file Previrt.pb.cc.
Referenced by ActionTree_Case(), and CopyFrom().
void previrt::proto::ActionTree_Case::MergeFrom (const ActionTree_Case & from)
Definition at line 3746 of file Previrt.pb.cc.
References _else(), _has_bits_, _then(), has__else(), has__then(), has_test(), has_var(), mutable__else(), mutable__then(), mutable_test(), mutable_unknown_fields(), set_var(), test(), unknown_fields(), and var().
bool previrt::proto::ActionTree_Case::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 3545 of file Previrt.pb.cc.
References DO_, mutable__else(), mutable__then(), mutable_test(), mutable_unknown_fields(), set_has_var(), and var_.
previrt::proto::ActionTree * previrt::proto::ActionTree_Case::mutable__else () inline
Definition at line 2964 of file Previrt.pb.h.
References _else_, and set_has__else().
Referenced by MergeFrom(), and MergePartialFromCodedStream().
previrt::proto::ActionTree * previrt::proto::ActionTree_Case::mutable__then () inline
Definition at line 2926 of file Previrt.pb.h.
References _then_, and set_has__then().
Referenced by MergeFrom(), and MergePartialFromCodedStream().
previrt::proto::PrevirtType * previrt::proto::ActionTree_Case::mutable_test () inline
Definition at line 2888 of file Previrt.pb.h.
References set_has_test(), and test_.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
inline ::google::protobuf::UnknownFieldSet* previrt::proto::ActionTree_Case::mutable_unknown_fields () inline
Definition at line 1199 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
ActionTree_Case * previrt::proto::ActionTree_Case::New () const
Definition at line 3524 of file Previrt.pb.cc.
References ActionTree_Case().
ActionTree_Case& previrt::proto::ActionTree_Case::operator= (const ActionTree_Case & from) inline
Definition at line 1190 of file Previrt.pb.h.
References CopyFrom().
previrt::proto::ActionTree * previrt::proto::ActionTree_Case::release__else () inline
Definition at line 2969 of file Previrt.pb.h.
References _else_, and clear_has__else().
previrt::proto::ActionTree * previrt::proto::ActionTree_Case::release__then () inline
Definition at line 2931 of file Previrt.pb.h.
References _then_, and clear_has__then().
previrt::proto::PrevirtType * previrt::proto::ActionTree_Case::release_test () inline
Definition at line 2893 of file Previrt.pb.h.
References clear_has_test(), and test_.
void previrt::proto::ActionTree_Case::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 3624 of file Previrt.pb.cc.
References _else(), _then(), has__else(), has__then(), has_test(), has_var(), test(), unknown_fields(), and var().
google::protobuf::uint8 * previrt::proto::ActionTree_Case::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 3655 of file Previrt.pb.cc.
References _else(), _then(), has__else(), has__then(), has_test(), has_var(), test(), unknown_fields(), and var().
void previrt::proto::ActionTree_Case::set_allocated__else (::previrt::proto::ActionTree * _else) inline
Definition at line 2975 of file Previrt.pb.h.
References _else(), _else_, clear_has__else(), and set_has__else().
void previrt::proto::ActionTree_Case::set_allocated__then (::previrt::proto::ActionTree * _then) inline
Definition at line 2937 of file Previrt.pb.h.
References _then(), _then_, clear_has__then(), and set_has__then().
void previrt::proto::ActionTree_Case::set_allocated_test (::previrt::proto::PrevirtType * test) inline
Definition at line 2899 of file Previrt.pb.h.
References clear_has_test(), set_has_test(), test(), and test_.
void previrt::proto::ActionTree_Case::set_has__else () inline private
Definition at line 2951 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable__else(), and set_allocated__else().
void previrt::proto::ActionTree_Case::set_has__then () inline private
Definition at line 2913 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable__then(), and set_allocated__then().
void previrt::proto::ActionTree_Case::set_has_test () inline private
Definition at line 2875 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_test(), and set_allocated_test().
void previrt::proto::ActionTree_Case::set_has_var () inline private
Definition at line 2853 of file Previrt.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_var().
void previrt::proto::ActionTree_Case::set_var (::google::protobuf::int32 value) inline
Definition at line 2866 of file Previrt.pb.h.
References set_has_var(), and var_.
Referenced by MergeFrom().
void previrt::proto::ActionTree_Case::SetCachedSize (int size) const private
Definition at line 3507 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::ActionTree_Case::SharedCtor () private
Definition at line 3486 of file Previrt.pb.cc.
References _cached_size_, _else_, _has_bits_, _then_, test_, and var_.
Referenced by ActionTree_Case().
void previrt::proto::ActionTree_Case::SharedDtor () private
Definition at line 3499 of file Previrt.pb.cc.
References _else_, _then_, default_instance_, and test_.
Referenced by ~ActionTree_Case().
void previrt::proto::ActionTree_Case::Swap (ActionTree_Case * other)
Definition at line 3792 of file Previrt.pb.cc.
References _cached_size_, _else_, _has_bits_, _then_, _unknown_fields_, test_, and var_.
const ::previrt::proto::PrevirtType & previrt::proto::ActionTree_Case::test () const inline
Definition at line 2885 of file Previrt.pb.h.
References default_instance_, and test_.
Referenced by ByteSize(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_test().
const ::google::protobuf::UnknownFieldSet& previrt::proto::ActionTree_Case::unknown_fields () const inline
Definition at line 1195 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
google::protobuf::int32 previrt::proto::ActionTree_Case::var () const inline
Definition at line 2863 of file Previrt.pb.h.
References var_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::ActionTree_Case::_cached_size_ mutable private
Definition at line 1289 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::previrt::proto::ActionTree* previrt::proto::ActionTree_Case::_else_ private
Definition at line 1286 of file Previrt.pb.h.
Referenced by _else(), Clear(), clear__else(), InitAsDefaultInstance(), mutable__else(), release__else(), set_allocated__else(), SharedCtor(), SharedDtor(), and Swap().
::google::protobuf::uint32 previrt::proto::ActionTree_Case::_has_bits_[(4+31)/32] private
Definition at line 1290 of file Previrt.pb.h.
Referenced by ByteSize(), Clear(), clear_has__else(), clear_has__then(), clear_has_test(), clear_has_var(), has__else(), has__then(), has_test(), has_var(), IsInitialized(), MergeFrom(), set_has__else(), set_has__then(), set_has_test(), set_has_var(), SharedCtor(), and Swap().
::previrt::proto::ActionTree* previrt::proto::ActionTree_Case::_then_ private
Definition at line 1285 of file Previrt.pb.h.
Referenced by _then(), Clear(), clear__then(), InitAsDefaultInstance(), mutable__then(), release__then(), set_allocated__then(), SharedCtor(), SharedDtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::ActionTree_Case::_unknown_fields_ private
Definition at line 1282 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
ActionTree_Case * previrt::proto::ActionTree_Case::default_instance_ = NULL static private
Definition at line 1297 of file Previrt.pb.h.
Referenced by _else(), _then(), default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), SharedDtor(), and test().
const int previrt::proto::ActionTree_Case::kElseFieldNumber = 19 static
Definition at line 1265 of file Previrt.pb.h.
const int previrt::proto::ActionTree_Case::kTestFieldNumber = 12 static
Definition at line 1247 of file Previrt.pb.h.
const int previrt::proto::ActionTree_Case::kThenFieldNumber = 18 static
Definition at line 1256 of file Previrt.pb.h.
const int previrt::proto::ActionTree_Case::kVarFieldNumber = 11 static
Definition at line 1240 of file Previrt.pb.h.
::previrt::proto::PrevirtType* previrt::proto::ActionTree_Case::test_ private
Definition at line 1284 of file Previrt.pb.h.
Referenced by Clear(), clear_test(), InitAsDefaultInstance(), mutable_test(), release_test(), set_allocated_test(), SharedCtor(), SharedDtor(), Swap(), and test().
::google::protobuf::int32 previrt::proto::ActionTree_Case::var_ private
Definition at line 1287 of file Previrt.pb.h.
Referenced by Clear(), clear_var(), MergePartialFromCodedStream(), set_var(), SharedCtor(), Swap(), and var().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc