Occam - Application Specialization: previrt::proto::ActionTree_Event Class Reference
previrt::proto::ActionTree_Event Class Reference
#include <Previrt.pb.h>
Public Member Functions
ActionTree_Event ()
virtual ~ActionTree_Event ()
ActionTree_Event (const ActionTree_Event &from)
ActionTree_Event & operator= (const ActionTree_Event &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ActionTree_Event *other)
ActionTree_Event * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ActionTree_Event &from)
void MergeFrom (const ActionTree_Event &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_exit () const
void clear_exit ()
bool exit () const
void set_exit (bool value)
bool has_handler () const
void clear_handler ()
const ::std::string & handler () const
void set_handler (const ::std::string &value)
void set_handler (const char *value)
void set_handler (const void *value, size_t size)
inline::std::string * mutable_handler ()
inline::std::string * release_handler ()
void set_allocated_handler (::std::string *handler)
int args_size () const
void clear_args ()
inline::google::protobuf::int32 args (int index) const
void set_args (int index,::google::protobuf::int32 value)
void add_args (::google::protobuf::int32 value)
const
::google::protobuf::RepeatedField
< ::google::protobuf::int32 > & args () const
inline::google::protobuf::RepeatedField
< ::google::protobuf::int32 > * mutable_args ()
bool has_then () const
void clear_then ()
const
::previrt::proto::ActionTree & then () const
inline::previrt::proto::ActionTree * mutable_then ()
inline::previrt::proto::ActionTree * release_then ()
void set_allocated_then (::previrt::proto::ActionTree *then)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const ActionTree_Event & default_instance ()
Static Public Attributes
static const int kExitFieldNumber = 31
static const int kHandlerFieldNumber = 32
static const int kArgsFieldNumber = 33
static const int kThenFieldNumber = 39
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_exit ()
void clear_has_exit ()
void set_has_handler ()
void clear_has_handler ()
void set_has_then ()
void clear_has_then ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::std::string * handler_
::google::protobuf::RepeatedField
< ::google::protobuf::int32 > args_
::previrt::proto::ActionTree * then_
bool exit_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(4+31)/32]
Static Private Attributes
static ActionTree_Event * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 1373 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::ActionTree_Event::ActionTree_Event ()
Definition at line 3978 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::ActionTree_Event::~ActionTree_Event () virtual
Definition at line 4001 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::ActionTree_Event::ActionTree_Event (const ActionTree_Event & from)
Definition at line 3987 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
void previrt::proto::ActionTree_Event::add_args (::google::protobuf::int32 value) inline
Definition at line 3098 of file Previrt.pb.h.
References args_.
google::protobuf::int32 previrt::proto::ActionTree_Event::args (int index) const inline
Definition at line 3092 of file Previrt.pb.h.
References args_.
const ::google::protobuf::RepeatedField<::google::protobuf::int32 > & previrt::proto::ActionTree_Event::args () const inline
Definition at line 3102 of file Previrt.pb.h.
References args_.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::ActionTree_Event::args_size () const inline
Definition at line 3086 of file Previrt.pb.h.
References args_.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::ActionTree_Event::ByteSize () const
Definition at line 4204 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, args(), args_size(), handler(), has_exit(), has_handler(), has_then(), then(), and unknown_fields().
void previrt::proto::ActionTree_Event::Clear ()
Definition at line 4035 of file Previrt.pb.cc.
References _has_bits_, args_, exit_, handler_, has_handler(), has_then(), mutable_unknown_fields(), and then_.
Referenced by CopyFrom().
void previrt::proto::ActionTree_Event::clear_args () inline
Definition at line 3089 of file Previrt.pb.h.
References args_.
void previrt::proto::ActionTree_Event::clear_exit () inline
Definition at line 3003 of file Previrt.pb.h.
References clear_has_exit(), and exit_.
void previrt::proto::ActionTree_Event::clear_handler () inline
Definition at line 3025 of file Previrt.pb.h.
References clear_has_handler(), and handler_.
void previrt::proto::ActionTree_Event::clear_has_exit () inline private
Definition at line 3000 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_exit().
void previrt::proto::ActionTree_Event::clear_has_handler () inline private
Definition at line 3022 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_handler(), release_handler(), and set_allocated_handler().
void previrt::proto::ActionTree_Event::clear_has_then () inline private
Definition at line 3117 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_then(), release_then(), and set_allocated_then().
void previrt::proto::ActionTree_Event::clear_then () inline
Definition at line 3120 of file Previrt.pb.h.
References clear_has_then(), and then_.
void previrt::proto::ActionTree_Event::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 4278 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::ActionTree_Event::CopyFrom (const ActionTree_Event & from)
Definition at line 4284 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const ActionTree_Event & previrt::proto::ActionTree_Event::default_instance () static
Definition at line 4024 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::ActionTree::InitAsDefaultInstance(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::ActionTree_Event::descriptor () static
Definition at line 4019 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Event_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
bool previrt::proto::ActionTree_Event::exit () const inline
Definition at line 3007 of file Previrt.pb.h.
References exit_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::ActionTree_Event::GetCachedSize () const inline
Definition at line 1414 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::ActionTree_Event::GetMetadata () const
Definition at line 4310 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Event_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Event_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
const ::std::string & previrt::proto::ActionTree_Event::handler () const inline
Definition at line 3031 of file Previrt.pb.h.
References handler_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_handler().
bool previrt::proto::ActionTree_Event::has_exit () const inline
Definition at line 2994 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::ActionTree_Event::has_handler () const inline
Definition at line 3016 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::ActionTree_Event::has_then () const inline
Definition at line 3111 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::ActionTree_Event::InitAsDefaultInstance () private
Definition at line 3983 of file Previrt.pb.cc.
References previrt::proto::ActionTree::default_instance(), and then_.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::ActionTree_Event::IsInitialized () const
Definition at line 4290 of file Previrt.pb.cc.
References has_then(), and then().
void previrt::proto::ActionTree_Event::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 4249 of file Previrt.pb.cc.
Referenced by ActionTree_Event(), and CopyFrom().
void previrt::proto::ActionTree_Event::MergeFrom (const ActionTree_Event & from)
Definition at line 4261 of file Previrt.pb.cc.
References _has_bits_, args_, exit(), handler(), has_exit(), has_handler(), has_then(), mutable_then(), mutable_unknown_fields(), set_exit(), set_handler(), then(), and unknown_fields().
bool previrt::proto::ActionTree_Event::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 4052 of file Previrt.pb.cc.
References DO_, exit_, mutable_args(), mutable_handler(), mutable_then(), mutable_unknown_fields(), and set_has_exit().
google::protobuf::RepeatedField<::google::protobuf::int32 > * previrt::proto::ActionTree_Event::mutable_args () inline
Definition at line 3106 of file Previrt.pb.h.
References args_.
Referenced by MergePartialFromCodedStream().
std::string * previrt::proto::ActionTree_Event::mutable_handler () inline
Definition at line 3055 of file Previrt.pb.h.
References handler_, and set_has_handler().
Referenced by MergePartialFromCodedStream().
previrt::proto::ActionTree * previrt::proto::ActionTree_Event::mutable_then () inline
Definition at line 3127 of file Previrt.pb.h.
References set_has_then(), and then_.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
inline ::google::protobuf::UnknownFieldSet* previrt::proto::ActionTree_Event::mutable_unknown_fields () inline
Definition at line 1389 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
ActionTree_Event * previrt::proto::ActionTree_Event::New () const
Definition at line 4031 of file Previrt.pb.cc.
References ActionTree_Event().
ActionTree_Event& previrt::proto::ActionTree_Event::operator= (const ActionTree_Event & from) inline
Definition at line 1380 of file Previrt.pb.h.
References CopyFrom().
std::string * previrt::proto::ActionTree_Event::release_handler () inline
Definition at line 3062 of file Previrt.pb.h.
References clear_has_handler(), and handler_.
previrt::proto::ActionTree * previrt::proto::ActionTree_Event::release_then () inline
Definition at line 3132 of file Previrt.pb.h.
References clear_has_then(), and then_.
void previrt::proto::ActionTree_Event::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 4139 of file Previrt.pb.cc.
References args(), args_size(), exit(), handler(), has_exit(), has_handler(), has_then(), then(), and unknown_fields().
google::protobuf::uint8 * previrt::proto::ActionTree_Event::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 4170 of file Previrt.pb.cc.
References args(), args_size(), exit(), handler(), has_exit(), has_handler(), has_then(), then(), and unknown_fields().
void previrt::proto::ActionTree_Event::set_allocated_handler (::std::string * handler) inline
Definition at line 3072 of file Previrt.pb.h.
References clear_has_handler(), handler(), handler_, and set_has_handler().
void previrt::proto::ActionTree_Event::set_allocated_then (::previrt::proto::ActionTree * then) inline
Definition at line 3138 of file Previrt.pb.h.
References clear_has_then(), set_has_then(), then(), and then_.
void previrt::proto::ActionTree_Event::set_args (int index, ::google::protobuf::int32 value) inline
Definition at line 3095 of file Previrt.pb.h.
References args_.
void previrt::proto::ActionTree_Event::set_exit (bool value) inline
Definition at line 3010 of file Previrt.pb.h.
References exit_, and set_has_exit().
Referenced by MergeFrom().
void previrt::proto::ActionTree_Event::set_handler (const ::std::string & value) inline
Definition at line 3034 of file Previrt.pb.h.
References handler_, and set_has_handler().
Referenced by MergeFrom().
void previrt::proto::ActionTree_Event::set_handler (const char * value) inline
Definition at line 3041 of file Previrt.pb.h.
References handler_, and set_has_handler().
void previrt::proto::ActionTree_Event::set_handler (const void * value, size_t size) inline
Definition at line 3048 of file Previrt.pb.h.
References handler_, and set_has_handler().
void previrt::proto::ActionTree_Event::set_has_exit () inline private
Definition at line 2997 of file Previrt.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_exit().
void previrt::proto::ActionTree_Event::set_has_handler () inline private
Definition at line 3019 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_handler(), set_allocated_handler(), and set_handler().
void previrt::proto::ActionTree_Event::set_has_then () inline private
Definition at line 3114 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_then(), and set_allocated_then().
void previrt::proto::ActionTree_Event::SetCachedSize (int size) const private
Definition at line 4014 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::ActionTree_Event::SharedCtor () private
Definition at line 3993 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, exit_, handler_, and then_.
Referenced by ActionTree_Event().
void previrt::proto::ActionTree_Event::SharedDtor () private
Definition at line 4005 of file Previrt.pb.cc.
References default_instance_, handler_, and then_.
Referenced by ~ActionTree_Event().
void previrt::proto::ActionTree_Event::Swap (ActionTree_Event * other)
Definition at line 4298 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, args_, exit_, handler_, and then_.
const ::previrt::proto::ActionTree & previrt::proto::ActionTree_Event::then () const inline
Definition at line 3124 of file Previrt.pb.h.
References default_instance_, and then_.
Referenced by ByteSize(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_then().
const ::google::protobuf::UnknownFieldSet& previrt::proto::ActionTree_Event::unknown_fields () const inline
Definition at line 1385 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::ActionTree_Event::_cached_size_ mutable private
Definition at line 1483 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::ActionTree_Event::_has_bits_[(4+31)/32] private
Definition at line 1484 of file Previrt.pb.h.
Referenced by ByteSize(), Clear(), clear_has_exit(), clear_has_handler(), clear_has_then(), has_exit(), has_handler(), has_then(), MergeFrom(), set_has_exit(), set_has_handler(), set_has_then(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::ActionTree_Event::_unknown_fields_ private
Definition at line 1476 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
::google::protobuf::RepeatedField< ::google::protobuf::int32 > previrt::proto::ActionTree_Event::args_ private
Definition at line 1479 of file Previrt.pb.h.
Referenced by add_args(), args(), args_size(), Clear(), clear_args(), MergeFrom(), mutable_args(), set_args(), and Swap().
ActionTree_Event * previrt::proto::ActionTree_Event::default_instance_ = NULL static private
Definition at line 1491 of file Previrt.pb.h.
Referenced by default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), SharedDtor(), and then().
bool previrt::proto::ActionTree_Event::exit_ private
Definition at line 1481 of file Previrt.pb.h.
Referenced by Clear(), clear_exit(), exit(), MergePartialFromCodedStream(), set_exit(), SharedCtor(), and Swap().
::std::string* previrt::proto::ActionTree_Event::handler_ private
Definition at line 1478 of file Previrt.pb.h.
Referenced by Clear(), clear_handler(), handler(), mutable_handler(), release_handler(), set_allocated_handler(), set_handler(), SharedCtor(), SharedDtor(), and Swap().
const int previrt::proto::ActionTree_Event::kArgsFieldNumber = 33 static
Definition at line 1449 of file Previrt.pb.h.
const int previrt::proto::ActionTree_Event::kExitFieldNumber = 31 static
Definition at line 1430 of file Previrt.pb.h.
const int previrt::proto::ActionTree_Event::kHandlerFieldNumber = 32 static
Definition at line 1437 of file Previrt.pb.h.
const int previrt::proto::ActionTree_Event::kThenFieldNumber = 39 static
Definition at line 1461 of file Previrt.pb.h.
::previrt::proto::ActionTree* previrt::proto::ActionTree_Event::then_ private
Definition at line 1480 of file Previrt.pb.h.
Referenced by Clear(), clear_then(), InitAsDefaultInstance(), mutable_then(), release_then(), set_allocated_then(), SharedCtor(), SharedDtor(), Swap(), and then().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc