Occam - Application Specialization: previrt::proto::PrevirtType_Vec Class Reference
previrt::proto::PrevirtType_Vec Class Reference
#include <Previrt.pb.h>
Public Member Functions
PrevirtType_Vec ()
virtual ~PrevirtType_Vec ()
PrevirtType_Vec (const PrevirtType_Vec &from)
PrevirtType_Vec & operator= (const PrevirtType_Vec &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (PrevirtType_Vec *other)
PrevirtType_Vec * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const PrevirtType_Vec &from)
void MergeFrom (const PrevirtType_Vec &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
int elems_size () const
void clear_elems ()
const
::previrt::proto::PrevirtType & elems (int index) const
inline::previrt::proto::PrevirtType * mutable_elems (int index)
inline::previrt::proto::PrevirtType * add_elems ()
const
::google::protobuf::RepeatedPtrField
< ::previrt::proto::PrevirtType > & elems () const
inline::google::protobuf::RepeatedPtrField
< ::previrt::proto::PrevirtType > * mutable_elems ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const PrevirtType_Vec & default_instance ()
Static Public Attributes
static const int kElemsFieldNumber = 21
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::RepeatedPtrField
< ::previrt::proto::PrevirtType > elems_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(1+31)/32]
Static Private Attributes
static PrevirtType_Vec * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 223 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::PrevirtType_Vec::PrevirtType_Vec ()
Definition at line 860 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::PrevirtType_Vec::~PrevirtType_Vec () virtual
Definition at line 879 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::PrevirtType_Vec::PrevirtType_Vec (const PrevirtType_Vec & from)
Definition at line 868 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
previrt::proto::PrevirtType * previrt::proto::PrevirtType_Vec::add_elems () inline
Definition at line 1917 of file Previrt.pb.h.
References elems_.
Referenced by MergePartialFromCodedStream().
int previrt::proto::PrevirtType_Vec::ByteSize () const
Definition at line 982 of file Previrt.pb.cc.
References _cached_size_, elems(), elems_size(), and unknown_fields().
void previrt::proto::PrevirtType_Vec::Clear ()
Definition at line 909 of file Previrt.pb.cc.
References _has_bits_, elems_, and mutable_unknown_fields().
Referenced by CopyFrom().
void previrt::proto::PrevirtType_Vec::clear_elems () inline
Definition at line 1908 of file Previrt.pb.h.
References elems_.
void previrt::proto::PrevirtType_Vec::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1022 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::PrevirtType_Vec::CopyFrom (const PrevirtType_Vec & from)
Definition at line 1028 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const PrevirtType_Vec & previrt::proto::PrevirtType_Vec::default_instance () static
Definition at line 898 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::PrevirtType::InitAsDefaultInstance(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::PrevirtType_Vec::descriptor () static
Definition at line 893 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Vec_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
const ::previrt::proto::PrevirtType & previrt::proto::PrevirtType_Vec::elems (int index) const inline
Definition at line 1911 of file Previrt.pb.h.
References elems_.
const ::google::protobuf::RepeatedPtrField<::previrt::proto::PrevirtType > & previrt::proto::PrevirtType_Vec::elems () const inline
Definition at line 1921 of file Previrt.pb.h.
References elems_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::PrevirtType_Vec::elems_size () const inline
Definition at line 1905 of file Previrt.pb.h.
References elems_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::PrevirtType_Vec::GetCachedSize () const inline
Definition at line 264 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::PrevirtType_Vec::GetMetadata () const
Definition at line 1051 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Vec_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Vec_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
void previrt::proto::PrevirtType_Vec::InitAsDefaultInstance () private
Definition at line 865 of file Previrt.pb.cc.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::PrevirtType_Vec::IsInitialized () const
Definition at line 1034 of file Previrt.pb.cc.
References elems(), and elems_size().
void previrt::proto::PrevirtType_Vec::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 1004 of file Previrt.pb.cc.
Referenced by CopyFrom(), and PrevirtType_Vec().
void previrt::proto::PrevirtType_Vec::MergeFrom (const PrevirtType_Vec & from)
Definition at line 1016 of file Previrt.pb.cc.
References elems_, mutable_unknown_fields(), and unknown_fields().
bool previrt::proto::PrevirtType_Vec::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 915 of file Previrt.pb.cc.
References add_elems(), DO_, and mutable_unknown_fields().
previrt::proto::PrevirtType * previrt::proto::PrevirtType_Vec::mutable_elems (int index) inline
Definition at line 1914 of file Previrt.pb.h.
References elems_.
google::protobuf::RepeatedPtrField<::previrt::proto::PrevirtType > * previrt::proto::PrevirtType_Vec::mutable_elems () inline
Definition at line 1925 of file Previrt.pb.h.
References elems_.
inline ::google::protobuf::UnknownFieldSet* previrt::proto::PrevirtType_Vec::mutable_unknown_fields () inline
Definition at line 239 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
PrevirtType_Vec * previrt::proto::PrevirtType_Vec::New () const
Definition at line 905 of file Previrt.pb.cc.
References PrevirtType_Vec().
PrevirtType_Vec& previrt::proto::PrevirtType_Vec::operator= (const PrevirtType_Vec & from) inline
Definition at line 230 of file Previrt.pb.h.
References CopyFrom().
void previrt::proto::PrevirtType_Vec::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 952 of file Previrt.pb.cc.
References elems(), elems_size(), and unknown_fields().
google::protobuf::uint8 * previrt::proto::PrevirtType_Vec::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 966 of file Previrt.pb.cc.
References elems(), elems_size(), and unknown_fields().
void previrt::proto::PrevirtType_Vec::SetCachedSize (int size) const private
Definition at line 888 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::PrevirtType_Vec::SharedCtor () private
Definition at line 874 of file Previrt.pb.cc.
References _cached_size_, and _has_bits_.
Referenced by PrevirtType_Vec().
void previrt::proto::PrevirtType_Vec::SharedDtor () private
Definition at line 883 of file Previrt.pb.cc.
References default_instance_.
Referenced by ~PrevirtType_Vec().
void previrt::proto::PrevirtType_Vec::Swap (PrevirtType_Vec * other)
Definition at line 1042 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, and elems_.
const ::google::protobuf::UnknownFieldSet& previrt::proto::PrevirtType_Vec::unknown_fields () const inline
Definition at line 235 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::PrevirtType_Vec::_cached_size_ mutable private
Definition at line 296 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::PrevirtType_Vec::_has_bits_[(1+31)/32] private
Definition at line 297 of file Previrt.pb.h.
Referenced by Clear(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::PrevirtType_Vec::_unknown_fields_ private
Definition at line 292 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
PrevirtType_Vec * previrt::proto::PrevirtType_Vec::default_instance_ = NULL static private
Definition at line 304 of file Previrt.pb.h.
Referenced by default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
::google::protobuf::RepeatedPtrField< ::previrt::proto::PrevirtType > previrt::proto::PrevirtType_Vec::elems_ private
Definition at line 294 of file Previrt.pb.h.
Referenced by add_elems(), Clear(), clear_elems(), elems(), elems_size(), MergeFrom(), mutable_elems(), and Swap().
const int previrt::proto::PrevirtType_Vec::kElemsFieldNumber = 21 static
Definition at line 280 of file Previrt.pb.h.
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc