Occam - Application Specialization: previrt::proto::EnforceInterface_Functions Class Reference
previrt::proto::EnforceInterface_Functions Class Reference
#include <Previrt.pb.h>
Public Member Functions
EnforceInterface_Functions ()
virtual ~EnforceInterface_Functions ()
EnforceInterface_Functions (const EnforceInterface_Functions &from)
EnforceInterface_Functions & operator= (const EnforceInterface_Functions &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (EnforceInterface_Functions *other)
EnforceInterface_Functions * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const EnforceInterface_Functions &from)
void MergeFrom (const EnforceInterface_Functions &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_name () const
void clear_name ()
const ::std::string & name () const
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const void *value, size_t size)
inline::std::string * mutable_name ()
inline::std::string * release_name ()
void set_allocated_name (::std::string *name)
bool has_actions () const
void clear_actions ()
const
::previrt::proto::ActionTree & actions () const
inline::previrt::proto::ActionTree * mutable_actions ()
inline::previrt::proto::ActionTree * release_actions ()
void set_allocated_actions (::previrt::proto::ActionTree *actions)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const
EnforceInterface_Functions & default_instance ()
Static Public Attributes
static const int kNameFieldNumber = 2
static const int kActionsFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_name ()
void clear_has_name ()
void set_has_actions ()
void clear_has_actions ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::std::string * name_
::previrt::proto::ActionTree * actions_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(2+31)/32]
Static Private Attributes
static EnforceInterface_Functions * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 1617 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::EnforceInterface_Functions::EnforceInterface_Functions ()
Definition at line 4682 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::EnforceInterface_Functions::~EnforceInterface_Functions () virtual
Definition at line 4704 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::EnforceInterface_Functions::EnforceInterface_Functions (const EnforceInterface_Functions & from)
Definition at line 4691 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
const ::previrt::proto::ActionTree & previrt::proto::EnforceInterface_Functions::actions () const inline
Definition at line 3377 of file Previrt.pb.h.
References actions_, and default_instance_.
Referenced by ByteSize(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_actions().
int previrt::proto::EnforceInterface_Functions::ByteSize () const
Definition at line 4845 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, actions(), has_actions(), has_name(), name(), and unknown_fields().
void previrt::proto::EnforceInterface_Functions::Clear ()
Definition at line 4738 of file Previrt.pb.cc.
References _has_bits_, actions_, has_actions(), has_name(), mutable_unknown_fields(), and name_.
Referenced by CopyFrom().
void previrt::proto::EnforceInterface_Functions::clear_actions () inline
Definition at line 3373 of file Previrt.pb.h.
References actions_, and clear_has_actions().
void previrt::proto::EnforceInterface_Functions::clear_has_actions () inline private
Definition at line 3370 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_actions(), release_actions(), and set_allocated_actions().
void previrt::proto::EnforceInterface_Functions::clear_has_name () inline private
Definition at line 3300 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_name(), release_name(), and set_allocated_name().
void previrt::proto::EnforceInterface_Functions::clear_name () inline
Definition at line 3303 of file Previrt.pb.h.
References clear_has_name(), and name_.
void previrt::proto::EnforceInterface_Functions::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 4900 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::EnforceInterface_Functions::CopyFrom (const EnforceInterface_Functions & from)
Definition at line 4906 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const EnforceInterface_Functions & previrt::proto::EnforceInterface_Functions::default_instance () static
Definition at line 4727 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::EnforceInterface_Functions::descriptor () static
Definition at line 4722 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::EnforceInterface_Functions_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
int previrt::proto::EnforceInterface_Functions::GetCachedSize () const inline
Definition at line 1658 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::EnforceInterface_Functions::GetMetadata () const
Definition at line 4931 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::EnforceInterface_Functions_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::EnforceInterface_Functions_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
bool previrt::proto::EnforceInterface_Functions::has_actions () const inline
Definition at line 3364 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::EnforceInterface_Functions::has_name () const inline
Definition at line 3294 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::EnforceInterface_Functions::InitAsDefaultInstance () private
Definition at line 4687 of file Previrt.pb.cc.
References actions_, and previrt::proto::ActionTree::default_instance().
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::EnforceInterface_Functions::IsInitialized () const
Definition at line 4912 of file Previrt.pb.cc.
References _has_bits_, actions(), and has_actions().
void previrt::proto::EnforceInterface_Functions::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 4875 of file Previrt.pb.cc.
Referenced by CopyFrom(), and EnforceInterface_Functions().
void previrt::proto::EnforceInterface_Functions::MergeFrom (const EnforceInterface_Functions & from)
Definition at line 4887 of file Previrt.pb.cc.
References _has_bits_, actions(), has_actions(), has_name(), mutable_actions(), mutable_unknown_fields(), name(), set_name(), and unknown_fields().
bool previrt::proto::EnforceInterface_Functions::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 4753 of file Previrt.pb.cc.
References DO_, mutable_actions(), mutable_name(), and mutable_unknown_fields().
previrt::proto::ActionTree * previrt::proto::EnforceInterface_Functions::mutable_actions () inline
Definition at line 3381 of file Previrt.pb.h.
References actions_, and set_has_actions().
Referenced by MergeFrom(), and MergePartialFromCodedStream().
std::string * previrt::proto::EnforceInterface_Functions::mutable_name () inline
Definition at line 3333 of file Previrt.pb.h.
References name_, and set_has_name().
Referenced by MergePartialFromCodedStream().
inline ::google::protobuf::UnknownFieldSet* previrt::proto::EnforceInterface_Functions::mutable_unknown_fields () inline
Definition at line 1633 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
const ::std::string & previrt::proto::EnforceInterface_Functions::name () const inline
Definition at line 3309 of file Previrt.pb.h.
References name_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_name().
EnforceInterface_Functions * previrt::proto::EnforceInterface_Functions::New () const
Definition at line 4734 of file Previrt.pb.cc.
References EnforceInterface_Functions().
EnforceInterface_Functions& previrt::proto::EnforceInterface_Functions::operator= (const EnforceInterface_Functions & from) inline
Definition at line 1624 of file Previrt.pb.h.
References CopyFrom().
previrt::proto::ActionTree * previrt::proto::EnforceInterface_Functions::release_actions () inline
Definition at line 3388 of file Previrt.pb.h.
References actions_, and clear_has_actions().
std::string * previrt::proto::EnforceInterface_Functions::release_name () inline
Definition at line 3340 of file Previrt.pb.h.
References clear_has_name(), and name_.
void previrt::proto::EnforceInterface_Functions::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 4802 of file Previrt.pb.cc.
References actions(), has_actions(), has_name(), name(), and unknown_fields().
google::protobuf::uint8 * previrt::proto::EnforceInterface_Functions::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 4822 of file Previrt.pb.cc.
References actions(), has_actions(), has_name(), name(), and unknown_fields().
void previrt::proto::EnforceInterface_Functions::set_allocated_actions (::previrt::proto::ActionTree * actions) inline
Definition at line 3396 of file Previrt.pb.h.
References actions(), actions_, clear_has_actions(), and set_has_actions().
void previrt::proto::EnforceInterface_Functions::set_allocated_name (::std::string * name) inline
Definition at line 3350 of file Previrt.pb.h.
References clear_has_name(), name(), name_, and set_has_name().
void previrt::proto::EnforceInterface_Functions::set_has_actions () inline private
Definition at line 3367 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_actions(), and set_allocated_actions().
void previrt::proto::EnforceInterface_Functions::set_has_name () inline private
Definition at line 3297 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_name(), set_allocated_name(), and set_name().
void previrt::proto::EnforceInterface_Functions::set_name (const ::std::string & value) inline
Definition at line 3312 of file Previrt.pb.h.
References name_, and set_has_name().
Referenced by MergeFrom().
void previrt::proto::EnforceInterface_Functions::set_name (const char * value) inline
Definition at line 3319 of file Previrt.pb.h.
References name_, and set_has_name().
void previrt::proto::EnforceInterface_Functions::set_name (const void * value, size_t size) inline
Definition at line 3326 of file Previrt.pb.h.
References name_, and set_has_name().
void previrt::proto::EnforceInterface_Functions::SetCachedSize (int size) const private
Definition at line 4717 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::EnforceInterface_Functions::SharedCtor () private
Definition at line 4697 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, actions_, and name_.
Referenced by EnforceInterface_Functions().
void previrt::proto::EnforceInterface_Functions::SharedDtor () private
Definition at line 4708 of file Previrt.pb.cc.
References actions_, default_instance_, and name_.
Referenced by ~EnforceInterface_Functions().
void previrt::proto::EnforceInterface_Functions::Swap (EnforceInterface_Functions * other)
Definition at line 4921 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, actions_, and name_.
const ::google::protobuf::UnknownFieldSet& previrt::proto::EnforceInterface_Functions::unknown_fields () const inline
Definition at line 1629 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::EnforceInterface_Functions::_cached_size_ mutable private
Definition at line 1704 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::EnforceInterface_Functions::_has_bits_[(2+31)/32] private
Definition at line 1705 of file Previrt.pb.h.
Referenced by ByteSize(), Clear(), clear_has_actions(), clear_has_name(), has_actions(), has_name(), IsInitialized(), MergeFrom(), set_has_actions(), set_has_name(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::EnforceInterface_Functions::_unknown_fields_ private
Definition at line 1699 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
::previrt::proto::ActionTree* previrt::proto::EnforceInterface_Functions::actions_ private
Definition at line 1702 of file Previrt.pb.h.
Referenced by actions(), Clear(), clear_actions(), InitAsDefaultInstance(), mutable_actions(), release_actions(), set_allocated_actions(), SharedCtor(), SharedDtor(), and Swap().
EnforceInterface_Functions * previrt::proto::EnforceInterface_Functions::default_instance_ = NULL static private
Definition at line 1712 of file Previrt.pb.h.
Referenced by actions(), default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
const int previrt::proto::EnforceInterface_Functions::kActionsFieldNumber = 3 static
Definition at line 1686 of file Previrt.pb.h.
const int previrt::proto::EnforceInterface_Functions::kNameFieldNumber = 2 static
Definition at line 1674 of file Previrt.pb.h.
::std::string* previrt::proto::EnforceInterface_Functions::name_ private
Definition at line 1701 of file Previrt.pb.h.
Referenced by Clear(), clear_name(), mutable_name(), name(), release_name(), set_allocated_name(), set_name(), SharedCtor(), SharedDtor(), and Swap().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc