Occam - Application Specialization: previrt::proto::CallInfo Class Reference
previrt::proto::CallInfo Class Reference
#include <Previrt.pb.h>
Public Member Functions
CallInfo ()
virtual ~CallInfo ()
CallInfo (const CallInfo &from)
CallInfo & operator= (const CallInfo &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (CallInfo *other)
CallInfo * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const CallInfo &from)
void MergeFrom (const CallInfo &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_name () const
void clear_name ()
const ::std::string & name () const
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const void *value, size_t size)
inline::std::string * mutable_name ()
inline::std::string * release_name ()
void set_allocated_name (::std::string *name)
bool has_count () const
void clear_count ()
inline::google::protobuf::uint32 count () const
void set_count (::google::protobuf::uint32 value)
int args_size () const
void clear_args ()
const
::previrt::proto::PrevirtType & args (int index) const
inline::previrt::proto::PrevirtType * mutable_args (int index)
inline::previrt::proto::PrevirtType * add_args ()
const
::google::protobuf::RepeatedPtrField
< ::previrt::proto::PrevirtType > & args () const
inline::google::protobuf::RepeatedPtrField
< ::previrt::proto::PrevirtType > * mutable_args ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const CallInfo & default_instance ()
Static Public Attributes
static const int kNameFieldNumber = 1
static const int kCountFieldNumber = 2
static const int kArgsFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_name ()
void clear_has_name ()
void set_has_count ()
void clear_has_count ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::std::string * name_
::google::protobuf::RepeatedPtrField
< ::previrt::proto::PrevirtType > args_
::google::protobuf::uint32 count_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(3+31)/32]
Static Private Attributes
static CallInfo * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 747 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::CallInfo::CallInfo ()
Definition at line 2301 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::CallInfo::~CallInfo () virtual
Definition at line 2322 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::CallInfo::CallInfo (const CallInfo & from)
Definition at line 2309 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
previrt::proto::PrevirtType * previrt::proto::CallInfo::add_args () inline
Definition at line 2544 of file Previrt.pb.h.
References args_.
Referenced by MergePartialFromCodedStream().
const ::previrt::proto::PrevirtType & previrt::proto::CallInfo::args (int index) const inline
Definition at line 2538 of file Previrt.pb.h.
References args_.
const ::google::protobuf::RepeatedPtrField<::previrt::proto::PrevirtType > & previrt::proto::CallInfo::args () const inline
Definition at line 2548 of file Previrt.pb.h.
References args_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::CallInfo::args_size () const inline
Definition at line 2532 of file Previrt.pb.h.
References args_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::CallInfo::ByteSize () const
Definition at line 2488 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, args(), args_size(), count(), has_count(), has_name(), name(), and unknown_fields().
void previrt::proto::CallInfo::Clear ()
Definition at line 2355 of file Previrt.pb.cc.
References _has_bits_, args_, count_, has_name(), mutable_unknown_fields(), and name_.
Referenced by CopyFrom().
void previrt::proto::CallInfo::clear_args () inline
Definition at line 2535 of file Previrt.pb.h.
References args_.
void previrt::proto::CallInfo::clear_count () inline
Definition at line 2519 of file Previrt.pb.h.
References clear_has_count(), and count_.
void previrt::proto::CallInfo::clear_has_count () inline private
Definition at line 2516 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_count().
void previrt::proto::CallInfo::clear_has_name () inline private
Definition at line 2446 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_name(), release_name(), and set_allocated_name().
void previrt::proto::CallInfo::clear_name () inline
Definition at line 2449 of file Previrt.pb.h.
References clear_has_name(), and name_.
void previrt::proto::CallInfo::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 2552 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::CallInfo::CopyFrom (const CallInfo & from)
Definition at line 2558 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
google::protobuf::uint32 previrt::proto::CallInfo::count () const inline
Definition at line 2523 of file Previrt.pb.h.
References count_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
const CallInfo & previrt::proto::CallInfo::default_instance () static
Definition at line 2344 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::CallRewrite::InitAsDefaultInstance(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::CallInfo::descriptor () static
Definition at line 2339 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::CallInfo_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
int previrt::proto::CallInfo::GetCachedSize () const inline
Definition at line 788 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::CallInfo::GetMetadata () const
Definition at line 2584 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::CallInfo_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::CallInfo_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
bool previrt::proto::CallInfo::has_count () const inline
Definition at line 2510 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::CallInfo::has_name () const inline
Definition at line 2440 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::CallInfo::InitAsDefaultInstance () private
Definition at line 2306 of file Previrt.pb.cc.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::CallInfo::IsInitialized () const
Definition at line 2564 of file Previrt.pb.cc.
References _has_bits_, args(), and args_size().
void previrt::proto::CallInfo::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 2526 of file Previrt.pb.cc.
Referenced by CallInfo(), and CopyFrom().
void previrt::proto::CallInfo::MergeFrom (const CallInfo & from)
Definition at line 2538 of file Previrt.pb.cc.
References _has_bits_, args_, count(), has_count(), has_name(), mutable_unknown_fields(), name(), set_count(), set_name(), and unknown_fields().
bool previrt::proto::CallInfo::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 2369 of file Previrt.pb.cc.
References add_args(), count_, DO_, mutable_name(), mutable_unknown_fields(), and set_has_count().
previrt::proto::PrevirtType * previrt::proto::CallInfo::mutable_args (int index) inline
Definition at line 2541 of file Previrt.pb.h.
References args_.
google::protobuf::RepeatedPtrField<::previrt::proto::PrevirtType > * previrt::proto::CallInfo::mutable_args () inline
Definition at line 2552 of file Previrt.pb.h.
References args_.
std::string * previrt::proto::CallInfo::mutable_name () inline
Definition at line 2479 of file Previrt.pb.h.
References name_, and set_has_name().
Referenced by MergePartialFromCodedStream().
inline ::google::protobuf::UnknownFieldSet* previrt::proto::CallInfo::mutable_unknown_fields () inline
Definition at line 763 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
const ::std::string & previrt::proto::CallInfo::name () const inline
Definition at line 2455 of file Previrt.pb.h.
References name_.
Referenced by ByteSize(), previrt::codeInto< proto::ComponentInterface, ComponentInterface >(), previrt::codeInto< proto::ComponentInterfaceTransform, ComponentInterfaceTransform >(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_name().
CallInfo * previrt::proto::CallInfo::New () const
Definition at line 2351 of file Previrt.pb.cc.
References CallInfo().
CallInfo& previrt::proto::CallInfo::operator= (const CallInfo & from) inline
Definition at line 754 of file Previrt.pb.h.
References CopyFrom().
std::string * previrt::proto::CallInfo::release_name () inline
Definition at line 2486 of file Previrt.pb.h.
References clear_has_name(), and name_.
void previrt::proto::CallInfo::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 2435 of file Previrt.pb.cc.
References args(), args_size(), count(), has_count(), has_name(), name(), and unknown_fields().
google::protobuf::uint8 * previrt::proto::CallInfo::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 2460 of file Previrt.pb.cc.
References args(), args_size(), count(), has_count(), has_name(), name(), and unknown_fields().
void previrt::proto::CallInfo::set_allocated_name (::std::string * name) inline
Definition at line 2496 of file Previrt.pb.h.
References clear_has_name(), name(), name_, and set_has_name().
void previrt::proto::CallInfo::set_count (::google::protobuf::uint32 value) inline
Definition at line 2526 of file Previrt.pb.h.
References count_, and set_has_count().
Referenced by MergeFrom().
void previrt::proto::CallInfo::set_has_count () inline private
Definition at line 2513 of file Previrt.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_count().
void previrt::proto::CallInfo::set_has_name () inline private
Definition at line 2443 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_name(), set_allocated_name(), and set_name().
void previrt::proto::CallInfo::set_name (const ::std::string & value) inline
Definition at line 2458 of file Previrt.pb.h.
References name_, and set_has_name().
Referenced by previrt::codeInto< ComponentInterface, proto::ComponentInterface >(), and MergeFrom().
void previrt::proto::CallInfo::set_name (const char * value) inline
Definition at line 2465 of file Previrt.pb.h.
References name_, and set_has_name().
void previrt::proto::CallInfo::set_name (const void * value, size_t size) inline
Definition at line 2472 of file Previrt.pb.h.
References name_, and set_has_name().
void previrt::proto::CallInfo::SetCachedSize (int size) const private
Definition at line 2334 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::CallInfo::SharedCtor () private
Definition at line 2315 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, count_, and name_.
Referenced by CallInfo().
void previrt::proto::CallInfo::SharedDtor () private
Definition at line 2326 of file Previrt.pb.cc.
References default_instance_, and name_.
Referenced by ~CallInfo().
void previrt::proto::CallInfo::Swap (CallInfo * other)
Definition at line 2573 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, args_, count_, and name_.
const ::google::protobuf::UnknownFieldSet& previrt::proto::CallInfo::unknown_fields () const inline
Definition at line 759 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::CallInfo::_cached_size_ mutable private
Definition at line 845 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::CallInfo::_has_bits_[(3+31)/32] private
Definition at line 846 of file Previrt.pb.h.
Referenced by ByteSize(), Clear(), clear_has_count(), clear_has_name(), has_count(), has_name(), IsInitialized(), MergeFrom(), set_has_count(), set_has_name(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::CallInfo::_unknown_fields_ private
Definition at line 839 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
::google::protobuf::RepeatedPtrField< ::previrt::proto::PrevirtType > previrt::proto::CallInfo::args_ private
Definition at line 842 of file Previrt.pb.h.
Referenced by add_args(), args(), args_size(), Clear(), clear_args(), MergeFrom(), mutable_args(), and Swap().
::google::protobuf::uint32 previrt::proto::CallInfo::count_ private
Definition at line 843 of file Previrt.pb.h.
Referenced by Clear(), clear_count(), count(), MergePartialFromCodedStream(), set_count(), SharedCtor(), and Swap().
CallInfo * previrt::proto::CallInfo::default_instance_ = NULL static private
Definition at line 853 of file Previrt.pb.h.
Referenced by default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
const int previrt::proto::CallInfo::kArgsFieldNumber = 3 static
Definition at line 823 of file Previrt.pb.h.
const int previrt::proto::CallInfo::kCountFieldNumber = 2 static
Definition at line 816 of file Previrt.pb.h.
const int previrt::proto::CallInfo::kNameFieldNumber = 1 static
Definition at line 804 of file Previrt.pb.h.
::std::string* previrt::proto::CallInfo::name_ private
Definition at line 841 of file Previrt.pb.h.
Referenced by Clear(), clear_name(), mutable_name(), name(), release_name(), set_allocated_name(), set_name(), SharedCtor(), SharedDtor(), and Swap().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc