Occam - Application Specialization: previrt::proto::PrevirtType_Float Class Reference
previrt::proto::PrevirtType_Float Class Reference
#include <Previrt.pb.h>
Public Member Functions
PrevirtType_Float ()
virtual ~PrevirtType_Float ()
PrevirtType_Float (const PrevirtType_Float &from)
PrevirtType_Float & operator= (const PrevirtType_Float &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (PrevirtType_Float *other)
PrevirtType_Float * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const PrevirtType_Float &from)
void MergeFrom (const PrevirtType_Float &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_sem () const
void clear_sem ()
inline::previrt::proto::FloatSemantics sem () const
void set_sem (::previrt::proto::FloatSemantics value)
bool has_data () const
void clear_data ()
const ::std::string & data () const
void set_data (const ::std::string &value)
void set_data (const char *value)
void set_data (const char *value, size_t size)
inline::std::string * mutable_data ()
inline::std::string * release_data ()
void set_allocated_data (::std::string *data)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const PrevirtType_Float & default_instance ()
Static Public Attributes
static const int kSemFieldNumber = 41
static const int kDataFieldNumber = 42
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_sem ()
void clear_has_sem ()
void set_has_data ()
void clear_has_data ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::std::string * data_
int sem_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(2+31)/32]
Static Private Attributes
static PrevirtType_Float * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 405 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::PrevirtType_Float::PrevirtType_Float ()
Definition at line 1321 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::PrevirtType_Float::~PrevirtType_Float () virtual
Definition at line 1342 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::PrevirtType_Float::PrevirtType_Float (const PrevirtType_Float & from)
Definition at line 1329 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
int previrt::proto::PrevirtType_Float::ByteSize () const
Definition at line 1495 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, data(), has_data(), has_sem(), sem(), and unknown_fields().
void previrt::proto::PrevirtType_Float::Clear ()
Definition at line 1375 of file Previrt.pb.cc.
References _has_bits_, data_, has_data(), mutable_unknown_fields(), and sem_.
Referenced by CopyFrom().
void previrt::proto::PrevirtType_Float::clear_data () inline
Definition at line 2062 of file Previrt.pb.h.
References clear_has_data(), and data_.
void previrt::proto::PrevirtType_Float::clear_has_data () inline private
Definition at line 2059 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_data(), release_data(), and set_allocated_data().
void previrt::proto::PrevirtType_Float::clear_has_sem () inline private
Definition at line 2036 of file Previrt.pb.h.
References _has_bits_.
Referenced by clear_sem().
void previrt::proto::PrevirtType_Float::clear_sem () inline
Definition at line 2039 of file Previrt.pb.h.
References clear_has_sem(), and sem_.
void previrt::proto::PrevirtType_Float::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1549 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::PrevirtType_Float::CopyFrom (const PrevirtType_Float & from)
Definition at line 1555 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const ::std::string & previrt::proto::PrevirtType_Float::data () const inline
Definition at line 2068 of file Previrt.pb.h.
References data_.
Referenced by ByteSize(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_data().
const PrevirtType_Float & previrt::proto::PrevirtType_Float::default_instance () static
Definition at line 1364 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::PrevirtType::InitAsDefaultInstance(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::PrevirtType_Float::descriptor () static
Definition at line 1359 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Float_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
int previrt::proto::PrevirtType_Float::GetCachedSize () const inline
Definition at line 446 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::PrevirtType_Float::GetMetadata () const
Definition at line 1577 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Float_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Float_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
bool previrt::proto::PrevirtType_Float::has_data () const inline
Definition at line 2053 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
bool previrt::proto::PrevirtType_Float::has_sem () const inline
Definition at line 2030 of file Previrt.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::PrevirtType_Float::InitAsDefaultInstance () private
Definition at line 1326 of file Previrt.pb.cc.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::PrevirtType_Float::IsInitialized () const
Definition at line 1561 of file Previrt.pb.cc.
References _has_bits_.
void previrt::proto::PrevirtType_Float::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 1524 of file Previrt.pb.cc.
Referenced by CopyFrom(), and PrevirtType_Float().
void previrt::proto::PrevirtType_Float::MergeFrom (const PrevirtType_Float & from)
Definition at line 1536 of file Previrt.pb.cc.
References _has_bits_, data(), has_data(), has_sem(), mutable_unknown_fields(), sem(), set_data(), set_sem(), and unknown_fields().
bool previrt::proto::PrevirtType_Float::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 1388 of file Previrt.pb.cc.
References data(), DO_, previrt::proto::FloatSemantics_IsValid(), mutable_data(), mutable_unknown_fields(), and set_sem().
std::string * previrt::proto::PrevirtType_Float::mutable_data () inline
Definition at line 2092 of file Previrt.pb.h.
References data_, and set_has_data().
Referenced by MergePartialFromCodedStream().
inline ::google::protobuf::UnknownFieldSet* previrt::proto::PrevirtType_Float::mutable_unknown_fields () inline
Definition at line 421 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
PrevirtType_Float * previrt::proto::PrevirtType_Float::New () const
Definition at line 1371 of file Previrt.pb.cc.
References PrevirtType_Float().
PrevirtType_Float& previrt::proto::PrevirtType_Float::operator= (const PrevirtType_Float & from) inline
Definition at line 412 of file Previrt.pb.h.
References CopyFrom().
std::string * previrt::proto::PrevirtType_Float::release_data () inline
Definition at line 2099 of file Previrt.pb.h.
References clear_has_data(), and data_.
previrt::proto::FloatSemantics previrt::proto::PrevirtType_Float::sem () const inline
Definition at line 2043 of file Previrt.pb.h.
References sem_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::PrevirtType_Float::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 1447 of file Previrt.pb.cc.
References data(), has_data(), has_sem(), sem(), and unknown_fields().
google::protobuf::uint8 * previrt::proto::PrevirtType_Float::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 1470 of file Previrt.pb.cc.
References data(), has_data(), has_sem(), sem(), and unknown_fields().
void previrt::proto::PrevirtType_Float::set_allocated_data (::std::string * data) inline
Definition at line 2109 of file Previrt.pb.h.
References clear_has_data(), data(), data_, and set_has_data().
void previrt::proto::PrevirtType_Float::set_data (const ::std::string & value) inline
Definition at line 2071 of file Previrt.pb.h.
References data_, and set_has_data().
Referenced by MergeFrom().
void previrt::proto::PrevirtType_Float::set_data (const char * value) inline
Definition at line 2078 of file Previrt.pb.h.
References data_, and set_has_data().
void previrt::proto::PrevirtType_Float::set_data (const char * value, size_t size) inline
Definition at line 2085 of file Previrt.pb.h.
References data_, and set_has_data().
void previrt::proto::PrevirtType_Float::set_has_data () inline private
Definition at line 2056 of file Previrt.pb.h.
References _has_bits_.
Referenced by mutable_data(), set_allocated_data(), and set_data().
void previrt::proto::PrevirtType_Float::set_has_sem () inline private
Definition at line 2033 of file Previrt.pb.h.
References _has_bits_.
Referenced by set_sem().
void previrt::proto::PrevirtType_Float::set_sem (::previrt::proto::FloatSemantics value) inline
Definition at line 2046 of file Previrt.pb.h.
References previrt::proto::FloatSemantics_IsValid(), sem_, and set_has_sem().
Referenced by MergeFrom(), and MergePartialFromCodedStream().
void previrt::proto::PrevirtType_Float::SetCachedSize (int size) const private
Definition at line 1354 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::PrevirtType_Float::SharedCtor () private
Definition at line 1335 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, data_, and sem_.
Referenced by PrevirtType_Float().
void previrt::proto::PrevirtType_Float::SharedDtor () private
Definition at line 1346 of file Previrt.pb.cc.
References data_, and default_instance_.
Referenced by ~PrevirtType_Float().
void previrt::proto::PrevirtType_Float::Swap (PrevirtType_Float * other)
Definition at line 1567 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, data_, and sem_.
const ::google::protobuf::UnknownFieldSet& previrt::proto::PrevirtType_Float::unknown_fields () const inline
Definition at line 417 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::PrevirtType_Float::_cached_size_ mutable private
Definition at line 490 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::PrevirtType_Float::_has_bits_[(2+31)/32] private
Definition at line 491 of file Previrt.pb.h.
Referenced by ByteSize(), Clear(), clear_has_data(), clear_has_sem(), has_data(), has_sem(), IsInitialized(), MergeFrom(), set_has_data(), set_has_sem(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::PrevirtType_Float::_unknown_fields_ private
Definition at line 485 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
::std::string* previrt::proto::PrevirtType_Float::data_ private
Definition at line 487 of file Previrt.pb.h.
Referenced by Clear(), clear_data(), data(), mutable_data(), release_data(), set_allocated_data(), set_data(), SharedCtor(), SharedDtor(), and Swap().
PrevirtType_Float * previrt::proto::PrevirtType_Float::default_instance_ = NULL static private
Definition at line 498 of file Previrt.pb.h.
Referenced by default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
const int previrt::proto::PrevirtType_Float::kDataFieldNumber = 42 static
Definition at line 469 of file Previrt.pb.h.
const int previrt::proto::PrevirtType_Float::kSemFieldNumber = 41 static
Definition at line 462 of file Previrt.pb.h.
int previrt::proto::PrevirtType_Float::sem_ private
Definition at line 488 of file Previrt.pb.h.
Referenced by Clear(), clear_sem(), sem(), set_sem(), SharedCtor(), and Swap().
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc