Occam - Application Specialization: previrt::proto::ComponentInterfaceTransform Class Reference
previrt::proto::ComponentInterfaceTransform Class Reference
#include <Previrt.pb.h>
Public Member Functions
ComponentInterfaceTransform ()
virtual ~ComponentInterfaceTransform ()
ComponentInterfaceTransform (const ComponentInterfaceTransform &from)
ComponentInterfaceTransform & operator= (const ComponentInterfaceTransform &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ComponentInterfaceTransform *other)
ComponentInterfaceTransform * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ComponentInterfaceTransform &from)
void MergeFrom (const ComponentInterfaceTransform &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
int calls_size () const
void clear_calls ()
const
::previrt::proto::CallRewrite & calls (int index) const
inline::previrt::proto::CallRewrite * mutable_calls (int index)
inline::previrt::proto::CallRewrite * add_calls ()
const
::google::protobuf::RepeatedPtrField
< ::previrt::proto::CallRewrite > & calls () const
inline::google::protobuf::RepeatedPtrField
< ::previrt::proto::CallRewrite > * mutable_calls ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const
ComponentInterfaceTransform & default_instance ()
Static Public Attributes
static const int kCallsFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::RepeatedPtrField
< ::previrt::proto::CallRewrite > calls_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(1+31)/32]
Static Private Attributes
static
ComponentInterfaceTransform * default_instance_ = NULL
Friends
void protobuf_AddDesc_Previrt_2eproto ()
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
Detailed Description
Definition at line 1098 of file Previrt.pb.h.
Constructor & Destructor Documentation
previrt::proto::ComponentInterfaceTransform::ComponentInterfaceTransform ()
Definition at line 3260 of file Previrt.pb.cc.
References SharedCtor().
Referenced by New().
previrt::proto::ComponentInterfaceTransform::~ComponentInterfaceTransform () virtual
Definition at line 3279 of file Previrt.pb.cc.
References SharedDtor().
previrt::proto::ComponentInterfaceTransform::ComponentInterfaceTransform (const ComponentInterfaceTransform & from)
Definition at line 3268 of file Previrt.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
previrt::proto::CallRewrite * previrt::proto::ComponentInterfaceTransform::add_calls () inline
Definition at line 2833 of file Previrt.pb.h.
References calls_.
Referenced by MergePartialFromCodedStream().
int previrt::proto::ComponentInterfaceTransform::ByteSize () const
Definition at line 3382 of file Previrt.pb.cc.
References _cached_size_, calls(), calls_size(), and unknown_fields().
const ::previrt::proto::CallRewrite & previrt::proto::ComponentInterfaceTransform::calls (int index) const inline
Definition at line 2827 of file Previrt.pb.h.
References calls_.
const ::google::protobuf::RepeatedPtrField<::previrt::proto::CallRewrite > & previrt::proto::ComponentInterfaceTransform::calls () const inline
Definition at line 2837 of file Previrt.pb.h.
References calls_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
int previrt::proto::ComponentInterfaceTransform::calls_size () const inline
Definition at line 2821 of file Previrt.pb.h.
References calls_.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
void previrt::proto::ComponentInterfaceTransform::Clear ()
Definition at line 3309 of file Previrt.pb.cc.
References _has_bits_, calls_, and mutable_unknown_fields().
Referenced by CopyFrom().
void previrt::proto::ComponentInterfaceTransform::clear_calls () inline
Definition at line 2824 of file Previrt.pb.h.
References calls_.
void previrt::proto::ComponentInterfaceTransform::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 3422 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
void previrt::proto::ComponentInterfaceTransform::CopyFrom (const ComponentInterfaceTransform & from)
Definition at line 3428 of file Previrt.pb.cc.
References Clear(), and MergeFrom().
const ComponentInterfaceTransform & previrt::proto::ComponentInterfaceTransform::default_instance () static
Definition at line 3298 of file Previrt.pb.cc.
References default_instance_, and protobuf_AddDesc_Previrt_2eproto.
Referenced by previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes().
const ::google::protobuf::Descriptor * previrt::proto::ComponentInterfaceTransform::descriptor () static
Definition at line 3293 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ComponentInterfaceTransform_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
int previrt::proto::ComponentInterfaceTransform::GetCachedSize () const inline
Definition at line 1139 of file Previrt.pb.h.
References _cached_size_.
google::protobuf::Metadata previrt::proto::ComponentInterfaceTransform::GetMetadata () const
Definition at line 3451 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ComponentInterfaceTransform_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ComponentInterfaceTransform_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
void previrt::proto::ComponentInterfaceTransform::InitAsDefaultInstance () private
Definition at line 3265 of file Previrt.pb.cc.
Referenced by previrt::proto::protobuf_AddDesc_Previrt_2eproto().
bool previrt::proto::ComponentInterfaceTransform::IsInitialized () const
Definition at line 3434 of file Previrt.pb.cc.
References calls(), and calls_size().
void previrt::proto::ComponentInterfaceTransform::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 3404 of file Previrt.pb.cc.
Referenced by ComponentInterfaceTransform(), and CopyFrom().
void previrt::proto::ComponentInterfaceTransform::MergeFrom (const ComponentInterfaceTransform & from)
Definition at line 3416 of file Previrt.pb.cc.
References calls_, mutable_unknown_fields(), and unknown_fields().
bool previrt::proto::ComponentInterfaceTransform::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 3315 of file Previrt.pb.cc.
References add_calls(), DO_, and mutable_unknown_fields().
previrt::proto::CallRewrite * previrt::proto::ComponentInterfaceTransform::mutable_calls (int index) inline
Definition at line 2830 of file Previrt.pb.h.
References calls_.
google::protobuf::RepeatedPtrField<::previrt::proto::CallRewrite > * previrt::proto::ComponentInterfaceTransform::mutable_calls () inline
Definition at line 2841 of file Previrt.pb.h.
References calls_.
inline ::google::protobuf::UnknownFieldSet* previrt::proto::ComponentInterfaceTransform::mutable_unknown_fields () inline
Definition at line 1114 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
ComponentInterfaceTransform * previrt::proto::ComponentInterfaceTransform::New () const
Definition at line 3305 of file Previrt.pb.cc.
References ComponentInterfaceTransform().
ComponentInterfaceTransform& previrt::proto::ComponentInterfaceTransform::operator= (const ComponentInterfaceTransform & from) inline
Definition at line 1105 of file Previrt.pb.h.
References CopyFrom().
void previrt::proto::ComponentInterfaceTransform::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 3352 of file Previrt.pb.cc.
References calls(), calls_size(), and unknown_fields().
google::protobuf::uint8 * previrt::proto::ComponentInterfaceTransform::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 3366 of file Previrt.pb.cc.
References calls(), calls_size(), and unknown_fields().
void previrt::proto::ComponentInterfaceTransform::SetCachedSize (int size) const private
Definition at line 3288 of file Previrt.pb.cc.
References _cached_size_.
void previrt::proto::ComponentInterfaceTransform::SharedCtor () private
Definition at line 3274 of file Previrt.pb.cc.
References _cached_size_, and _has_bits_.
Referenced by ComponentInterfaceTransform().
void previrt::proto::ComponentInterfaceTransform::SharedDtor () private
Definition at line 3283 of file Previrt.pb.cc.
References default_instance_.
Referenced by ~ComponentInterfaceTransform().
void previrt::proto::ComponentInterfaceTransform::Swap (ComponentInterfaceTransform * other)
Definition at line 3442 of file Previrt.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, and calls_.
const ::google::protobuf::UnknownFieldSet& previrt::proto::ComponentInterfaceTransform::unknown_fields () const inline
Definition at line 1110 of file Previrt.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
void protobuf_AddDesc_Previrt_2eproto () friend
Definition at line 436 of file Previrt.pb.cc.
Referenced by default_instance().
void protobuf_AssignDesc_Previrt_2eproto () friend
Definition at line 79 of file Previrt.pb.cc.
void protobuf_ShutdownFile_Previrt_2eproto () friend
Definition at line 401 of file Previrt.pb.cc.
Member Data Documentation
int previrt::proto::ComponentInterfaceTransform::_cached_size_ mutable private
Definition at line 1171 of file Previrt.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 previrt::proto::ComponentInterfaceTransform::_has_bits_[(1+31)/32] private
Definition at line 1172 of file Previrt.pb.h.
Referenced by Clear(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet previrt::proto::ComponentInterfaceTransform::_unknown_fields_ private
Definition at line 1167 of file Previrt.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
::google::protobuf::RepeatedPtrField< ::previrt::proto::CallRewrite > previrt::proto::ComponentInterfaceTransform::calls_ private
Definition at line 1169 of file Previrt.pb.h.
Referenced by add_calls(), calls(), calls_size(), Clear(), clear_calls(), MergeFrom(), mutable_calls(), and Swap().
ComponentInterfaceTransform * previrt::proto::ComponentInterfaceTransform::default_instance_ = NULL static private
Definition at line 1179 of file Previrt.pb.h.
Referenced by default_instance(), previrt::proto::protobuf_AddDesc_Previrt_2eproto(), previrt::proto::protobuf_AssignDesc_Previrt_2eproto(), previrt::proto::protobuf_ShutdownFile_Previrt_2eproto(), and SharedDtor().
const int previrt::proto::ComponentInterfaceTransform::kCallsFieldNumber = 1 static
Definition at line 1155 of file Previrt.pb.h.
The documentation for this class was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/proto/Previrt.pb.cc