Occam - Application Specialization: previrt Namespace Reference
previrt Namespace Reference
Namespaces
proto
Classes
class AggressiveSpecPolicy
class SpecializeArguments
class ConservativeSpecPolicy
struct FunctionContract
struct OrContract
struct SingletonTypeContract
class FixFunctions
class GatherInterface2Pass
class OccamPass
class PrevirtType
struct SlicePolicy
struct CallInfo
class ComponentInterface
struct CallRewrite
class ComponentInterfaceTransform
class RegisterArguments
class RecursiveGuardSpecPolicy
class RewriteComponentPass
struct SpecializationPolicy
class SpecializationTable
class SpecializerPass
class StripGccComment
struct WatchContext
struct WatchEnv
class WatchPass2
Typedefs
typedef std::string FunctionHandle
FunctionHandle is essentially a string.
typedef
SpecializationTable::Specialization Specialization
Functions
llvm::InvokeInst::op_iterator arg_begin (llvm::InvokeInst &i)
llvm::InvokeInst::op_iterator arg_end (llvm::InvokeInst &i)
llvm::CallInst::op_iterator arg_begin (llvm::CallInst &i)
llvm::CallInst::op_iterator arg_end (llvm::CallInst &i)
void protectCall (Function *F, Function *const call, const FunctionContract &I)
Function * enforceInterfaceInside (Function *F, const FunctionContract &I)
Function * enforceInterfaceOutside (Function *F, const FunctionContract &I)
FunctionContract * getContractFromInterface (StringRef name, ComponentInterface &T)
bool enforceInterface (Module &M, ComponentInterface &T, bool inside)
static RegisterPass< FixFunctions > X ("Pfix-1function","remove \\1 from function names", false, false)
static bool isInternal (Function *target)
static GlobalValue * getGlobal (Value *value)
static cl::opt< std::string > GatherInterfaceOutput ("Pinterface2-output", cl::init(""), cl::Hidden, cl::desc("specifies the output file for the interface description"))
The cl::opt lists are optimization lists that are automatically populated with registered Passes by the PassNameParser. The command line arguments to the Pass, populate the lists. cl namespace - This namespace contains all of the command line option processing machinery. The file name followed by the 'Pinterface2-output' flag specifies the output file for the interface description.
static cl::list< std::string > GatherInterfaceMain ("Pinterface2-function", cl::Hidden, cl::desc("specifies the function that is called"))
specifies the function that is called (externally)
static cl::list< std::string > GatherInterfaceEntry ("Pinterface2-entry", cl::Hidden, cl::desc("specifies the interface that is used (only function names)"))
specifies the interface that is used (only function names called externally)
static RegisterPass
< GatherInterface2Pass > X ("Pinterface2","compute the external dependencies of the module.", false, false)
Register 'Pinterface2' as an available pass with the PassManager. The 'Pinterface2' pass collects all the external references made from a module and writes them to an interface file, with file name specified as a command line argument to the Pass.
static GlobalValue::LinkageTypes localizeLinkage (GlobalValue::LinkageTypes l)
bool MinimizeComponent (Module &M, ComponentInterface &I)
static cl::list< std::string > OccamComponentInput ("Poccam-input", cl::NotHidden, cl::desc("specifies the interface to prune with respect to"))
A set of files, specifying the interface to prune with respect to. Given Multiple Modules making calls into functions defined in a certain Module, the interface files of each of the Modules need to be input to Occam component, in order to preserve all functions that are called externally.
static RegisterPass< OccamPass > X ("Poccam","hide/eliminate all non-external dependencies", false, false)
Register Poccam as an available pass with the PassManager.
static bool StringFromValue (const Value *val, StringRef &out)
static Function * buildIntEquality (IntegerType *typ, LLVMContext &ctx)
static Function * buildStringEquality (PointerType *typ, Module &M)
template<>
void codeInto< previrt::proto::PrevirtType, PrevirtType > (const previrt::proto::PrevirtType &buf, PrevirtType &result)
template<>
void codeInto< PrevirtType, proto::PrevirtType > (const PrevirtType &typ, proto::PrevirtType &buf)
void GatherInterface (llvm::Module &M, ComponentInterface &I, llvm::AliasAnalysis *aa=NULL)
void GatherInterface (llvm::Function &M, ComponentInterface &I, llvm::AliasAnalysis *aa=NULL)
void GatherInterface2 (const llvm::CallGraph &, ComponentInterface &, std::list< llvm::Function * > *roots=NULL)
bool SpecializeComponent (llvm::Module &M, ComponentInterfaceTransform &T, SpecializationPolicy &policy)
bool TransformComponent (llvm::Module &M, ComponentInterfaceTransform &T)
bool MinimizeComponent (llvm::Module &M, ComponentInterface &I)
bool sliceComponent (llvm::Module &M, const SlicePolicy &policy)
bool enforceInterface (llvm::Module &M, ComponentInterface &, bool)
bool watchFunction (llvm::Function *inside, llvm::Function *const delegate, const proto::ActionTree &policy, llvm::Constant *policyError, bool fancyFail=false)
template<>
void codeInto< CallInfo, proto::CallInfo > (const CallInfo &ci, proto::CallInfo &buf)
template<>
void codeInto< proto::CallInfo, CallInfo > (const proto::CallInfo &buf, CallInfo &ci)
template<>
void codeInto< ComponentInterface, proto::ComponentInterface > (const ComponentInterface &ci, proto::ComponentInterface &buf)
template<>
void codeInto< proto::ComponentInterface, ComponentInterface > (const proto::ComponentInterface &buf, ComponentInterface &ci)
template<>
void codeInto< proto::CallRewrite, CallRewrite > (const proto::CallRewrite &buf, CallRewrite &ci)
template<>
void codeInto< CallRewrite, proto::CallRewrite > (const CallRewrite &ci, proto::CallRewrite &buf)
template<>
void codeInto< ComponentInterfaceTransform, proto::ComponentInterfaceTransform > (const ComponentInterfaceTransform &ci, proto::ComponentInterfaceTransform &buf)
template<>
void codeInto< proto::ComponentInterface, ComponentInterfaceTransform > (const proto::ComponentInterface &buf, ComponentInterfaceTransform &ci)
template<>
void codeInto< proto::ComponentInterfaceTransform, ComponentInterfaceTransform > (const proto::ComponentInterfaceTransform &buf, ComponentInterfaceTransform &ci)
static cl::opt< std::string > ArgumentsFileName ("Parguments-input", cl::init(""), cl::Hidden, cl::desc("specifies the input file for the arguments"))
The file name containing the static arguments, to which the main function is to be specialized.
static cl::opt< std::string > SpecializeProgName ("Parguments-name", cl::init(""), cl::Hidden, cl::desc("specifies the program name"))
The name of the program to be specialized. The name replaces the usage of argv[0] in the main function.
static RegisterPass
< RegisterArguments > X ("Parguments","Specialize main() function arguments from file 'arguments'", false, false)
Register the previrt::RegisterArguments class with the PassManager, with the name 'Parguments'. The pass specializes the main function with the arguments specified in the file that is input to the pass.
static void strongconnect (CallGraphNode *from, CallGraph &cg, std::list< Function * > &stack, std::set< Function * > &stack_contents, std::map< const Function *, std::pair< int, int > > &indicies, int &next_idx, RecursiveGuardSpecPolicy::SCC &result)
static void scc (CallGraph &cg, RecursiveGuardSpecPolicy::SCC &scc)
static Instruction * applyRewriteToCall (Module &M, const CallRewrite *const rw, CallSite cs)
static bool vector_in (const std::vector< unsigned > &x, unsigned in)
bool TransformComponentWithUse (Module &M, ComponentInterfaceTransform &T)
bool TransformComponent (Module &M, ComponentInterfaceTransform &T)
static cl::list< std::string > RewriteComponentInput ("Prewrite-input", cl::NotHidden, cl::desc("specifies the interface to rewrite using"))
Specifies the interface, according to which the Module call sites need to be rewritten.
static RegisterPass
< RewriteComponentPass > X ("Prewrite","previrtualize the given module (requires parameters)", false, false)
Register the 'Prewrite' Pass with the Pass Manager. The Pass Rewrites the call sites, to functions with specific arguments, specified in the interface file passed as an argument to the Pass.
template<class Data , class Target >
Target * codeNew (const Data *)
static Function * resolveFunction (Module &M, StringRef name)
bool SpecializeComponent (Module &M, ComponentInterfaceTransform &T, SpecializationPolicy &policy, std::list< Function * > &to_add)
std::string specializeName (Function *f, std::vector< std::string > &args)
Function * specializeFunction (Function *f, Value *const *args)
Function * specializeFunction (Function *f, const std::vector< Value * > &args)
Instruction * specializeCallSite (Instruction *I, llvm::Function *nfunc, const std::vector< unsigned > &perm)
bool canSpecialize (Function *f)
GlobalVariable * materializeStringLiteral (llvm::Module &m, const char *data)
Constant * charStarFromStringConstant (llvm::Module &m, llvm::Constant *v)
llvm::Function * specializeFunction (llvm::Function *f, llvm::Value *const *args)
llvm::Function * specializeFunction (llvm::Function *f, const std::vector< llvm::Value * > &args)
llvm::Instruction * specializeCallSite (llvm::Instruction *, llvm::Function *, const std::vector< unsigned > &)
bool canSpecialize (llvm::Function *f)
static RegisterPass
< StripGccComment > X ("Pstrip-asm-ident","remove .ident... from module assembly", false, false)
Register the StripGccComment Class with the internal database of RegisterPass, 'Pstrip-asm-ident'. Remove .ident from inline Asm.
static Constant * getExit (WatchContext *ctx, const char *failureName, bool fancy)
static Value * getValue (WatchEnv &env, IRBuilder<> &irb, const watch::proto::PrimExpr &expr)
static bool getArguments (WatchEnv &env, IRBuilder<> &irb, const google::protobuf::RepeatedPtrField< watch::proto::PrimExprs > &indicies, std::vector< Value * > &result)
static void tailCall (Value *call, IRBuilder<> &builder)
static void returnUndef (Function *inside, IRBuilder<> &builder)
static bool compileAction (Function *inside, const Function *const delegate, const watch::proto::ActionTree &policy, WatchContext &ctx, WatchEnv &env, BasicBlock *result, BasicBlock *failure, BasicBlock *success)
bool watchFunction (WatchContext &ctx, WatchEnv &env, Function *inside, const Function *const delegate, const watch::proto::ActionTree &policy, Constant *policyError, bool fancyFail)
static bool patternMatches (const watch::proto::PatternExpr &ptrn, const std::string &fname, FunctionType *ft, WatchEnv &env)
static const Function * getAliasedFunction (const GlobalAlias *alias)
static cl::list< std::string > WatchInput ("Pwatch2-input", cl::NotHidden, cl::desc("interfaces to watch"))
static cl::opt< bool > WatchFancy ("Pwatch2-fancy", cl::Hidden, cl::init(false), cl::desc("should the failure function be passed the name and arguments?"))
static cl::opt< bool > WatchAllowLocal ("Pwatch2-local", cl::Hidden, cl::init(false), cl::desc("allow local calls to the function"))
static cl::opt< std::string > WatchFailFunction ("Pwatch2-fail", cl::Hidden, cl::init("exit"), cl::desc("name of function to call"))
static RegisterPass< WatchPass2 > X ("Pwatch2","watch/enforce an interface inside functions", false, false)
The WatchPass2 Class is registered as a Pass with the PassManageer internal database with the name 'Pwatch2'.
Detailed Description
The Previrt Namespace contains helper functions, and Classes inheriting LLVM Passes
Typedef Documentation
typedef std::string previrt::FunctionHandle
FunctionHandle is essentially a string.
Definition at line 57 of file PrevirtualizeInterfaces.h.
typedef SpecializationTable::Specialization previrt::Specialization
Definition at line 61 of file SpecializationTable.cpp.
Function Documentation
static Instruction* previrt::applyRewriteToCall (Module & M, const CallRewrite *const rw, CallSite cs) static
Replace the call sites 'cs' in the Module M with specialized call sites, with respect to the arguments in the previrt::proto::CallRewrite object
Definition at line 67 of file RewriteComponent.cpp.
References previrt::CallRewrite::args, previrt::CallRewrite::function, and specializeCallSite().
Referenced by TransformComponentWithUse().
llvm::InvokeInst::op_iterator previrt::arg_begin (llvm::InvokeInst & i) inline
Definition at line 49 of file ArgIterator.h.
llvm::CallInst::op_iterator previrt::arg_begin (llvm::CallInst & i) inline
Definition at line 61 of file ArgIterator.h.
llvm::InvokeInst::op_iterator previrt::arg_end (llvm::InvokeInst & i) inline
Definition at line 55 of file ArgIterator.h.
llvm::CallInst::op_iterator previrt::arg_end (llvm::CallInst & i) inline
Definition at line 67 of file ArgIterator.h.
static cl::opt<std::string> previrt::ArgumentsFileName ("Parguments-input" , cl:: init"", cl::Hidden , cl:: desc"specifies the input file for the arguments") static
The file name containing the static arguments, to which the main function is to be specialized.
static Function* previrt::buildIntEquality (IntegerType * typ, LLVMContext & ctx) static
Build an equality function that takes two integers parameters, testing the equality of the values and returns the result of comparing the two values. The function is given the Attribute::AlwaysInline and once the PassManager Pass is applied the function is in-lined into the calling function body.
Definition at line 583 of file PrevirtTypes.cpp.
Referenced by previrt::PrevirtType::getEqualityFunction().
static Function* previrt::buildStringEquality (PointerType * typ, Module & M) static
Build an equality function that takes two string parameters, testing the equality of the values and returns the result of comparing the two values. The function is given the Attribute::AlwaysInline and once the PassManager Pass is applied the function is in-lined into the calling function body.
Definition at line 610 of file PrevirtTypes.cpp.
Referenced by previrt::PrevirtType::getEqualityFunction().
bool previrt::canSpecialize (llvm::Function * f)
bool previrt::canSpecialize (Function * f)
The canSpecialize function returns false if a call site within in-line assembly is found. A function containing an in-line assembly call is not subject to our analysis and thereby specializing such a function could remove arguments required within the in-line assembly. If no call-site within in-line assembly is found, canSpecialize returns true for the function f
Definition at line 333 of file Specializer.cpp.
References previrt::proto::I.
Referenced by trySpecializeFunction().
llvm::Constant * previrt::charStarFromStringConstant (llvm::Module & m, llvm::Constant * v)
Definition at line 365 of file Specializer.cpp.
Referenced by previrt::PrevirtType::concretize().
template<> void previrt::codeInto< CallInfo, proto::CallInfo > (const CallInfo & ci, proto::CallInfo & buf)
The previrt::CallInfo ci object is copied into the previrt::proto::CallInfo object buf
Definition at line 96 of file PrevirtualizeInterfaces.cpp.
template<> void previrt::codeInto< CallRewrite, proto::CallRewrite > (const CallRewrite & ci, proto::CallRewrite & buf)
The function copies a previrt::CallRewrite object ci into a previrt::proto::CallRewrite buffer (Google protocol buffer) buf
Definition at line 456 of file PrevirtualizeInterfaces.cpp.
template<> void previrt::codeInto< ComponentInterface, proto::ComponentInterface > (const ComponentInterface & ci, proto::ComponentInterface & buf)
Copy the previrt::ComponentInterface object ci into the previrt::proto::ComponentInterface(Google protocol buffer) buf
Definition at line 358 of file PrevirtualizeInterfaces.cpp.
References previrt::proto::CallInfo::set_name().
template<> void previrt::codeInto< ComponentInterfaceTransform, proto::ComponentInterfaceTransform > (const ComponentInterfaceTransform & ci, proto::ComponentInterfaceTransform & buf)
The function copies a previrt::ComponentInterfaceTransform object ci into a previrt::proto::ComponentInterfaceTransform buffer (Google protocol buffer) object buf
Definition at line 471 of file PrevirtualizeInterfaces.cpp.
References previrt::proto::CallRewrite::mutable_call().
template<> void previrt::codeInto< previrt::proto::PrevirtType, PrevirtType > (const previrt::proto::PrevirtType & buf, PrevirtType & result)
Copy a previrt::proto::PrevirtType buffer 'buf', into a previrt::PrevirtType object result
Definition at line 694 of file PrevirtTypes.cpp.
template<> void previrt::codeInto< PrevirtType, proto::PrevirtType > (const PrevirtType & typ, proto::PrevirtType & buf)
Copy a previrt::PrevirtType object 'typ', into a previrt::proto::PrevirtType buffer 'buf'
Definition at line 705 of file PrevirtTypes.cpp.
template<> void previrt::codeInto< proto::CallInfo, CallInfo > (const proto::CallInfo & buf, CallInfo & ci)
Copies the previrt::proto::CallInfo (Google protocol buffer) into the previrt::CallInfo structure
Definition at line 109 of file PrevirtualizeInterfaces.cpp.
template<> void previrt::codeInto< proto::CallRewrite, CallRewrite > (const proto::CallRewrite & buf, CallRewrite & ci)
The function copies a previrt::proto::CallRewrite buffer (Google protocol buffer) buf into a previrt::CallRewrite object ci
Definition at line 442 of file PrevirtualizeInterfaces.cpp.
template<> void previrt::codeInto< proto::ComponentInterface, ComponentInterface > (const proto::ComponentInterface & buf, ComponentInterface & ci)
Copy the previrt::proto::ComponentInterface (Google protocol buffer) buf into the previrt::ComponentInterface object ci
Definition at line 383 of file PrevirtualizeInterfaces.cpp.
References previrt::proto::CallInfo::name().
template<> void previrt::codeInto< proto::ComponentInterface, ComponentInterfaceTransform > (const proto::ComponentInterface & buf, ComponentInterfaceTransform & ci)
The function copies a previrt::proto::ComponentInterface (Google protocol buffer) buf into a previrt::ComponentInterfaceTransform object ci
Definition at line 494 of file PrevirtualizeInterfaces.cpp.
template<> void previrt::codeInto< proto::ComponentInterfaceTransform, ComponentInterfaceTransform > (const proto::ComponentInterfaceTransform & buf, ComponentInterfaceTransform & ci)
The function copies a previrt::proto::ComponentInterfaceTransform (Google protocol buffer) buf into a previrt::ComponentInterfaceTransform object ci
Definition at line 510 of file PrevirtualizeInterfaces.cpp.
References previrt::CallInfo::args, previrt::proto::CallRewrite::call(), previrt::CallInfo::count, and previrt::proto::CallInfo::name().
template<class Data , class Target > Target* previrt::codeNew (const Data *)
static bool previrt::compileAction (Function * inside, const Function *const delegate, const watch::proto::ActionTree & policy, WatchContext & ctx, WatchEnv & env, BasicBlock * result, BasicBlock * failure, BasicBlock * success) static
The compileAction function uses the IRBuilder to construct, a wrapper function over the original function to watch the function. (Enforce the interface specified by the Google protocol buffer serialized file). It compares the values of the arguments to be equal to the previrt::PrevirtType values. If found unequal a failure function is called. If the interface is not violated by a call, the original function (delegate) is invoked. The compileAction Function is called recursively, as the action policy can be nested The 'if' actions are the only actions can be nested.
Definition at line 549 of file Watch2.cpp.
References getArguments(), previrt::WatchContext::getCallFunction(), previrt::WatchContext::getContext(), previrt::PrevirtType::getEqualityFunction(), getValue(), previrt::WatchEnv::lookupValue(), returnUndef(), tailCall(), and previrt::WatchEnv::valueEnv.
Referenced by watchFunction().
bool previrt::enforceInterface (llvm::Module & M, ComponentInterface & , bool)
The function enforces the ComponentInterface to the functions of the Module. Watches also serve the purpose of interface enforcement, but watches are computationally more expensive to implement.
bool previrt::enforceInterface (Module & M, ComponentInterface & T, bool inside)
The enforceInterface function iterates through all the functions that are a part of the previrt::ComponentInterface enforcing interfaces to the functions by calling previrt::enforceInterfaceInside for a function definition, and previrt::enforceInterfaceOutside for a function declaration
Definition at line 366 of file EnforceInterface.cpp.
References previrt::ComponentInterface::begin(), previrt::ComponentInterface::end(), enforceInterfaceInside(), enforceInterfaceOutside(), and getContractFromInterface().
Function* previrt::enforceInterfaceInside (Function * F, const FunctionContract & I)
Enforce an interface inside a function. Code is injected into function definitions to test the equality of the previrt::PrevirtType arguments against the function arguments. If the tests are successful, the protected function F is called otherwise, the failure function is called
Definition at line 302 of file EnforceInterface.cpp.
References protectCall().
Referenced by enforceInterface().
Function* previrt::enforceInterfaceOutside (Function * F, const FunctionContract & I)
Enforce an interface outside a call (For function declarations). A wrapper is created around the declaration, that tests the equality of the previrt::PrevirtType arguments against the function arguments. If the tests are successful, the protected function is called otherwise, the failure function is called
Definition at line 323 of file EnforceInterface.cpp.
References protectCall().
Referenced by enforceInterface().
void previrt::GatherInterface (llvm::Module & M, ComponentInterface & I, llvm::AliasAnalysis * aa = NULL)
void previrt::GatherInterface (llvm::Function & M, ComponentInterface & I, llvm::AliasAnalysis * aa = NULL)
Compute the minimal interface that the given function depends on NOTE: Use GatherInterface2 instead
void previrt::GatherInterface2 (const llvm::CallGraph & , ComponentInterface & , std::list< llvm::Function * > * roots = NULL)
This is a sketch of a new implementation of GatherInterface that uses CallGraph the benefit of using CallGraph is that we can (in theory) hook into alias analysis and other passes that refine indirect function calls (an attempt at this is AACallGraph.cpp)
static cl::list<std::string> previrt::GatherInterfaceEntry ("Pinterface2-entry" , cl::Hidden , cl:: desc"specifies the interface that is used (only function names)") static
specifies the interface that is used (only function names called externally)
Referenced by previrt::GatherInterface2Pass::runOnModule().
static cl::list<std::string> previrt::GatherInterfaceMain ("Pinterface2-function" , cl::Hidden , cl:: desc"specifies the function that is called") static
specifies the function that is called (externally)
Referenced by previrt::GatherInterface2Pass::runOnModule().
static cl::opt<std::string> previrt::GatherInterfaceOutput ("Pinterface2-output" , cl:: init"", cl::Hidden , cl:: desc"specifies the output file for the interface description") static
The cl::opt lists are optimization lists that are automatically populated with registered Passes by the PassNameParser. The command line arguments to the Pass, populate the lists. cl namespace - This namespace contains all of the command line option processing machinery. The file name followed by the 'Pinterface2-output' flag specifies the output file for the interface description.
Referenced by previrt::GatherInterface2Pass::runOnModule().
static const Function* previrt::getAliasedFunction (const GlobalAlias * alias) static
previrt::getAliasedFunction, returns the Function* to which an alias is made
Definition at line 871 of file Watch2.cpp.
Referenced by previrt::WatchPass2::runOnModule().
static bool previrt::getArguments (WatchEnv & env, IRBuilder<> & irb, const google::protobuf::RepeatedPtrField< watch::proto::PrimExprs > & indicies, std::vector< Value * > & result) static
The getArguments function populates the result vector reading the indices array.
Definition at line 463 of file Watch2.cpp.
References previrt::WatchEnv::argRangeAdd(), and getValue().
Referenced by compileAction().
FunctionContract* previrt::getContractFromInterface (StringRef name, ComponentInterface & T)
The function takes as argument a function name, and creates a vector of FunctionContract based on the usages of the function (arguments to calls). An object of previrt::OrContract is created and returned instantiated with the vector of FunctionContract
Definition at line 342 of file EnforceInterface.cpp.
References previrt::ComponentInterface::call_begin(), previrt::ComponentInterface::call_end(), previrt::ComponentInterface::end(), and previrt::ComponentInterface::find().
Referenced by enforceInterface().
static Constant* previrt::getExit (WatchContext * ctx, const char * failureName, bool fancy) static
Creates a failure function with the name failureName and add it to the Module . If a function with the name failureName, already exists do not create a new one.
Definition at line 368 of file Watch2.cpp.
References previrt::WatchContext::added_functions, previrt::WatchContext::getContext(), and previrt::WatchContext::module.
Referenced by previrt::WatchPass2::runOnModule().
static GlobalValue* previrt::getGlobal (Value * value) static
Function definitions become part of program, if macro evaluates to true
Definition at line 379 of file GatherInterface2.cpp.
Referenced by previrt::GatherInterface2Pass::runOnModule().
static Value* previrt::getValue (WatchEnv & env, IRBuilder<> & irb, const watch::proto::PrimExpr & expr) static
Definition at line 424 of file Watch2.cpp.
References previrt::WatchEnv::getContext(), previrt::proto::I, previrt::WatchEnv::lookupValue(), and previrt::WatchEnv::materializeMatch().
Referenced by compileAction(), and getArguments().
static bool previrt::isInternal (Function * target) static
The isInternal Function given a function pointer as argument, returns true if the function is defined inside the module and false otherwise.
Definition at line 73 of file GatherInterface2.cpp.
Referenced by previrt::GatherInterface2Pass::runOnModule().
static GlobalValue::LinkageTypes previrt::localizeLinkage (GlobalValue::LinkageTypes l) inline static
The function returns an internal linkage counterpart for each external linkage type
Definition at line 66 of file OccamComponent.cpp.
Referenced by MinimizeComponent().
llvm::GlobalVariable * previrt::materializeStringLiteral (llvm::Module & m, const char * data)
Given a char * data, the function creates a GlobalVariable holding the string, and returns the pointer to it
Definition at line 353 of file Specializer.cpp.
Referenced by previrt::PrevirtType::concretize(), previrt::WatchEnv::materializeMatch(), and previrt::SpecializeArguments::runOnModule().
bool previrt::MinimizeComponent (Module & M, ComponentInterface & I)
Remove all code from the given module that is not necessary to implement the given interface. In llvm each function is by default external-linkage(assumed to be called externally). To remove dead code it is necessary to modify the linkage of the functions, not called externally to internal-linkage. previrt::localizeLinkage is called to return an internal-linkage counter-part for each external definition. Once internalized the llvm PassManager performs dead code elimination in the module. The dead code elimination is performed in a loop, until there is more code still to be removed.
The given Interface I of type previrt::proto::ComponentInterface is a list of functions and Globals that are accessed from other modules. These functions and globals should not be internalized as they are being accessed from other modules.
Definition at line 94 of file OccamComponent.cpp.
References previrt::ComponentInterface::calls, previrt::ComponentInterface::dump(), localizeLinkage(), and previrt::ComponentInterface::references.
Referenced by previrt::OccamPass::runOnModule().
bool previrt::MinimizeComponent (llvm::Module & M, ComponentInterface & I)
Remove all code from the given module that is not necessary to implement the given interface.
static cl::list<std::string> previrt::OccamComponentInput ("Poccam-input" , cl::NotHidden , cl:: desc"specifies the interface to prune with respect to") static
A set of files, specifying the interface to prune with respect to. Given Multiple Modules making calls into functions defined in a certain Module, the interface files of each of the Modules need to be input to Occam component, in order to preserve all functions that are called externally.
Referenced by previrt::OccamPass::OccamPass().
static bool previrt::patternMatches (const watch::proto::PatternExpr & ptrn, const std::string & fname, FunctionType * ft, WatchEnv & env) static
The previrt::proto::PatternExpr Google protocol buffer contains the following members:
1) ModuleName
2) FunctionName
3) ExcludedFunctions[]
4) Predicates[]
If the function name is found, in the pattern 'ptrn' as a regex, and is not in the list of excluded functions, save the function name in the 'env.matchEnv' vector
Definition at line 811 of file Watch2.cpp.
References previrt::WatchEnv::matchCache, previrt::WatchEnv::matchEnv, and MAX_MATCH.
Referenced by previrt::WatchPass2::runOnModule().
void previrt::protectCall (Function * F, Function *const call, const FunctionContract & I)
Generate a piece of code in F that enforces I, protecting calls to 'call'. It calls emitEntryTest in turn to create equality tests that validate the interface
Definition at line 238 of file EnforceInterface.cpp.
References previrt::FunctionContract::emitEntryTest().
Referenced by enforceInterfaceInside(), and enforceInterfaceOutside().
static Function* previrt::resolveFunction (Module & M, StringRef name) static
Given a StringRef name of the function, or the name of the alias to the function, return the pointer to the function
Definition at line 66 of file SpecializeComponent.cpp.
Referenced by SpecializeComponent().
static void previrt::returnUndef (Function * inside, IRBuilder<> & builder) static
If the return type of the function inside, is void, create a void return type instruction in the basic block built by the IRBuilder builder, else create an appropriate return instruction based on the return type of inside
Definition at line 529 of file Watch2.cpp.
Referenced by compileAction(), and watchFunction().
static cl::list<std::string> previrt::RewriteComponentInput ("Prewrite-input" , cl::NotHidden , cl:: desc"specifies the interface to rewrite using") static
Specifies the interface, according to which the Module call sites need to be rewritten.
Referenced by previrt::RewriteComponentPass::RewriteComponentPass().
static void previrt::scc (CallGraph & cg, RecursiveGuardSpecPolicy::SCC & scc) static
The function iterates over the indices in the call graph and calls previrt::strongconnect to identify recursive functions given a callgraph node and adds functions found recursive to the sccs map
Definition at line 185 of file RecursiveGuardSpecPolicy.cpp.
References strongconnect().
Referenced by previrt::RecursiveGuardSpecPolicy::RecursiveGuardSpecPolicy().
bool previrt::sliceComponent (llvm::Module & M, const SlicePolicy & policy)
llvm::Instruction* previrt::specializeCallSite (llvm::Instruction * , llvm::Function * , const std::vector< unsigned > &)
Instruction* previrt::specializeCallSite (Instruction * I, llvm::Function * nfunc, const std::vector< unsigned > & perm)
Specialize a call site I reducing the arguments to the specialized version of the function nfunc, and return the new call instruction
Parameters
I Instruction Call site to be specialized
nfunc The pointer to the specialized function
perm Array of indices to the array of arguments in the CallInst, that have to be included in the new call-site
Definition at line 264 of file Specializer.cpp.
Referenced by applyRewriteToCall(), and trySpecializeFunction().
bool previrt::SpecializeComponent (llvm::Module & M, ComponentInterfaceTransform & T, SpecializationPolicy & policy)
Referenced by anonymous_namespace{SpecializeComponent.cpp}::SpecializeComponentPass::runOnModule().
bool previrt::SpecializeComponent (Module & M, ComponentInterfaceTransform & T, SpecializationPolicy & policy, std::list< Function * > & to_add)
Reduce this module with respect to the given interface.
The interface suggests some of the uses of the functions, so here we can generate special versions of those functions. Generate a ComponentInterfaceTransform for clients to rewrite their code to use the new API. The previrt::specializeComponent calls previrt::specializeFunction, to create a specialized version of the function corresponding to list of arguments in the transform object. The new function name, along with arguments is written to the previrt::ComponentInterfaceTransform object. the file will be used by the 'Prewrite' Pass to replace the existing call-sites with specialized call-sites. The previrt::proto::ComponentInterface object is extracted from the previrt::ComponentInterfaceTransform class data member
Definition at line 100 of file SpecializeComponent.cpp.
References previrt::CallInfo::args, previrt::ComponentInterface::begin(), previrt::ComponentInterface::call_begin(), previrt::ComponentInterface::call_end(), previrt::ComponentInterface::end(), previrt::ComponentInterfaceTransform::getInterface(), previrt::proto::I, resolveFunction(), previrt::ComponentInterfaceTransform::rewrite(), specializeFunction(), and previrt::SpecializationPolicy::specializeOn().
llvm::Function* previrt::specializeFunction (llvm::Function * f, llvm::Value *const * args)
llvm::Function* previrt::specializeFunction (llvm::Function * f, const std::vector< llvm::Value * > & args)
Function* previrt::specializeFunction (Function * f, Value *const * args)
specializeFunction creates a specialized version of function f based on the arguments array args The set of operations performed are:
1) previrt::specializeName is called to retrieve the base name of the original function.
2) Based on the arguments passed onto the specialized copy a unique name is constructed for the specialized function.
3) cloneFunction (llvm) is called to create a clone of the function, to directly embed the values of the partially evaluated arguments into the function body, thus reducing the parameters to the specialized version of the function.
4) Return the pointer to the newly specialized copy of the function f.
Parameters
f is the original function to be specialized
args is an array containing a policy corresponding to each argument. a NON-NULL value means the argument is to be removed from the new copy and the value of the argument directly embedded inside the function body.
Definition at line 152 of file Specializer.cpp.
References specializeName(), and previrt::PrevirtType::to_string().
Referenced by SpecializeComponent(), specializeFunction(), and trySpecializeFunction().
Function* previrt::specializeFunction (Function * f, const std::vector< Value * > & args)
The specializeFunction calls previrt::specializeFunction with the function pointer f and the set of arguments args to for which a specialized version of function f needs to be created
Definition at line 237 of file Specializer.cpp.
References specializeFunction().
std::string previrt::specializeName (Function * f, std::vector< std::string > & args)
The function assigns a new unique name to the specialized version of the function. The name is assigned respective to the parameters to the function. If the function name already consisted of a full qualified name consisting of the arguments and their types as a part of their name only the base name is returned, otherwise the base name is appended with a left bracket '(' and a question mark '?' whereas each question mark corresponds to an argument.
For example if the function name is : "printArr(arg1,arg2)", the specializeName routine returns "printArr" (base name) and the arguments "arg1" and "arg2" in the vector args (sent as argument to the function).
If the function name is "printArr" the function simply returns "printArr" (base name) and '?', for each argument in the vector of args.
Definition at line 74 of file Specializer.cpp.
Referenced by specializeFunction().
static cl::opt<std::string> previrt::SpecializeProgName ("Parguments-name" , cl:: init"", cl::Hidden , cl:: desc"specifies the program name") static
The name of the program to be specialized. The name replaces the usage of argv[0] in the main function.
static bool previrt::StringFromValue (const Value * val, StringRef & out) static
The function calls getConstantStringInfo with val and out as arguments. getConstantStringInfo - This function computes the length of a null-terminated C string pointed to by a Value *. If successful, it returns true and returns the string in out. If unsuccessful, it returns false.
Definition at line 129 of file PrevirtTypes.cpp.
Referenced by previrt::PrevirtType::abstract(), and previrt::PrevirtType::refines().
static void previrt::strongconnect (CallGraphNode * from, CallGraph & cg, std::list< Function * > & stack, std::set< Function * > & stack_contents, std::map< const Function *, std::pair< int, int > > & indicies, int & next_idx, RecursiveGuardSpecPolicy::SCC & result) static
The strongconnect function iterates over the call graph, and identifies all recursive functions. The recursive functions are saved onto the sccs map. The RecursiveSpecPolicy::allowSpecialization searches the sccs map to check if a function is recursive. If the function is found recursive, specialization on function arguments does not proceed.
Definition at line 116 of file RecursiveGuardSpecPolicy.cpp.
Referenced by scc().
static void previrt::tailCall (Value * call, IRBuilder<> & builder) static
If the return type of the function call is void, add a void return statement to the basic block that is created by IRBuilder builder . Otherwise return the value, returned by the call to function call
Definition at line 514 of file Watch2.cpp.
Referenced by compileAction().
bool previrt::TransformComponent (llvm::Module & M, ComponentInterfaceTransform & T)
Rewrite the given module according to the ComponentInterfaceTransformer.
Referenced by previrt::RewriteComponentPass::runOnModule().
bool previrt::TransformComponent (Module & M, ComponentInterfaceTransform & T)
Transform the Module M with respect to the ComponentInterfaceTransform, previrt::TransformComponentWithUse is called to replace all the call-sites to specialized functions with rewritten call-sites.
Definition at line 261 of file RewriteComponent.cpp.
References TransformComponentWithUse().
bool previrt::TransformComponentWithUse (Module & M, ComponentInterfaceTransform & T)
The function rewrites the call sites to functions present in the previrt::ComponentInterfaceTransform. The function performs the following sequence of operations:
1) Iterates over the previrt::CallRewrite objects in the previrt::ComponentInterfaceTransform object.
2) If the previrt::CallRewrite object applies to a function not defined in the current Module simply skip.
3) If the function is found within the module, iterate over all of the uses of the function and visit all the call-sites to the function.
4) If a previrt::CallRewrite is available for the particular call-site, rewrite the call-site with fewer arguments.
5) Replace the original call-site with the rewritten call-site
6) If any single call-site was modified, the function returns true, otherwise returns false.
Definition at line 120 of file RewriteComponent.cpp.
References applyRewriteToCall(), previrt::CallRewrite::args, previrt::ComponentInterfaceTransform::lookupRewrite(), previrt::ComponentInterfaceTransform::rewrites, previrt::proto::U, and vector_in().
Referenced by TransformComponent().
static bool previrt::vector_in (const std::vector< unsigned > & x, unsigned in) static
Definition at line 94 of file RewriteComponent.cpp.
Referenced by TransformComponentWithUse().
static cl::opt<bool> previrt::WatchAllowLocal ("Pwatch2-local" , cl::Hidden , cl:: initfalse, cl:: desc"allow local calls to the function") static
static cl::opt<std::string> previrt::WatchFailFunction ("Pwatch2-fail" , cl::Hidden , cl:: init"exit", cl:: desc"name of function to call") static
static cl::opt<bool> previrt::WatchFancy ("Pwatch2-fancy" , cl::Hidden , cl:: initfalse, cl:: desc"should the failure function be passed the name and arguments?") static
bool previrt::watchFunction (llvm::Function * inside, llvm::Function *const delegate, const proto::ActionTree & policy, llvm::Constant * policyError, bool fancyFail = false)
The function adds watch code to the Function 'inside' protecting calls to 'delegate'. The call to delegate (original function) is only made if the interface has not been violated. In case the interface is violated, the failure function is called
Referenced by previrt::WatchPass2::runOnModule().
bool previrt::watchFunction (WatchContext & ctx, WatchEnv & env, Function * inside, const Function *const delegate, const watch::proto::ActionTree & policy, Constant * policyError, bool fancyFail)
The watchFunction does the following:
1) Creates three basic blocks a) the 'entry' basic block b) the 'success' basic block; the block called if the entry test succeed c) The 'failure' basic block; is called if the interface is violated. It calls the failure function.
2) previrt::compileAction is called to enforce the interface in the newly added 'entry' basic block as specified by the watch::proto::ActionTree& policy
Definition at line 744 of file Watch2.cpp.
References compileAction(), previrt::WatchContext::getContext(), returnUndef(), and previrt::WatchEnv::valueEnv.
static cl::list<std::string> previrt::WatchInput ("Pwatch2-input" , cl::NotHidden , cl:: desc"interfaces to watch") static
Referenced by previrt::WatchPass2::WatchPass2().
static RegisterPass<FixFunctions> previrt::X ("Pfix-1function" , "remove \\1 from function names" , false , false) static
static RegisterPass<StripGccComment> previrt::X ("Pstrip-asm-ident" , "remove .ident... from module assembly" , false , false) static
Register the StripGccComment Class with the internal database of RegisterPass, 'Pstrip-asm-ident'. Remove .ident from inline Asm.
static RegisterPass<OccamPass> previrt::X ("Poccam" , "hide/eliminate all non-external dependencies" , false , false) static
Register Poccam as an available pass with the PassManager.
static RegisterPass<RegisterArguments> previrt::X ("Parguments" , "Specialize main() function arguments from file 'arguments'" , false , false) static
Register the previrt::RegisterArguments class with the PassManager, with the name 'Parguments'. The pass specializes the main function with the arguments specified in the file that is input to the pass.
static RegisterPass<RewriteComponentPass> previrt::X ("Prewrite" , "previrtualize the given module (requires parameters)" , false , false) static
Register the 'Prewrite' Pass with the Pass Manager. The Pass Rewrites the call sites, to functions with specific arguments, specified in the interface file passed as an argument to the Pass.
static RegisterPass<GatherInterface2Pass> previrt::X ("Pinterface2" , "compute the external dependencies of the module." , false , false) static
Register 'Pinterface2' as an available pass with the PassManager. The 'Pinterface2' pass collects all the external references made from a module and writes them to an interface file, with file name specified as a command line argument to the Pass.
static RegisterPass<WatchPass2> previrt::X ("Pwatch2" , "watch/enforce an interface inside functions" , false , false) static
The WatchPass2 Class is registered as a Pass with the PassManageer internal database with the name 'Pwatch2'.