Occam - Application Specialization: previrt::proto Namespace Reference
previrt::proto Namespace Reference
Namespaces
anonymous_namespace{Previrt.pb.cc}
Classes
struct StaticDescriptorInitializer_Previrt_2eproto
class PrevirtType_Int
class PrevirtType_Vec
class PrevirtType_Str
class PrevirtType_Float
class PrevirtType_Global
class PrevirtType
class CallInfo
class CallRewrite
class ComponentInterface
class ComponentInterfaceTransform
class ActionTree_Case
class ActionTree_Forward
class ActionTree_Event
class ActionTree
class EnforceInterface_Functions
class EnforceInterface
Enumerations
enum Type {
U = 0, I = 1, F = 2, S = 3,
V = 4, N = 5, G = 6
}
enum FloatSemantics {
IEEEhalf = 1, IEEEsingle = 2, IEEEdouble = 3, IEEEquad = 4,
x87DoubleExtended = 5, Bogus = 6, PPCDoubleDouble = 7
}
enum ActionType { CASE = 1, FORWARD = 2, EVENT = 3, FAIL = 4 }
Functions
void protobuf_AssignDesc_Previrt_2eproto ()
void protobuf_ShutdownFile_Previrt_2eproto ()
void protobuf_AddDesc_Previrt_2eproto ()
const
::google::protobuf::EnumDescriptor * Type_descriptor ()
bool Type_IsValid (int value)
const
::google::protobuf::EnumDescriptor * FloatSemantics_descriptor ()
bool FloatSemantics_IsValid (int value)
const
::google::protobuf::EnumDescriptor * ActionType_descriptor ()
bool ActionType_IsValid (int value)
const ::std::string & Type_Name (Type value)
bool Type_Parse (const ::std::string &name, Type *value)
const ::std::string & FloatSemantics_Name (FloatSemantics value)
bool FloatSemantics_Parse (const ::std::string &name, FloatSemantics *value)
const ::std::string & ActionType_Name (ActionType value)
bool ActionType_Parse (const ::std::string &name, ActionType *value)
Variables
struct
previrt::proto::StaticDescriptorInitializer_Previrt_2eproto static_descriptor_initializer_Previrt_2eproto_
const Type Type_MIN = U
const Type Type_MAX = G
const int Type_ARRAYSIZE = Type_MAX + 1
const FloatSemantics FloatSemantics_MIN = IEEEhalf
const FloatSemantics FloatSemantics_MAX = PPCDoubleDouble
const int FloatSemantics_ARRAYSIZE = FloatSemantics_MAX + 1
const ActionType ActionType_MIN = CASE
const ActionType ActionType_MAX = FAIL
const int ActionType_ARRAYSIZE = ActionType_MAX + 1
Enumeration Type Documentation
enum previrt::proto::ActionType
Enumerator
CASE
FORWARD
EVENT
FAIL
Definition at line 103 of file Previrt.pb.h.
enum previrt::proto::FloatSemantics
Enumerator
IEEEhalf
IEEEsingle
IEEEdouble
IEEEquad
x87DoubleExtended
Bogus
PPCDoubleDouble
Definition at line 79 of file Previrt.pb.h.
enum previrt::proto::Type
Enumerator
U
I
F
S
V
N
G
Definition at line 55 of file Previrt.pb.h.
Function Documentation
const ::google::protobuf::EnumDescriptor * previrt::proto::ActionType_descriptor ()
Definition at line 571 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionType_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
Referenced by ActionType_Name(), ActionType_Parse(), and google::protobuf::GetEnumDescriptor< ::previrt::proto::ActionType >().
bool previrt::proto::ActionType_IsValid (int value)
Definition at line 575 of file Previrt.pb.cc.
Referenced by previrt::proto::ActionTree::MergePartialFromCodedStream(), and previrt::proto::ActionTree::set_type().
const ::std::string& previrt::proto::ActionType_Name (ActionType value) inline
Definition at line 115 of file Previrt.pb.h.
References ActionType_descriptor().
bool previrt::proto::ActionType_Parse (const ::std::string & name, ActionType * value) inline
Definition at line 119 of file Previrt.pb.h.
References ActionType_descriptor().
const ::google::protobuf::EnumDescriptor * previrt::proto::FloatSemantics_descriptor ()
Definition at line 552 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::FloatSemantics_descriptor_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
Referenced by FloatSemantics_Name(), FloatSemantics_Parse(), and google::protobuf::GetEnumDescriptor< ::previrt::proto::FloatSemantics >().
bool previrt::proto::FloatSemantics_IsValid (int value)
Definition at line 556 of file Previrt.pb.cc.
Referenced by previrt::proto::PrevirtType_Float::MergePartialFromCodedStream(), and previrt::proto::PrevirtType_Float::set_sem().
const ::std::string& previrt::proto::FloatSemantics_Name (FloatSemantics value) inline
Definition at line 94 of file Previrt.pb.h.
References FloatSemantics_descriptor().
bool previrt::proto::FloatSemantics_Parse (const ::std::string & name, FloatSemantics * value) inline
Definition at line 98 of file Previrt.pb.h.
References FloatSemantics_descriptor().
void previrt::proto::protobuf_AddDesc_Previrt_2eproto ()
Definition at line 436 of file Previrt.pb.cc.
References previrt::proto::PrevirtType_Int::default_instance_, previrt::proto::PrevirtType_Vec::default_instance_, previrt::proto::PrevirtType_Str::default_instance_, previrt::proto::PrevirtType_Float::default_instance_, previrt::proto::PrevirtType_Global::default_instance_, previrt::proto::PrevirtType::default_instance_, previrt::proto::CallInfo::default_instance_, previrt::proto::CallRewrite::default_instance_, previrt::proto::ComponentInterface::default_instance_, previrt::proto::ComponentInterfaceTransform::default_instance_, previrt::proto::ActionTree_Case::default_instance_, previrt::proto::ActionTree_Forward::default_instance_, previrt::proto::ActionTree_Event::default_instance_, previrt::proto::ActionTree::default_instance_, previrt::proto::EnforceInterface_Functions::default_instance_, previrt::proto::EnforceInterface::default_instance_, previrt::proto::PrevirtType_Int::InitAsDefaultInstance(), previrt::proto::PrevirtType_Vec::InitAsDefaultInstance(), previrt::proto::PrevirtType_Str::InitAsDefaultInstance(), previrt::proto::PrevirtType_Float::InitAsDefaultInstance(), previrt::proto::PrevirtType_Global::InitAsDefaultInstance(), previrt::proto::PrevirtType::InitAsDefaultInstance(), previrt::proto::CallInfo::InitAsDefaultInstance(), previrt::proto::CallRewrite::InitAsDefaultInstance(), previrt::proto::ComponentInterface::InitAsDefaultInstance(), previrt::proto::ComponentInterfaceTransform::InitAsDefaultInstance(), previrt::proto::ActionTree_Case::InitAsDefaultInstance(), previrt::proto::ActionTree_Forward::InitAsDefaultInstance(), previrt::proto::ActionTree_Event::InitAsDefaultInstance(), previrt::proto::ActionTree::InitAsDefaultInstance(), previrt::proto::EnforceInterface_Functions::InitAsDefaultInstance(), previrt::proto::EnforceInterface::InitAsDefaultInstance(), previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_RegisterTypes(), and protobuf_ShutdownFile_Previrt_2eproto().
Referenced by protobuf_AssignDesc_Previrt_2eproto(), and previrt::proto::StaticDescriptorInitializer_Previrt_2eproto::StaticDescriptorInitializer_Previrt_2eproto().
void previrt::proto::protobuf_AssignDesc_Previrt_2eproto ()
Definition at line 79 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Case_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Case_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Event_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Event_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Forward_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Forward_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionType_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::CallInfo_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::CallInfo_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::CallRewrite_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::CallRewrite_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ComponentInterface_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ComponentInterface_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ComponentInterfaceTransform_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ComponentInterfaceTransform_reflection_, previrt::proto::PrevirtType_Int::default_instance_, previrt::proto::PrevirtType_Vec::default_instance_, previrt::proto::PrevirtType_Str::default_instance_, previrt::proto::PrevirtType_Float::default_instance_, previrt::proto::PrevirtType_Global::default_instance_, previrt::proto::PrevirtType::default_instance_, previrt::proto::CallInfo::default_instance_, previrt::proto::CallRewrite::default_instance_, previrt::proto::ComponentInterface::default_instance_, previrt::proto::ComponentInterfaceTransform::default_instance_, previrt::proto::ActionTree_Case::default_instance_, previrt::proto::ActionTree_Forward::default_instance_, previrt::proto::ActionTree_Event::default_instance_, previrt::proto::ActionTree::default_instance_, previrt::proto::EnforceInterface_Functions::default_instance_, previrt::proto::EnforceInterface::default_instance_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::EnforceInterface_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::EnforceInterface_Functions_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::EnforceInterface_Functions_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::EnforceInterface_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::FloatSemantics_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Float_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Float_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Global_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Global_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Int_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Int_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Str_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Str_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Vec_descriptor_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Vec_reflection_, protobuf_AddDesc_Previrt_2eproto(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::Type_descriptor_.
Referenced by previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce().
void previrt::proto::protobuf_ShutdownFile_Previrt_2eproto ()
Definition at line 401 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Case_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Event_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_Forward_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ActionTree_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::CallInfo_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::CallRewrite_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ComponentInterface_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::ComponentInterfaceTransform_reflection_, previrt::proto::PrevirtType_Int::default_instance_, previrt::proto::PrevirtType_Vec::default_instance_, previrt::proto::PrevirtType_Str::default_instance_, previrt::proto::PrevirtType_Float::default_instance_, previrt::proto::PrevirtType_Global::default_instance_, previrt::proto::PrevirtType::default_instance_, previrt::proto::CallInfo::default_instance_, previrt::proto::CallRewrite::default_instance_, previrt::proto::ComponentInterface::default_instance_, previrt::proto::ComponentInterfaceTransform::default_instance_, previrt::proto::ActionTree_Case::default_instance_, previrt::proto::ActionTree_Forward::default_instance_, previrt::proto::ActionTree_Event::default_instance_, previrt::proto::ActionTree::default_instance_, previrt::proto::EnforceInterface_Functions::default_instance_, previrt::proto::EnforceInterface::default_instance_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::EnforceInterface_Functions_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::EnforceInterface_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Float_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Global_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Int_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_reflection_, previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Str_reflection_, and previrt::proto::anonymous_namespace{Previrt.pb.cc}::PrevirtType_Vec_reflection_.
Referenced by protobuf_AddDesc_Previrt_2eproto().
const ::google::protobuf::EnumDescriptor * previrt::proto::Type_descriptor ()
Definition at line 533 of file Previrt.pb.cc.
References previrt::proto::anonymous_namespace{Previrt.pb.cc}::protobuf_AssignDescriptorsOnce(), and previrt::proto::anonymous_namespace{Previrt.pb.cc}::Type_descriptor_.
Referenced by google::protobuf::GetEnumDescriptor< ::previrt::proto::Type >(), Type_Name(), and Type_Parse().
bool previrt::proto::Type_IsValid (int value)
Definition at line 537 of file Previrt.pb.cc.
Referenced by previrt::proto::PrevirtType::MergePartialFromCodedStream(), and previrt::proto::PrevirtType::set_type().
const ::std::string& previrt::proto::Type_Name (Type value) inline
Definition at line 70 of file Previrt.pb.h.
References Type_descriptor().
bool previrt::proto::Type_Parse (const ::std::string & name, Type * value) inline
Definition at line 74 of file Previrt.pb.h.
References Type_descriptor().
Variable Documentation
const int previrt::proto::ActionType_ARRAYSIZE = ActionType_MAX + 1
Definition at line 112 of file Previrt.pb.h.
const ActionType previrt::proto::ActionType_MAX = FAIL
Definition at line 111 of file Previrt.pb.h.
const ActionType previrt::proto::ActionType_MIN = CASE
Definition at line 110 of file Previrt.pb.h.
const int previrt::proto::FloatSemantics_ARRAYSIZE = FloatSemantics_MAX + 1
Definition at line 91 of file Previrt.pb.h.
const FloatSemantics previrt::proto::FloatSemantics_MAX = PPCDoubleDouble
Definition at line 90 of file Previrt.pb.h.
const FloatSemantics previrt::proto::FloatSemantics_MIN = IEEEhalf
Definition at line 89 of file Previrt.pb.h.
struct previrt::proto::StaticDescriptorInitializer_Previrt_2eproto previrt::proto::static_descriptor_initializer_Previrt_2eproto_
const int previrt::proto::Type_ARRAYSIZE = Type_MAX + 1
Definition at line 67 of file Previrt.pb.h.
const Type previrt::proto::Type_MAX = G
Definition at line 66 of file Previrt.pb.h.
const Type previrt::proto::Type_MIN = U
Definition at line 65 of file Previrt.pb.h.