Occam - Application Specialization: google::protobuf Namespace Reference
google::protobuf Namespace Reference
Functions
template<>
const EnumDescriptor * GetEnumDescriptor< ::previrt::proto::Type > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::previrt::proto::FloatSemantics > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::previrt::proto::ActionType > ()
Function Documentation
template<> const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::previrt::proto::ActionType > () inline
Definition at line 3465 of file Previrt.pb.h.
References previrt::proto::ActionType_descriptor().
template<> const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::previrt::proto::FloatSemantics > () inline
Definition at line 3461 of file Previrt.pb.h.
References previrt::proto::FloatSemantics_descriptor().
template<> const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::previrt::proto::Type > () inline
Definition at line 3457 of file Previrt.pb.h.
References previrt::proto::Type_descriptor().