Occam - Application Specialization: previrt::SpecializationPolicy Struct Reference
previrt::SpecializationPolicy Struct Reference abstract
#include <SpecializationPolicy.h>
Public Member Functions
virtual ~SpecializationPolicy ()
Default destructor.
virtual void release ()=0
virtual llvm::Value ** specializeOn (llvm::Function *F, llvm::User::op_iterator begin, llvm::User::op_iterator end) const =0
virtual bool specializeOn (llvm::Function *, const PrevirtType *, const PrevirtType *, llvm::SmallBitVector &) const =0
virtual bool specializeOn (llvm::Function *, std::vector< PrevirtType >::const_iterator, std::vector< PrevirtType >::const_iterator, llvm::SmallBitVector &) const =0
Static Public Member Functions
static bool isConstantSpecializable (llvm::Constant *cst)
static SpecializationPolicy * aggressivePolicy ()
static SpecializationPolicy * conservativePolicy ()
static SpecializationPolicy * recursiveGuard (SpecializationPolicy *, llvm::CallGraph &)
Protected Member Functions
SpecializationPolicy ()
Default constructor.
Detailed Description
The SpecializationPolicy is an abstract base class, declaring the methods that must be implemented in derived classes. AggressiveSpecPolicy, ConservativeSpecPolicy and RecursiveGuardSpecPolicy are derived classes implementing the functionality declared in the base class.
Definition at line 62 of file SpecializationPolicy.h.
Constructor & Destructor Documentation
previrt::SpecializationPolicy::SpecializationPolicy () protected
Default constructor.
Definition at line 339 of file StrategySpecializer.cpp.
previrt::SpecializationPolicy::~SpecializationPolicy () virtual
Default destructor.
Definition at line 344 of file StrategySpecializer.cpp.
Member Function Documentation
SpecializationPolicy * previrt::SpecializationPolicy::aggressivePolicy () static
The aggressivePolicy function returns the Singleton instance of AggressiveSpecPolicy
Definition at line 178 of file AggressiveSpecPolicy.cpp.
SpecializationPolicy * previrt::SpecializationPolicy::conservativePolicy () static
Returns the singleton instance of ConservativeSpecPolicy
Definition at line 191 of file ConservativeSpecPolicy.cpp.
static bool previrt::SpecializationPolicy::isConstantSpecializable (llvm::Constant * cst) inline static
The function returns true if the type of the constant, is one of the recognized types for a previrtType
Definition at line 118 of file SpecializationPolicy.h.
References previrt::PrevirtType::abstract(), and previrt::PrevirtType::isConcrete().
SpecializationPolicy * previrt::SpecializationPolicy::recursiveGuard (SpecializationPolicy * policy, llvm::CallGraph & cg) static
The function creates a RecursiveGuardSpecPolicy object and returns the pointer, The RecursiveGuardSpecPolicy constructor is a private constructor and hence the function provides the only gateway to create a RecursiveGuardSpecPolicy object
Definition at line 294 of file RecursiveGuardSpecPolicy.cpp.
virtual void previrt::SpecializationPolicy::release () pure virtual
Implemented in previrt::RecursiveGuardSpecPolicy, previrt::ConservativeSpecPolicy, and previrt::AggressiveSpecPolicy.
Referenced by previrt::RecursiveGuardSpecPolicy::~RecursiveGuardSpecPolicy().
virtual llvm::Value** previrt::SpecializationPolicy::specializeOn (llvm::Function * F, llvm::User::op_iterator begin, llvm::User::op_iterator end) const pure virtual
The specializeOn function is a virtual function, with separate implementations in the derived classes ConservativeSpecPolicy, AggressiveSpecPolicy and RecursiveGuardSpecPolicy. The detailed descriptions of each implementation are as follows:
ConservativeSpecPolicy::specializeOn , AggressiveSpecPolicy::specializeOn detailed description:
The specializeOn method, returns a Value **. Value ** is essentially a array defining the specialization policy against each argument. If an argument is a constant and is can be partially evaluated into the function body, the argument is returned in the array. For arguments cannot be partially evaluated into the function body, their corresponding index in the Value* array is NULL.
RecursiveGuardSpecPolicy::specializeOn detailed description:
The function guards the specialization of recursive functions. It Returns a policy array consisting of a policy against every argument to the function. The array contains NULL values against arguments that cannot be specialized and NON-NULL values against arguments that are to be specialized. The function in turn calls the specializeOn method of the delegate class member. Delegate can be an object of two possible classes: ConservativeSpecPolicy and AggressiveSpecPolicy. If the function is a recursive function, NULL is returned, as recursive functions cannot be specialized. (specialization could result in a large number of specialized versions of the recursive function)
Parameters
F The pointer to the Function being specialized
begin The iterator to the start of the argument list
end The iterator to the end of the argument list.
Implemented in previrt::RecursiveGuardSpecPolicy, previrt::ConservativeSpecPolicy, and previrt::AggressiveSpecPolicy.
Referenced by previrt::SpecializeComponent(), and trySpecializeFunction().
virtual bool previrt::SpecializationPolicy::specializeOn (llvm::Function * , const PrevirtType * , const PrevirtType * , llvm::SmallBitVector &) const pure virtual
Implemented in previrt::RecursiveGuardSpecPolicy, previrt::ConservativeSpecPolicy, and previrt::AggressiveSpecPolicy.
virtual bool previrt::SpecializationPolicy::specializeOn (llvm::Function * , std::vector< PrevirtType >::const_iterator , std::vector< PrevirtType >::const_iterator , llvm::SmallBitVector &) const pure virtual
Implemented in previrt::RecursiveGuardSpecPolicy, previrt::ConservativeSpecPolicy, and previrt::AggressiveSpecPolicy.
The documentation for this struct was generated from the following files:
C:/Users/Hashim/Dropbox/Occam 2.0/src/SpecializationPolicy.h
C:/Users/Hashim/Dropbox/Occam 2.0/src/AggressiveSpecPolicy.cpp
C:/Users/Hashim/Dropbox/Occam 2.0/src/ConservativeSpecPolicy.cpp
C:/Users/Hashim/Dropbox/Occam 2.0/src/RecursiveGuardSpecPolicy.cpp
C:/Users/Hashim/Dropbox/Occam 2.0/src/StrategySpecializer.cpp