Occam - Application Specialization: previrt::WatchEnv Struct Reference
previrt::WatchEnv Struct Reference
Public Member Functions
WatchEnv (WatchContext *ctx)
Constructor, takes as argument a WatchContext and initializes the class data member ctx.
virtual ~WatchEnv ()
Default destructor.
LLVMContext & getContext ()
Return the context of the LLVM module.
void init (Function *f)
Value * lookupValue (int idx) const
bool lookupMatch (int idx, std::string &result) const
Value * materializeMatch (IRBuilder<> &irb, int idx)
bool argRangeAdd (int from, int to, std::vector< Value * > &result) const
argRangeAdd adds a subset of args from the valueEnv vector to the result vector specified by the indices from and to
Public Attributes
std::vector< Value * > valueEnv
vector of the arguments of a function
std::vector< std::string > matchEnv
a vector of function names
std::vector< GlobalVariable * > matchCache
vector of global variables holding function names
int argCount
The number of arguments; size of valueEnv vector.
WatchContext *const context
Detailed Description
Definition at line 116 of file Watch2.cpp.
Constructor & Destructor Documentation
previrt::WatchEnv::WatchEnv (WatchContext * ctx) inline
Constructor, takes as argument a WatchContext and initializes the class data member ctx.
Definition at line 130 of file Watch2.cpp.
virtual previrt::WatchEnv::~WatchEnv () inline virtual
Default destructor.
Definition at line 137 of file Watch2.cpp.
Member Function Documentation
bool previrt::WatchEnv::argRangeAdd (int from, int to, std::vector< Value * > & result) const inline
argRangeAdd adds a subset of args from the valueEnv vector to the result vector specified by the indices from and to
Definition at line 216 of file Watch2.cpp.
Referenced by previrt::getArguments().
LLVMContext& previrt::WatchEnv::getContext () inline
Return the context of the LLVM module.
Definition at line 143 of file Watch2.cpp.
Referenced by previrt::getValue().
void previrt::WatchEnv::init (Function * f) inline
Adding all the arguments of the function to the valueEnv vector (class data member)
Definition at line 150 of file Watch2.cpp.
bool previrt::WatchEnv::lookupMatch (int idx, std::string & result) const inline
Returns the value in matchEnv vector at index idx in a string result passed as reference.
Definition at line 178 of file Watch2.cpp.
Referenced by previrt::WatchContext::getCallFunction().
Value* previrt::WatchEnv::lookupValue (int idx) const inline
Returns an argument at a certain index idx in the valueEnv vector
Definition at line 163 of file Watch2.cpp.
Referenced by previrt::compileAction(), previrt::WatchContext::getCallFunction(), and previrt::getValue().
Value* previrt::WatchEnv::materializeMatch (IRBuilder<> & irb, int idx) inline
Definition at line 193 of file Watch2.cpp.
References previrt::materializeStringLiteral().
Referenced by previrt::getValue().
Member Data Documentation
int previrt::WatchEnv::argCount
The number of arguments; size of valueEnv vector.
Definition at line 125 of file Watch2.cpp.
WatchContext* const previrt::WatchEnv::context
Definition at line 126 of file Watch2.cpp.
std::vector<GlobalVariable*> previrt::WatchEnv::matchCache mutable
vector of global variables holding function names
Definition at line 123 of file Watch2.cpp.
Referenced by previrt::patternMatches().
std::vector<std::string> previrt::WatchEnv::matchEnv
a vector of function names
Definition at line 121 of file Watch2.cpp.
Referenced by previrt::patternMatches().
std::vector<Value*> previrt::WatchEnv::valueEnv
vector of the arguments of a function
Definition at line 119 of file Watch2.cpp.
Referenced by previrt::compileAction(), and previrt::watchFunction().
The documentation for this struct was generated from the following file:
C:/Users/Hashim/Dropbox/Occam 2.0/src/Watch2.cpp