Occam - Application Specialization: previrt::WatchContext Struct Reference
previrt::WatchContext Struct Reference
Public Member Functions
WatchContext (Module *m)
Constructor takes a module m as argument and initializes the class data member module. The watch functions created are added to module.
virtual ~WatchContext ()
Default destructor.
LLVMContext & getContext ()
Return the context of the LLVM Module.
void addAllFunctions ()
Value * getCallFunction (WatchEnv &env, const google::protobuf::RepeatedPtrField< watch::proto::PrimExpr > &exprs, const std::vector< Type * > &types)
Value * getCallFunction (WatchEnv &env, const google::protobuf::RepeatedPtrField< watch::proto::PrimExpr > &exprs, const std::vector< Value * > &values)
The getCallFunction calls the previrt::getCallFunction after computing the types of the values vector sent as an argument.
Public Attributes
std::list< Function * > added_functions
The list containing all the watch functions created, that need to be added to the module.
Module *const module
The module to which the watch functions need to be added.
Detailed Description
The WatchContext class stores the context required for the watch Pass (adding watch functions to the Module). The context includes:
1) The list of functions added_functions that include specialized versions to be added to the module
2) The Module module
Definition at line 80 of file Watch2.cpp.
Constructor & Destructor Documentation
previrt::WatchContext::WatchContext (Module * m) inline
Constructor takes a module m as argument and initializes the class data member module. The watch functions created are added to module.
Definition at line 89 of file Watch2.cpp.
virtual previrt::WatchContext::~WatchContext () inline virtual
Default destructor.
Definition at line 95 of file Watch2.cpp.
Member Function Documentation
void previrt::WatchContext::addAllFunctions ()
Adds all the watch functions created in the list added_functions to the module in the context
Definition at line 249 of file Watch2.cpp.
Referenced by previrt::WatchPass2::runOnModule().
Value * previrt::WatchContext::getCallFunction (WatchEnv & env, const google::protobuf::RepeatedPtrField< watch::proto::PrimExpr > & exprs, const std::vector< Type * > & types)
The previrt::getCallFunction returns the pointer to a Function, that was pushed into the WatchEnv::matchEnv array with the call to previrt::patternMatches. The function pushed was the one that matched the expression in the watch::proto::patternExpr object.
Definition at line 263 of file Watch2.cpp.
References previrt::WatchEnv::lookupMatch(), and previrt::WatchEnv::lookupValue().
Referenced by previrt::compileAction().
Value * previrt::WatchContext::getCallFunction (WatchEnv & env, const google::protobuf::RepeatedPtrField< watch::proto::PrimExpr > & exprs, const std::vector< Value * > & values)
The getCallFunction calls the previrt::getCallFunction after computing the types of the values vector sent as an argument.
Definition at line 353 of file Watch2.cpp.
LLVMContext & previrt::WatchContext::getContext ()
Return the context of the LLVM Module.
Definition at line 242 of file Watch2.cpp.
Referenced by previrt::compileAction(), previrt::getExit(), and previrt::watchFunction().
Member Data Documentation
std::list<Function*> previrt::WatchContext::added_functions
The list containing all the watch functions created, that need to be added to the module.
Definition at line 83 of file Watch2.cpp.
Referenced by previrt::getExit(), and previrt::WatchPass2::runOnModule().
Module* const previrt::WatchContext::module
The module to which the watch functions need to be added.
Definition at line 85 of file Watch2.cpp.
Referenced by previrt::getExit().
The documentation for this struct was generated from the following file:
C:/Users/Hashim/Dropbox/Occam 2.0/src/Watch2.cpp