Application Specialization Python Modules: occam.targets.ld.LdTool Class Reference
occam.targets.ld.LdTool Class Reference
This helper tool for linking.
Public Member Functions
def flags
def shortWithOpt
def longWithOpt
def opts
Returns Options that can passed to this tool using command line.
def occam
Run llvm linker tool llvm-ld .
Public Member Functions inherited from occam.targets.par.ParallelTool
def opts
Returns Options that can passed to this tool using command line.
def occam
def usage
Returns string specifing how to use this tool on command line.
def run
def createLo
Files with extension .lo are library objects which may be built into shared library.
def createLa
Files with extension .la contains description of libraries which enables libtool to make platform independent names.
def fixinputname
This function calls fixname() function which basically checks name of input file and give it a proper extension to work with occam toolchain.
def fixname
Fix the name of file so that we can find the path of file.
Public Member Functions inherited from occam.target.Target
def __init__
Constructor.
def opts
The method is overrided specifically in every tool to return a string defining the set of accepted options.
def usage
The method is overrided specifically in every tool to return a string defining the usage of the Tool.
def desc
The method is overrided specifically in every tool to return a string describing the Tool.
def args
The method is overrided specifically in every tool to return a string containing the set of arguments accepted by the tool.
def help
The function prints the usage, description and the arguments accepted by the Tool.
def run
The run method is overrided in every derived Tool.
Public Member Functions inherited from occam.targets.argparser.ArgParser
def flags
Abstract function that returns list of flags for a tool.
def shortWithOpt
Abstract function.
def longWithOpt
Abstract function.
def extractFlag
Extracts list of flags from the argument passed to a command that is going to be executed as child process.
def parse_args
This method parse the arguments passed to a command.
Additional Inherited Members
Public Attributes inherited from occam.target.Target
name
Detailed Description
This helper tool for linking.
It executes the llvm-ld that takes a set of LLVM bitcode files and links them together into a single LLVM bitcode file.
Member Function Documentation
def occam.targets.ld.LdTool.flags (self)
def occam.targets.ld.LdTool.longWithOpt (self)
def occam.targets.ld.LdTool.occam (self, cfg, args)
Run llvm linker tool llvm-ld .
The llvm-ld tool takes a set of LLVM bitcode files and links them together into a single LLVM bitcode file. The output bitcode file can be another bitcode file or an executable bitcode program. Using additional options, llvm-ld is able to produce native code executables.
References occam.targets.par.ParallelTool.fixinputname(), occam.targets.par.ParallelTool.fixname(), occam.targets.ld.ld_default_o(), occam.target.Target.name, and occam.targets.argparser.ArgParser.parse_args().
Referenced by occam.targets.par.ParallelTool.run().
def occam.targets.ld.LdTool.opts (self, args)
Returns Options that can passed to this tool using command line.
def occam.targets.ld.LdTool.shortWithOpt (self)
The documentation for this class was generated from the following file:
occam/occam/targets/ld.py