My Project: occam.toolchain(Wajih ul hassan's conflicted copy 2013-09-18).LibNotFound Class Reference
occam.toolchain(Wajih ul hassan's conflicted copy 2013-09-18).LibNotFound Class Reference
This class used in printing on display when libary is not found in defined path.
Public Member Functions
def __init__
Constructor.
def __str__
Returns string containing which libray is not found.
Private Attributes
_lib
_path
Detailed Description
This class used in printing on display when libary is not found in defined path.
Constructor & Destructor Documentation
def occam.toolchain(Wajih ul hassan's conflicted copy 2013-09-18).LibNotFound.__init__ (self, lib, path)
Constructor.
Member Function Documentation
def occam.toolchain(Wajih ul hassan's conflicted copy 2013-09-18).LibNotFound.__str__ (self)
Returns string containing which libray is not found.
References occam.toolchain(Wajih ul hassan's conflicted copy 2013-09-18).LibNotFound._lib, and occam.toolchain(Wajih ul hassan's conflicted copy 2013-09-18).LibNotFound._path.
Member Data Documentation
occam.toolchain(Wajih ul hassan's conflicted copy 2013-09-18).LibNotFound._lib private
Referenced by occam.toolchain(Wajih ul hassan's conflicted copy 2013-09-18).LibNotFound.__str__(), and occam.toolchain.LibNotFound.__str__().
occam.toolchain(Wajih ul hassan's conflicted copy 2013-09-18).LibNotFound._path private
Referenced by occam.toolchain(Wajih ul hassan's conflicted copy 2013-09-18).LibNotFound.__str__(), and occam.toolchain.LibNotFound.__str__().
The documentation for this class was generated from the following file:
occam/occam/toolchain (Wajih ul hassan's conflicted copy 2013-09-18).py