Application Specialization Python Modules: occam.targets.previrt.PrevirtTool Class Reference
occam.targets.previrt.PrevirtTool Class Reference
Pre-virtualize a compilation unit based on a manifest file sent as argument to the PrevirtTool Procedure of Pre-virtualization is as follows:
Public Member Functions
def opts
Returns a string of possible options to the tool.
def usage
Returns string specifying the usage of the tool.
def desc
Returns string containing description of the tool.
def args
Returns a string specifying the set of arguments that the tool accepts.
def run
The run method applies the procedure of pre-virtualization to the Module.
Public Member Functions inherited from occam.target.Target
def __init__
Constructor.
def opts
The method is overrided specifically in every tool to return a string defining the set of accepted options.
def usage
The method is overrided specifically in every tool to return a string defining the usage of the Tool.
def desc
The method is overrided specifically in every tool to return a string describing the Tool.
def args
The method is overrided specifically in every tool to return a string containing the set of arguments accepted by the tool.
def help
The function prints the usage, description and the arguments accepted by the Tool.
def run
The run method is overrided in every derived Tool.
Additional Inherited Members
Public Attributes inherited from occam.target.Target
name
Detailed Description
Pre-virtualize a compilation unit based on a manifest file sent as argument to the PrevirtTool Procedure of Pre-virtualization is as follows:
1) Read the configuration in the manifest file.
2) Create watch functions if they are requested.
3) Invoke Passes.interface() that executes the 'Pinterface2' pass with opt which compute the external dependencies of the module, implemented in the C++ library Class previrt::GatherInterface2Pass
4) Invoke passes.intern() : Internalizes the interfaces and perform Dead Code Elimination invoking the 'Poccam' Pass implemented in the C++ library Class previrt::OccamPass.
5) Invoke passes.peval() : Apply a Partial Evaluation Pass, creating specialized functions based on specific usages by invoking the 'Ppeval' Pass, implemented in the C++ library Class ParEvalOptPass .
6) Invoke passes.interface to compute all the external references made from within the modules.
9) Invoke passes.specialize() to create specialized versions of functions based on the Gathered Interfaces that in turn invokes the 'Pspecialize' Pass implemented in the C++ library Class SpecializeComponentPass
10) Invoke passes.rewrite()to rewrite all call-sites corresponding to the specialized functions by invoking the 'Prewrite' Pass implemented in the C++ library Class previrt::RewriteComponentPass
11) prune Dead code.
12) llvm-ld = LLVM linking tool.
Member Function Documentation
def occam.targets.previrt.PrevirtTool.args (self)
Returns a string specifying the set of arguments that the tool accepts.
def occam.targets.previrt.PrevirtTool.desc (self)
Returns string containing description of the tool.
def occam.targets.previrt.PrevirtTool.opts (self, args)
Returns a string of possible options to the tool.
def occam.targets.previrt.PrevirtTool.run (self, cfg, flags, args)
The run method applies the procedure of pre-virtualization to the Module.
References occam.targets.previrt.get_default(), occam.targets.previrt.get_flag(), occam.targets.previrt.get_library(), occam.targets.previrt.get_work_dir(), occam.targets.previrt.InParallel(), and occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).rewrite().
def occam.targets.previrt.PrevirtTool.usage (self)
Returns string specifying the usage of the tool.
References occam.target.Target.name.
The documentation for this class was generated from the following file:
occam/occam/targets/previrt.py