Application Specialization Python Modules: occam.targets.interface.InterfaceTool Class Reference
occam.targets.interface.InterfaceTool Class Reference
Computes the minimal interfaces accross all libraries.
Public Member Functions
def opts
Returns Options that can passed to this tool using command line.
def usage
Returns string specifing how to use this tool on command line.
def desc
Returns string containing description of what this tools does when you execute it on command line.
def run
Executes interface.writeInterface() after computing intefaces.
Public Member Functions inherited from occam.target.Target
def __init__
Constructor.
def opts
The method is overrided specifically in every tool to return a string defining the set of accepted options.
def usage
The method is overrided specifically in every tool to return a string defining the usage of the Tool.
def desc
The method is overrided specifically in every tool to return a string describing the Tool.
def args
The method is overrided specifically in every tool to return a string containing the set of arguments accepted by the tool.
def help
The function prints the usage, description and the arguments accepted by the Tool.
def run
The run method is overrided in every derived Tool.
Additional Inherited Members
Public Attributes inherited from occam.target.Target
name
Detailed Description
Computes the minimal interfaces accross all libraries.
!main! can be used as any interface file name and it will insert the interface that has a single call to main(?,?) which is the default entry point. NOTE: This is only safe if there are no calls into these libraries from modules that are not listed. The tool supports the following usages: output.iface> <input.bc> [<interfaces.iface>+], compute the functions required for input.bc given the calls in the given interface files are the entry points –deep <output.iface> <input.bc>+ –with <interfaces.iface>+" % self.name, recursively compute the minimal interfaces needed for the input bc files and write the cumulative interface to output.iface. The –with parameters specify input interfaces –join <output.iface> <interfaces.iface> Join the given interfaces into a single interface, write the combined interface to stdout"
Member Function Documentation
def occam.targets.interface.InterfaceTool.desc (self)
Returns string containing description of what this tools does when you execute it on command line.
References occam.target.Target.name.
def occam.targets.interface.InterfaceTool.opts (self, args)
Returns Options that can passed to this tool using command line.
def occam.targets.interface.InterfaceTool.run (self, cfg, flags, args)
Executes interface.writeInterface() after computing intefaces.
It also join interface depending on flag.
References occam.targets.interface.deep(), occam.targets.interface.parse(), and occam.targets.interface.shallow().
def occam.targets.interface.InterfaceTool.usage (self)
Returns string specifing how to use this tool on command line.
References occam.target.Target.name.
The documentation for this class was generated from the following file:
occam/occam/targets/interface.py