My Project: occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18) Namespace Reference
occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18) Namespace Reference
Functions
def assemble
################## DEAD FUNCTION Runs llvm assembler on input file using subprocess.
def compileS
################# DEAD FUCNTION Calls asm.assemble which write assembly file .ll .
def compile
Wrapper function to run Clang on 'input_file' in subprocess This method is only called by occam.targets.clang.py Returns subprocess status.
def archive
Runs LLVM ar tool to archive the inputs.
def archive_contents
Archive bitcode file into symbol tables make linking faster.
def symbols
Runs llvm-nm tools.
def archive_to_module
Gather only the files necessary for linking and build a single module for them.
def getSearchPath
Returns the paths used for finding libraries and programs.
def findlib
Search the l(library) in paths argument.
def bundle
Link the bytecode files together as a library, not an executable.
def clean
######################## DEAD FUNCTION
def libarg
############################ DEAD FUCNTION Finds library path given as argument.
def haveBitcode
########################## DEAD FUNCTION
def manifest
Makes manifest file according to given arguments in json format This manifest file is used in BUILD tool to make search of libraries easy or for other things also.
def link
Executes BUILD Tool which excutes llvm-ld on the bitcode file.
def watch
Runs opt(llvm) with addtional arguments for watches pass.
def callgraph
#################### DEAD FUNCTION Executes Standard opt(llvm) pass dot-callgraph.
Function Documentation
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).archive (action, inputs, ar)
Runs LLVM ar tool to archive the inputs.
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).archive_contents (archive)
Archive bitcode file into symbol tables make linking faster.
Returns list of names of members. Used in occam.toolchain.archive_to_module() where members
Referenced by occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).archive_to_module().
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).archive_to_module (input_file, output_file, minimal = None)
Gather only the files necessary for linking and build a single module for them.
This is useful/necessary to remove dead assembly from libc. Excutes llvm-ar tool on input file which outputs a archive which is then fed into llvm-ld with link-as-library flag which combines all contents into library.
References occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).archive_contents(), and occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).symbols().
Referenced by occam.targets.arlink.ArLinkTool.run().
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).assemble (input_file, output_file, args)
################## DEAD FUNCTION Runs llvm assembler on input file using subprocess.
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).bundle (output, inputs, libs, paths)
Link the bytecode files together as a library, not an executable.
In this mode, undefined symbols will be permitted. Utility method for the ld and clang tool defined in occam toolchain.
References occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).findlib().
Referenced by occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).link().
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).callgraph (input_file, output_file)
#################### DEAD FUNCTION Executes Standard opt(llvm) pass dot-callgraph.
This pass Print Call Graph to 'dot' file. Return code of subprocess which gives the status of program execution.
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).clean (input_file, output_file)
######################## DEAD FUNCTION
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).compile (input_files, output_file, args, tool = 'clang')
Wrapper function to run Clang on 'input_file' in subprocess This method is only called by occam.targets.clang.py Returns subprocess status.
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).compileS (input_file, output_file, args, tool = 'gcc')
################# DEAD FUCNTION Calls asm.assemble which write assembly file .ll .
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).findlib (l, paths)
Search the l(library) in paths argument.
First find in OCCAM_LIB_PATH environmental variable, then make path of library and check if this path exists. then call occam.toolchain.getSearchPath() to find path again.
Returns null if library is not found in paths list.
References occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).getSearchPath().
Referenced by occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).bundle(), occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).haveBitcode(), and occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).libarg().
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).getSearchPath ()
Returns the paths used for finding libraries and programs.
which is then used the Build tool(which runs llvm-ld) for linking libraries.
Referenced by occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).findlib(), and occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).link().
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).haveBitcode (l, paths)
########################## DEAD FUNCTION
References occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).findlib().
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).libarg (l, paths)
############################ DEAD FUCNTION Finds library path given as argument.
Returns the full path of library or just -l+library.
References occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).findlib().
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).link (inputs, output_file, args, save = None, link = True)
Executes BUILD Tool which excutes llvm-ld on the bitcode file.
The basic steps of execution are as follows:- 1) First find list of path given in command line argument 2) Then list of libraries from argumnts 3) Then list of native libraries 4) Then runs llvm ld tool Method is used by clang and ld tool defined in occam toolchain.
References occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).bundle(), occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).getSearchPath(), occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).manifest(), and occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).watch().
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).manifest (filename, exe, lib, libs = [], nativelibs = [], search = [], shared = [])
Makes manifest file according to given arguments in json format This manifest file is used in BUILD tool to make search of libraries easy or for other things also.
Referenced by occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).link().
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).symbols (obj)
Runs llvm-nm tools.
Makes symbols tables from bitcode files or ar archive It retuns "address , code character, name for symbol" per line
Referenced by occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).archive_to_module().
def occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).watch (input_file, output_file, watches, local = False, fancy = False, failName = 'exit')
Runs opt(llvm) with addtional arguments for watches pass.
This pass watch/enforce an interface inside functions. -Pwatch2-input= Interfaces to watch. -Pwatch2-local= allow local calls to the function Pwatch2-fail= name of function to call.
Referenced by occam.toolchain (Wajih ul hassan's conflicted copy 2013-09-18).link().