Application Specialization Python Modules: occam.driver Namespace Reference
occam.driver Namespace Reference
Classes
class ReturnCode
When subprocess.popen() is called it returns a number to describe the status of process.
Functions
def open_input
Provides abstraction to open file and return its handle.
def runUnknown
When any tool was run and tool module is not found in targets package, then this function is called.
def run
Executes the program given in the argument using subprocess.popen().
def all_args
make list of pairs with first element as first argument and second element one element each from list of args.
def previrt
Executes opt(llvm) with additional pass names defined in libpervirt.so.
def previrt_progress
Opens subprocess executing opt(llvm) with pass names, then logs the return code, errors etc.
def isLLVM
####### DEAD FUNCTION NOt called from anywhere Runs linux file command for recognizing the type of data contained in a computer file f.
Function Documentation
def occam.driver.all_args (opt, args)
make list of pairs with first element as first argument and second element one element each from list of args.
Parameters
opt= name of opt pass.(defined in libprevirt.so)
args= list of names of files on which opt pass is to be applied.For example list of interface files.
Returns
List of pairs of opt pass name and files names.
Referenced by occam.passes.enforce(), occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).enforce(), occam.passes.interface(), occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).interface(), occam.passes.intern(), occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).intern(), occam.passes.rewrite(), occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).rewrite(), occam.passes.specialize(), and occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).specialize().
def occam.driver.isLLVM (f)
####### DEAD FUNCTION NOt called from anywhere Runs linux file command for recognizing the type of data contained in a computer file f.
def occam.driver.open_input (fn)
Provides abstraction to open file and return its handle.
Opens the file with the name given as argument. But if nothing is passed in arguments this function opens standard input. This function is used in context of logging in which this function opens the file then read() function is called on handle.
Parameters
fn=file name the handle of opened file.
def occam.driver.previrt (fin, fout, args, opts)
Executes opt(llvm) with additional pass names defined in libpervirt.so.
Parameters
fin= Input file to which opt pass is to be applied
fout= Output file name which is generated by opt pass
Returns
Return code of the subprocess.popen() which gives the status of the process.
References occam.driver.run().
Referenced by occam.passes.enforce(), occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).enforce(), occam.passes.interface(), occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).interface(), occam.passes.specialize(), occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).specialize(), occam.passes.specialize_program_args(), and occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).specialize_program_args().
def occam.driver.previrt_progress (fin, fout, args, output = None, opts)
Opens subprocess executing opt(llvm) with pass names, then logs the return code, errors etc.
Parameters
fin= Input file to which opt pass is to be applied
fout= Output file name which is generated by opt pass
args = additional opt pass arguments.
Returns
Return code of the subprocess.popen() which gives the status of the process. It returns the progress status if any function is specialize it returns true OTHERWISE return false. The basic purpose of this is that if return is true you run partial evaluation again and again untill nothing is to partial evaluate or specialize. This ...progress... feature is defined in three passes Poccam, Prewrite, Ppeval.
Referenced by occam.passes.intern(), occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).intern(), occam.passes.peval(), occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).peval(), occam.passes.rewrite(), and occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).rewrite().
def occam.driver.run (prog, args, quiet = False, inp = None, pipe = True, wd = None, resetPath = True)
Executes the program given in the argument using subprocess.popen().
In occam context it excutes the various tools defiened in the occam toolchain or excecutes the LLVM tools. If the error occurs in subprocess it calls ReturnCode() which stores returns string of exception in formated.
Parameters
prog = pragram to excute as child process. For example, llvm-ld opt
args = arguments to program which is going to be excuted. For example, input and output file names.
inp = Defines the inputfile for the child process stdin.
pipe = indicates that a new pipe to standard stream should be opened for stdout.
Returns
Return code of the subprocess.popen() which gives the status of the process.
Referenced by occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).callgraph(), occam.passes.callgraph(), occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).optimize(), occam.passes.optimize(), occam.driver.previrt(), occam.passes.strip(), and occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).strip().
def occam.driver.runUnknown (tool, args)
When any tool was run and tool module is not found in targets package, then this function is called.
Finds the tool path given in argument and executes using subprocess. Finds the path of tool using OCCAM_PROTECTED_PATH environmental variable and then open subprocess using that tool path. OCCAM_PROTECT_PATH environmental variable is when set, occam will remove all non-occam items from the path and intercept calls to common executables so that they can be logged at level INFO. Can be useful for debugging a build that isn't working properly.
Parameters
tool= tool name that user want to run
args= names of arguments to tool that wanted to be run.
Returns
ReturnCode of subprocess which shows status of program.
    Returns Path after if argument path exits.
References occam.genconfig.which().