Application Specialization Python Modules: occam.passes (Wajih ul hassan's conflicted copy 2013-10-04) Namespace Reference
occam.passes (Wajih ul hassan's conflicted copy 2013-10-04) Namespace Reference
Functions
def interface
RUNS llvm opt with interface passes.
def specialize
Runs opt(llvm) with Pspecialize pass.
def rewrite
Executes opt(llvm) with Prewrite pass using driver.previrt_progress()
def intern
Executs opt(llvm) with poccam pass using occam.driver.previrt_progress() intern calls Poccam which internalizes the interfaces and does dead code elimination.
def strip
Runs opt(llvm) with all deadcode elimation passes.These are standard passes.
def enforce
########## THIS FUNCTION IS DEAD Executes opt(llvm) Penforece pass.
def peval
Executes opt(llvm) with Ppeval pass.
def callgraph
Executes Standard opt(llvm) pass dot-callgraph.
def optimize
Executs opt(llvm) with standard 'O3' and 'disable-simplify-libcalls' passes disable-simplify-libcalls= This pass disable Simplify well-known library calls¶.
def specialize_program_args
Executes opt(llvm) to run Pargument pass.
def deep
compute interfaces across modules Join all interfaces then write interface.
Function Documentation
def occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).callgraph (input_file, output_file, opts)
Executes Standard opt(llvm) pass dot-callgraph.
This pass Print Call Graph to 'dot' file. Return code of subprocess which gives the status of program execution.
References occam.driver.run().
def occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).deep (libs, ifaces)
compute interfaces across modules Join all interfaces then write interface.
References occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).interface().
def occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).enforce (input_file, output_file, interfaces, inside, opts)
########## THIS FUNCTION IS DEAD Executes opt(llvm) Penforece pass.
Calls the enforceInterfaceInside and enforeInterfaceOutside Classes in the enforceInterface.cpp file
References occam.driver.all_args(), and occam.driver.previrt().
def occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).interface (input_file, output_file, wrt, opts)
RUNS llvm opt with interface passes.
Runs Pinterface2 pass with opt which compute the external dependencies of the module. Pass is defined in GatherInterface2.cpp
Pinterface2-output = specifies the output file for the interface description. Pinterface2-entry= specifies the interface that is used(only the function names).
Parameters
input_file =
output_file= .iface file
Returns
Return code of the subprocess.popen() which gives the status of the process.
References occam.driver.all_args(), and occam.driver.previrt().
Referenced by occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).deep().
def occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).intern (input_file, output_file, interfaces, opts)
Executs opt(llvm) with poccam pass using occam.driver.previrt_progress() intern calls Poccam which internalizes the interfaces and does dead code elimination.
Actually it hides/removes all non-external dependencies.
Parameters
interfaces= list of .iface which is a serialiezd object of ComponentInterface cantaining information about references.
References occam.driver.all_args(), and occam.driver.previrt_progress().
def occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).optimize (input_file, output_file, opts)
Executs opt(llvm) with standard 'O3' and 'disable-simplify-libcalls' passes disable-simplify-libcalls= This pass disable Simplify well-known library calls¶.
like exit(3) changes to return 3 when this is not disabled. O3= O3 level optimization.
References occam.driver.run().
Referenced by occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).peval().
def occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).peval (input_file, output_file, log = None, trail = None, opts)
Executes opt(llvm) with Ppeval pass.
Ppeval pass is partial evaluation pass(inlining) which apply standard partial evaluation techniques to specialize functions.
intra module previrtualization
References occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).optimize(), and occam.driver.previrt_progress().
def occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).rewrite (input_file, output_file, rewrites, debug = None, opts)
Executes opt(llvm) with Prewrite pass using driver.previrt_progress()
This pass previrtualize the given module(requires parameters) The Pass takes an argument (required argument) 'Prewrite-input' flag followed by a file name that specifies the interface to rewrite using (a buffer of type previrt::proto::ComponentInterfaceTransform). Prewrite-input= specifies the interface to rewrite using .iface file.
Parameters
input_file = .bc file name
output_file= .bc file name
rewrites= list containing a serialized object of ComponentInterfaceTransoform- containing the information for rewriting call sites; function name and the set of arguments.
References occam.driver.all_args(), and occam.driver.previrt_progress().
Referenced by occam.targets.previrt.PrevirtTool.run().
def occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).specialize (input_file, output_file, rewrite_file, interfaces, opts)
Runs opt(llvm) with Pspecialize pass.
Pspecialize pass previrualize the given module (requires parameter). The pass is a phase of inter-module specialization. Creating specialized functions corresponding to their specific usages Pspecialize-input specifies the interface to specialize with respect to. Pspecialize-output specifies the output file for the rewrite specification. inter module specialization, rewrite_file and output_file and the file names for the output files
References occam.driver.all_args(), and occam.driver.previrt().
def occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).specialize_program_args (input_file, output_file, args, fn = None, name = None)
Executes opt(llvm) to run Pargument pass.
This pass specialize main() function arguments from the file 'argumetns' -Parguments-input= Specifies the input file containing program arguments. -Parguments-name=Specifies the program name.
References occam.driver.previrt().
def occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).strip (input_file, output_file, opts)
Runs opt(llvm) with all deadcode elimation passes.These are standard passes.
opt passes used in this function are defined below:- -globaldce= Dead code elimination. This transform is designed to eliminate unreachable internal globals from the program. -strip = Strip all symbols from a module.Strip utility is used for reducing code size. -globalopt= Global Variable Optimizer.This pass transforms simple global variables that never have their address taken. -strip-dead-prototypes= Strip Unused Function Prototypes.This pass loops over all of the functions in the input module, looking for dead declarations and removes them
References occam.driver.run().
Referenced by occam.genconfig.llvm(), occam.genconfig.occam(), occam.interface.readInterfaceFromText(), and occam.genconfig.which().