Application Specialization Python Modules: occam.watchparse Namespace Reference
occam.watchparse Namespace Reference
Functions
def t_LIT
def t_ID
def t_VAR
def t_REL
def t_error
def p_watches
watches : watch watches : watch watches
def p_watch
def p_action_forward
def p_action_fail
def p_args
args : args : VAR args : VAR ',' args
def p_action_event
action : SIGNAL ID '(' args ')' ';' action action : SIGNAL ID '(' args ')'
def p_action_if
action : IF '(' VAR REL LIT ')' THEN '{' action '}' ELSE '{' action '}'
def p_error
def build_interface
def parse
def parseInto
Variables
tuple PARSE_DIR = os.path.join(os.path.dirname(__file__), 'ply')
dictionary reserved
list tokens
string literals = "(){},;"
string t_ignore_COMMENT = r'\#.*'
string t_ignore = ' \r\n\t'
tuple lexer = lex.lex(lextab='watchlex',outputdir=PARSE_DIR)
tuple parser = yacc.yacc(outputdir=PARSE_DIR,debug=0)
tuple f = open('watch', 'wb')
Function Documentation
def occam.watchparse.build_interface (watches, into)
Referenced by occam.watchparse.parseInto().
def occam.watchparse.p_action_event (p)
action : SIGNAL ID '(' args ')' ';' action action : SIGNAL ID '(' args ')'
def occam.watchparse.p_action_fail (p)
def occam.watchparse.p_action_forward (p)
def occam.watchparse.p_action_if (p)
action : IF '(' VAR REL LIT ')' THEN '{' action '}' ELSE '{' action '}'
def occam.watchparse.p_args (p)
args : args : VAR args : VAR ',' args
def occam.watchparse.p_error (p)
def occam.watchparse.p_watch (p)
def occam.watchparse.p_watches (p)
watches : watch watches : watch watches
def occam.watchparse.parse (s)
References occam.watchparse.parseInto().
def occam.watchparse.parseInto (proto, s)
Parameters
proto is a proto.EnforceInterface object
s is a string containing the file contents
References occam.watchparse.build_interface().
Referenced by occam.watchparse.parse().
def occam.watchparse.t_error (t)
def occam.watchparse.t_ID (t)
def occam.watchparse.t_LIT (t)
def occam.watchparse.t_REL (t)
def occam.watchparse.t_VAR (t)
Variable Documentation
tuple occam.watchparse.f = open('watch', 'wb')
Referenced by occam.pool.ThreadPool.map(), and occam.pool.Worker.run().
tuple occam.watchparse.lexer = lex.lex(lextab='watchlex',outputdir=PARSE_DIR)
string occam.watchparse.literals = "(){},;"
tuple occam.watchparse.PARSE_DIR = os.path.join(os.path.dirname(__file__), 'ply')
tuple occam.watchparse.parser = yacc.yacc(outputdir=PARSE_DIR,debug=0)
dictionary occam.watchparse.reserved
Initial value:
 = {
     'if' : "IF",
     'then' : "THEN",
     'else' : "ELSE",
     'fail' : "FAIL",
     'forward' : "FORWARD",
     'signal'  : "SIGNAL"
 }
string occam.watchparse.t_ignore = ' \r\n\t'
string occam.watchparse.t_ignore_COMMENT = r'\#.*'
list occam.watchparse.tokens
Initial value:
 = [
     "VAR" ,
     "LIT" ,
     "REL" ,
     "ID"
 ]