Application Specialization Python Modules: occam.genconfig Namespace Reference
occam.genconfig Namespace Reference
Functions
def which
Executes the "which" linux command that searches the path of executable in system paths set in PATH environment variable.
def llvm
Finds excutable path of argument in llvm/bin directory.
def occam
Finds path directory of the given argument executable.
def std
Simply returns the input.
Variables
tuple libprevirt = os.getenv('OCCAM_LIB')
Function Documentation
def occam.genconfig.llvm (name)
Finds excutable path of argument in llvm/bin directory.
Or excutes linux which command to find path of executable.
Parameters
name= name of executable file whose path has to be found.
Returns
Full path of executable.
References occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).strip().
def occam.genconfig.occam (name)
Finds path directory of the given argument executable.
Parameters
name = name of executable file whose path has to be found.
Returns
full path of executable.
References occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).strip().
def occam.genconfig.std (name)
Simply returns the input.
def occam.genconfig.which (name)
Executes the "which" linux command that searches the path of executable in system paths set in PATH environment variable.
Returns full path of input executable.
Parameters
name= name of the file whose path executable is to be find.
Returns
Path of executable.
References occam.passes (Wajih ul hassan's conflicted copy 2013-10-04).strip().
Referenced by occam.driver.runUnknown().
Variable Documentation
tuple occam.genconfig.libprevirt = os.getenv('OCCAM_LIB')