Application Specialization Python Modules: occam.asm Namespace Reference
occam.asm Namespace Reference
Classes
class Ptrn1
This class checks the pattern for the function signature using regular expressions.
class Ptrn2
Checks the pattern for the function signature using regular expressions.
Functions
def removeComments
Removes Comments from the string after matching patterns.
def getcppargs
def getLabels
Compute undefined labels in assembly code file input_file Uses LLVM nm tool to get list of symbols from bc file.
def writeRequiredProvided
LLVM.used global variable array consist of list of pointers to named global variables.
def assemble
Logs the logger and then open the subprocess.
Variables
tuple ptrn = re.compile(r'\/\*.+?\*\/', re.MULTILINE)
list CPP_OPTS = ['-fPIC', '-fpic']
Function Documentation
def occam.asm.assemble (input_file, output_file, args)
Logs the logger and then open the subprocess.
Then agains logs the logger. Then makes input_file.ll file and writes header for LLVM assembly. Fromat of assembly:- Module ID, Target datalayout, Target Triple, module asm.
If arguments starts with '@' sigil then replace it with '%';
References occam.asm.getcppargs(), occam.asm.getLabels(), and occam.asm.writeRequiredProvided().
def occam.asm.getcppargs (args)
Referenced by occam.asm.assemble().
def occam.asm.getLabels (input_file, args)
Compute undefined labels in assembly code file input_file Uses LLVM nm tool to get list of symbols from bc file.
Finds all the symbols with keys U and T .
Returns
dict of undefined symbols.
Referenced by occam.asm.assemble().
def occam.asm.removeComments (f)
Removes Comments from the string after matching patterns.
Parameters
f string.
Returns
string without comments.
def occam.asm.writeRequiredProvided (out, sym, ls)
LLVM.used global variable array consist of list of pointers to named global variables.
Referenced by occam.asm.assemble().
Variable Documentation
list occam.asm.CPP_OPTS = ['-fPIC', '-fpic']
tuple occam.asm.ptrn = re.compile(r'\/\*.+?\*\/', re.MULTILINE)