Application Specialization Python Modules: occam.toolchain Namespace Reference
occam.toolchain Namespace Reference
Classes
class LibNotFound
This class used in printing on display when libary is not found in defined path.
Functions
def assemble
################## DEAD FUNCTION Runs llvm assembler on input file using subprocess.
def compileS
################# DEAD FUCNTION Calls asm.assemble which write assembly file .ll .
def compile
Wrapper function to run Clang on 'input_file' in subprocess This method is only called by occam.targets.clang.py Returns subprocess status.
def archive
Runs LLVM ar tool to archive the inputs.
def archive_contents
Archive bitcode file into symbol tables make linking faster.
def symbols
Runs llvm-nm tools.
def archive_to_module
Makes archive then uses this in llvm-ld to make linking fast.
def getSearchPath
Returns the paths used for finding libraries and programs.
def findlib
Search the l(library) in paths argument.
def bundle
Link the bytecode files together as a library, not an executable.
def clean
######################## DEAD FUNCTION
def libarg
############################ DEAD FUCNTION Finds library path given as argument.
def haveBitcode
########################## DEAD FUNCTION
def manifest
Makes manifest file according to given arguments in json format This manifest file is used in BUILD tool to make search of libraries easy or for other things also.
def link
This method is executs Build tool that links that builds executable files from .manifest file and input bitcode file using llvm-ld tool.
def watch
Runs llvm opt with addtional arguments for watches pass.
def callgraph
Runs llvm opt with the call graph arguments.
Function Documentation
def occam.toolchain.archive (action, inputs, ar)
Runs LLVM ar tool to archive the inputs.
llvm-ar is to common UNIX utility ar. It archive several files together into single file. The intent for this is to produce archive libraries LLVM bitcode that can be linked into an LLVM program.
def occam.toolchain.archive_contents (archive)
Archive bitcode file into symbol tables make linking faster.
Returns list of names of members. Used in occam.toolchain.archive_to_module() where members
Referenced by occam.toolchain.archive_to_module().
def occam.toolchain.archive_to_module (input_file, output_file, minimal = None)
Makes archive then uses this in llvm-ld to make linking fast.
Basically runs llvm-ar tool on input file then contents returned by this tools are fed into llvm-ld tool with link as library flag which combine all contents into library.
References occam.toolchain.archive_contents(), and occam.toolchain.symbols().
Referenced by occam.targets.arlink.ArLinkTool.run().
def occam.toolchain.assemble (input_file, output_file, args)
################## DEAD FUNCTION Runs llvm assembler on input file using subprocess.
def occam.toolchain.bundle (output, inputs, libs, paths)
Link the bytecode files together as a library, not an executable.
In this mode, undefined symbols will be permitted. Utility method for the ld and clang tool defined in occam toolchain.
References occam.toolchain.findlib().
Referenced by occam.toolchain.link().
def occam.toolchain.callgraph (input_file, output_file)
Runs llvm opt with the call graph arguments.
def occam.toolchain.clean (input_file, output_file)
######################## DEAD FUNCTION
def occam.toolchain.compile (input_files, output_file, args, tool = 'clang')
Wrapper function to run Clang on 'input_file' in subprocess This method is only called by occam.targets.clang.py Returns subprocess status.
def occam.toolchain.compileS (input_file, output_file, args, tool = 'gcc')
################# DEAD FUCNTION Calls asm.assemble which write assembly file .ll .
def occam.toolchain.findlib (l, paths)
Search the l(library) in paths argument.
First find in OCCAM_LIB_PATH environmental variable, then make path of library and check if this path exists. then call occam.toolchain.getSearchPath() to find path again.
Returns null if library is not found in paths list.
References occam.toolchain.getSearchPath().
Referenced by occam.toolchain.bundle(), occam.toolchain.haveBitcode(), and occam.toolchain.libarg().
def occam.toolchain.getSearchPath ()
Returns the paths used for finding libraries and programs.
which is then used the Build tool(which runs llvm-ld) for linking libraries.
Referenced by occam.toolchain.findlib(), and occam.toolchain.link().
def occam.toolchain.haveBitcode (l, paths)
########################## DEAD FUNCTION
References occam.toolchain.findlib().
def occam.toolchain.libarg (l, paths)
############################ DEAD FUCNTION Finds library path given as argument.
Returns the full path of library or just -l+library.
References occam.toolchain.findlib().
def occam.toolchain.link (inputs, output_file, args, save = None, link = True)
This method is executs Build tool that links that builds executable files from .manifest file and input bitcode file using llvm-ld tool.
This functions executes in this manner First find list of path given in command line argument then list of libraries from argumnts then list of native libraries then runs llvm ld tool
References occam.toolchain.bundle(), occam.toolchain.getSearchPath(), occam.toolchain.manifest(), and occam.toolchain.watch().
def occam.toolchain.manifest (filename, exe, lib, libs = [], nativelibs = [], search = [], shared = [])
Makes manifest file according to given arguments in json format This manifest file is used in BUILD tool to make search of libraries easy or for other things also.
Referenced by occam.toolchain.link().
def occam.toolchain.symbols (obj)
Runs llvm-nm tools.
Makes symbols tables from bitcode files or ar archive It retuns "address , code character, name for symbol" per line
Referenced by occam.toolchain.archive_to_module().
def occam.toolchain.watch (input_file, output_file, watches, local = False, fancy = False, failName = 'exit')
Runs llvm opt with addtional arguments for watches pass.
Referenced by occam.toolchain.link().