Application Specialization Python Modules: occam.formats Namespace Reference
occam.formats Namespace Reference
Classes
class Format
class InterfaceFormat
class InterfaceTransformFormat
Functions
def cstr
def string_of_PrevirtType
def showCall
def showRewrite
Function Documentation
def occam.formats.cstr (s)
Referenced by occam.formats.string_of_PrevirtType().
def occam.formats.showCall (c)
References occam.formats.string_of_PrevirtType().
Referenced by occam.formats.InterfaceFormat.show(), and occam.formats.InterfaceTransformFormat.show().
def occam.formats.showRewrite (rw)
References occam.formats.string_of_PrevirtType().
Referenced by occam.formats.InterfaceTransformFormat.show().
def occam.formats.string_of_PrevirtType (pt, any_str)
References occam.formats.cstr().
Referenced by occam.formats.showCall(), and occam.formats.showRewrite().