Application Specialization Python Modules: occam.targets.previrt Namespace Reference
occam.targets.previrt Namespace Reference
Classes
class NotFound
class PrevirtTool
Pre-virtualize a compilation unit based on a manifest file sent as argument to the PrevirtTool Procedure of Pre-virtualization is as follows:
Functions
def get_flag
def get_work_dir
def collect_files
def get_library
def get_default
def defaultPool
Creates a thread pool of 3 threads.
def InParallel
The InParallel routine executes the function f in parallel threads, with a different set of arguments to each of the instance of the threads.
def occamRoot
Returns path of OCCAM_HOME (directory where occam is installed).
Variables
POOL = None
Function Documentation
def occam.targets.previrt.collect_files (mani)
def occam.targets.previrt.defaultPool ()
Creates a thread pool of 3 threads.
Each thread executes a Pass over a module. If a Pass is to be applied to a number of modules, the efficiency is improved by executing them in parallel using multi-threading
Referenced by occam.targets.previrt.InParallel().
def occam.targets.previrt.get_default (obj, key, default)
Referenced by occam.targets.previrt.PrevirtTool.run().
def occam.targets.previrt.get_flag (flags, flag, default = None)
Referenced by occam.targets.previrt.get_work_dir(), and occam.targets.previrt.PrevirtTool.run().
def occam.targets.previrt.get_library (lib, paths)
Referenced by occam.targets.previrt.PrevirtTool.run().
def occam.targets.previrt.get_work_dir (flags)
References occam.targets.previrt.get_flag().
Referenced by occam.targets.previrt.PrevirtTool.run().
def occam.targets.previrt.InParallel (f, args, pool = None)
The InParallel routine executes the function f in parallel threads, with a different set of arguments to each of the instance of the threads.
When a Pass is to be applied to a number of modules, multi-threading improves run time efficiency.
References occam.targets.previrt.defaultPool().
Referenced by occam.targets.previrt.PrevirtTool.run().
def occam.targets.previrt.occamRoot ()
Returns path of OCCAM_HOME (directory where occam is installed).
Variable Documentation
occam.targets.previrt.POOL = None