Application Specialization Python Modules: occam.watchparse2 Namespace Reference
occam.watchparse2 Namespace Reference
Functions
def t_STR
def t_RE
def t_INT
def t_ID
def t_VAR
def t_MVAR
def t_REL
def t_error
def p_watches
watches : watch watches : watch watches
def p_pattern
pattern : RE pattern : RE match_pred
def p_strings
strings : strings : STR strings : STR ',' strings
def p_match_pred
match_pred : ':' EXCLUDE '[' strings ']'
def p_watch
def p_action_forward
def p_action_fail
def p_args
args : args : VAR args : VAR ',' args
def p_action_seq
action_seq : action ';' action_seq action_seq : action
def p_action_block
action : '{' action_seq '}'
def p_prim_expr_str
def p_prim_expr_int
def p_prim_expr_var
def p_prim_expr_mvar
def p_prim_expr_list
prim_expr_list : prim_expr prim_expr_list : prim_expr prim_expr_list
def p_prim_exprs_prim_expr
prim_exprs : prim_expr
def p_prim_exprs
prim_exprs : ELIPSIS prim_exprs : INT ELIPSIS INT
def p_prim_exprs_list
prim_exprs_list : prim_exprs_list : prim_exprs prim_exprs_list : prim_exprs ',' prim_exprs_list
def p_action_return1
action : RETURN prim_expr
def p_action_return
action : RETURN action : RETURN UNDEF
def p_action_call
action : CALL prim_expr '(' prim_exprs_list ')' action : CALL '[' prim_expr_list ']' '(' prim_exprs_list ')'
def p_action_if
action : IF '(' VAR REL INT ')' THEN action action : IF '(' VAR REL INT ')' THEN action ELSE action
def p_error
def compileHook
def build_interface
the routine merges the Hooks in the watches parsed object into the into WatchInterface object (Google Protocol Buffer)
def parse
The routine creates an empty wproto.WatchInterface object and calls parseInto with the object wproto.WatchInterface and the string s as arguments.
def parseInto
The parseInto routine calls the build_interface function with the the parsed object returned from parser.parse(), along with the proto object as input.
Variables
tuple PARSE_DIR = os.path.join(os.path.dirname(__file__), 'ply')
dictionary reserved
list tokens
string literals = "[](){},;:"
string t_ignore = ' \r\n\t'
tuple lexer = lex.lex(lextab='watchlex2',outputdir=PARSE_DIR)
tuple parser = yacc.yacc(outputdir=PARSE_DIR,debug=0)
Function Documentation
def occam.watchparse2.build_interface (watches, into)
the routine merges the Hooks in the watches parsed object into the into WatchInterface object (Google Protocol Buffer)
Referenced by occam.watchparse2.parseInto().
def occam.watchparse2.compileHook (name, args, body)
Referenced by occam.watchparse2.p_watch().
def occam.watchparse2.p_action_block (p)
action : '{' action_seq '}'
def occam.watchparse2.p_action_call (p)
action : CALL prim_expr '(' prim_exprs_list ')' action : CALL '[' prim_expr_list ']' '(' prim_exprs_list ')'
def occam.watchparse2.p_action_fail (p)
def occam.watchparse2.p_action_forward (p)
def occam.watchparse2.p_action_if (p)
action : IF '(' VAR REL INT ')' THEN action action : IF '(' VAR REL INT ')' THEN action ELSE action
def occam.watchparse2.p_action_return (p)
action : RETURN action : RETURN UNDEF
def occam.watchparse2.p_action_return1 (p)
action : RETURN prim_expr
def occam.watchparse2.p_action_seq (p)
action_seq : action ';' action_seq action_seq : action
def occam.watchparse2.p_args (p)
args : args : VAR args : VAR ',' args
def occam.watchparse2.p_error (p)
def occam.watchparse2.p_match_pred (p)
match_pred : ':' EXCLUDE '[' strings ']'
def occam.watchparse2.p_pattern (p)
pattern : RE pattern : RE match_pred
def occam.watchparse2.p_prim_expr_int (p)
def occam.watchparse2.p_prim_expr_list (p)
prim_expr_list : prim_expr prim_expr_list : prim_expr prim_expr_list
def occam.watchparse2.p_prim_expr_mvar (p)
def occam.watchparse2.p_prim_expr_str (p)
def occam.watchparse2.p_prim_expr_var (p)
def occam.watchparse2.p_prim_exprs (p)
prim_exprs : ELIPSIS prim_exprs : INT ELIPSIS INT
def occam.watchparse2.p_prim_exprs_list (p)
prim_exprs_list : prim_exprs_list : prim_exprs prim_exprs_list : prim_exprs ',' prim_exprs_list
def occam.watchparse2.p_prim_exprs_prim_expr (p)
prim_exprs : prim_expr
def occam.watchparse2.p_strings (p)
strings : strings : STR strings : STR ',' strings
def occam.watchparse2.p_watch (p)
References occam.watchparse2.compileHook().
def occam.watchparse2.p_watches (p)
watches : watch watches : watch watches
def occam.watchparse2.parse (s)
The routine creates an empty wproto.WatchInterface object and calls parseInto with the object wproto.WatchInterface and the string s as arguments.
References occam.watchparse2.parseInto().
def occam.watchparse2.parseInto (proto, s)
The parseInto routine calls the build_interface function with the the parsed object returned from parser.parse(), along with the proto object as input.
References occam.watchparse2.build_interface().
Referenced by occam.watchparse2.parse().
def occam.watchparse2.t_error (t)
def occam.watchparse2.t_ID (t)
def occam.watchparse2.t_INT (t)
def occam.watchparse2.t_MVAR (t)
def occam.watchparse2.t_RE (t)
def occam.watchparse2.t_REL (t)
def occam.watchparse2.t_STR (t)
def occam.watchparse2.t_VAR (t)
Variable Documentation
tuple occam.watchparse2.lexer = lex.lex(lextab='watchlex2',outputdir=PARSE_DIR)
string occam.watchparse2.literals = "[](){},;:"
tuple occam.watchparse2.PARSE_DIR = os.path.join(os.path.dirname(__file__), 'ply')
tuple occam.watchparse2.parser = yacc.yacc(outputdir=PARSE_DIR,debug=0)
dictionary occam.watchparse2.reserved
Initial value:
 = {
     'if'      : "IF",
     'then'    : "THEN",
     'else'    : "ELSE",
     'fail'    : "FAIL",
     'forward' : "FORWARD",
     'call'    : "CALL",
     'hook'    : "HOOK",
     '...'     : "ELIPSIS",
     'undef'   : "UNDEF",
     'return'  : "RETURN",
     'exclude' : "EXCLUDE"
 }
string occam.watchparse2.t_ignore = ' \r\n\t'
list occam.watchparse2.tokens
Initial value:
 = [
     "VAR" ,
     "MVAR" ,
     "REL" ,
     "RE" ,
     "STR" ,
     "INT"
 ]